// <auto-generated />
using System;
using MedicinesManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicinesManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230422183018_MedicinesInitialModel")]
    partial class MedicinesInitialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicinesManagement.Models.ActiveSubstance", b =>
                {
                    b.Property<Guid>("SubstanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MedicineID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubstanceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubstanceID");

                    b.HasIndex("MedicineID");

                    b.ToTable("ActiveSubstances");
                });

            modelBuilder.Entity("MedicinesManagement.Models.Medicine", b =>
                {
                    b.Property<Guid>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MedicineDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicineID");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("MedicinesManagement.Models.ActiveSubstance", b =>
                {
                    b.HasOne("MedicinesManagement.Models.Medicine", null)
                        .WithMany("ActiveSubstances")
                        .HasForeignKey("MedicineID");
                });

            modelBuilder.Entity("MedicinesManagement.Models.Medicine", b =>
                {
                    b.Navigation("ActiveSubstances");
                });
#pragma warning restore 612, 618
        }
    }
}
