apiVersion: v1
kind: Service
metadata:
    name: activesubstancesservice
spec: 
    type: NodePort
    selector:
        app: substancesmanagement
    ports:
        - name: "http-substances-management"
          protocol: TCP
          port: 80
          targetPort: 80