apiVersion: apps/v1
kind: Deployment
metadata:
    name: activesubstancesmanagement-depl
spec: 
    replicas: 1
    selector:
        matchLabels:
            app: substancesmanagement
    template: 
        metadata:
            labels:
                app: substancesmanagement
        spec: 
            containers: 
                - name: substancesmanagement
                  image: klekot789/activesubstancesmanagement:latest
                  ports:
                    - containerPort: 80
                      name: http       
                    - containerPort: 443
                      name: https
                  resources:
                    limits: 
                        memory: "4000Mi"
                        cpu: "650m"

---
apiVersion: v1
kind: Service
metadata:
    name: substancesmanagement-cluster-ip
spec:
    clusterIP: 10.96.0.38
    selector:   
        app: substancesmanagement
    ports:
        - name: substancesmanagement-http
          protocol: TCP
          port: 80
          targetPort: 80
        - name: substancesmanagement-https
          protocol: TCP
          port: 443
          targetPort: 443


                    
