apiVersion: v1
kind: Service
metadata: 
    name: activesubstancesservice-loadbalancer
spec:
    type: LoadBalancer
    selector:
        app: substancesmanagement
    ports:
        - name: http-substances-management  
          protocol: TCP
          port: 23965
          targetPort: 80