// <auto-generated />
using System;
using ActiveSubstancesManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActiveSubstancesManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230508095927_predefined data")]
    partial class predefineddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActiveSubstancesManagement.Models.Interaction", b =>
                {
                    b.Property<Guid>("InteractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InteractedSubstanceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InteractionLevelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicineID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InteractionID");

                    b.HasIndex("InteractionLevelID");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("ActiveSubstancesManagement.Models.InteractionLevel", b =>
                {
                    b.Property<Guid>("InteractionLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InteractionLevelDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InteractionLevelID");

                    b.ToTable("InteractionsLevel");
                });

            modelBuilder.Entity("ActiveSubstancesManagement.Models.Interaction", b =>
                {
                    b.HasOne("ActiveSubstancesManagement.Models.InteractionLevel", "InteractionLevel")
                        .WithMany()
                        .HasForeignKey("InteractionLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InteractionLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
