insert into ActiveSubstances 
values(NEWID(), 'Naproxenum natricum'),
(NEWID(), 'Amlodipini besilas'),
(NEWID(), 'Ciprofloxacinum'),
(NEWID(), 'Irbesartanum'),
(NEWID(), 'Amphotericinum B'),
(NEWID(), 'Natrii hydroxybutyras'),
(NEWID(), 'Roxithromycinum'),
(NEWID(), 'Rivastigminum'),
(NEWID(), 'Acidum ursodeoxycholicum'),
(NEWID(), 'Repaglinidum'),
(NEWID(), 'Neomycini sulfas'),
(NEWID(), 'Articaini hydrochloridum'),
(NEWID(), 'Adrenalinum'),
(NEWID(), 'Atorvastatinum calcicum'),
(NEWID(), 'Tramadoli hydrochloridum'),
(NEWID(), 'Zopiclonum'),
(NEWID(), 'Alprazolamum'),
(NEWID(), 'Ticlopidini hydrochloridum'),
(NEWID(), 'Citalopramum'),
(NEWID(), 'Montelukastum'),
(NEWID(), 'Diclofenacum natricum'),
(NEWID(), 'Misoprostolum'),
(NEWID(), 'Factor VII coagulationis humanus'),
(NEWID(), 'Cetirizini dihydrochloridum'),
(NEWID(), 'Pefloxacini mesylas'),
(NEWID(), 'Acidum lacticum'),
(NEWID(), 'Acidum salicylicum'),
(NEWID(), 'Acetylcysteinum'),
(NEWID(), 'Acidum acetylsalicylicum'),
(NEWID(), 'Acidum acetylsalicylicum do'),
(NEWID(), 'Acidum ascorbicum'),
(NEWID(), 'Adenosinum'),
(NEWID(), 'Ambroxoli hydrochloridum'),
(NEWID(), 'Oxymetazolini hydrochloridum'),
(NEWID(), 'Pentoxifyllinum'),
(NEWID(), 'Biperideni lactas'),
(NEWID(), 'Biperideni hydrochloridum'),
(NEWID(), 'Erythromycinu'),
(NEWID(), 'Erythromycinum '),
(NEWID(), 'Erythromycinum'),
(NEWID(), 'Benzoylis peroxydum'),
(NEWID(), 'Proxymetacaini hydrochloridum'),
(NEWID(), 'Kalii canrenoas'),
(NEWID(), 'Melphalanum'),
(NEWID(), 'Natalizumabum'),
(NEWID(), 'Dihydroxyaluminii natrii carbonas'),
(NEWID(), 'Cyproteroni acetas'),
(NEWID(), 'Phenylephrini hydrochloridum'),
(NEWID(), 'Amoxicillinum natricum'),
(NEWID(), 'Acidum clavulanicum'),
(NEWID(), 'Amoxicillinum'),
(NEWID(), 'Flucitosinum'),
(NEWID(), 'Magnesii subcarbonas'),
(NEWID(), 'Calcii carbonas'),
(NEWID(), 'Antithrombinum humanum III'),
(NEWID(), 'Carboplatinum'),
(NEWID(), 'Paracetamolum'),
(NEWID(), 'Sodu czteroboran'),
(NEWID(), 'Sulfogaiacolum'),
(NEWID(), 'Pipecuronii bromidum'),
(NEWID(), 'Chloroquini phosphas'),
(NEWID(), 'Sulfathiazolum argentum'),
(NEWID(), 'Esomeprazolum (esomeprazol magnezowy, amorficzny)'),
(NEWID(), 'Hydroxyzini hydrochloridum'),
(NEWID(), 'Atenololum'),
(NEWID(), 'Moclobemidum'),
(NEWID(), 'Sulfamethoxazolum'),
(NEWID(), 'Trimethoprimum'),
(NEWID(), 'Trimebutinum'),
(NEWID(), 'Beta-metylodigoksyna'),
(NEWID(), 'Ibuprofenum'),
(NEWID(), 'Enalaprili maleas'),
(NEWID(), 'Dexpanthenolum'),
(NEWID(), 'Povidonum iodinatum'),
(NEWID(), 'Polyvidonum iodinatum'),
(NEWID(), 'Betaxololi hydrochloridum'),
(NEWID(), 'Verapamili hydrochloridum'),
(NEWID(), 'Sotaloli hydrochloridum'),
(NEWID(), 'Fluoxetinum'),
(NEWID(), 'Białko surowicy ludzkiej'),
(NEWID(), 'Pranoprofenum'),
(NEWID(), 'Bromocriptini mesylas'),
(NEWID(), 'Riluzolum'),
(NEWID(), 'Hyoscini butylbromidum'),
(NEWID(), 'Phenylbutazonum'),
(NEWID(), 'Calcii pantothenas'),
(NEWID(), 'Sulfonianu polistyrenu sól wapniowa'),
(NEWID(), 'Tasonermin'),
(NEWID(), 'Carbo activatus'),
(NEWID(), 'Dexrazoxanum'),
(NEWID(), 'Doxazosini mesilas'),
(NEWID(), 'Doxazosinum'),
(NEWID(), 'Diclofenacum kalicum'),
(NEWID(), 'Pirenoxinum natricum'),
(NEWID(), 'Vinpocetinum'),
(NEWID(), 'Tacrolimus'),
(NEWID(), 'Amoxicillinum trihydricum'),
(NEWID(), 'Cefoperazonum'),
(NEWID(), 'Betamethasoni natrii phosphas'),
(NEWID(), 'Desloratadinum'),
(NEWID(), 'Pseudoephedrini sulfas'),
(NEWID(), 'Chlorquinaldolum'),
(NEWID(), 'Chlorprothixeni hydrochloridum'),
(NEWID(), 'Suxamethonii chloridum'),
(NEWID(), 'Hymecromonum'),
(NEWID(), 'Cholini salicylas'),
(NEWID(), 'Ciprofloxacini hydrochloridum'),
(NEWID(), 'Loratadinum'),
(NEWID(), 'Enoxaparinum natricum'),
(NEWID(), 'Clopamidum'),
(NEWID(), 'Zuclopenthixoli dihydrochloridu'),
(NEWID(), 'Zuclopenthixoli acetas'),
(NEWID(), 'Zuclopenthixoli decanoas'),
(NEWID(), 'Clomifeni citras'),
(NEWID(), 'Clotrimazolum'),
(NEWID(), 'Tianeptinum'),
(NEWID(), 'Mometasoni furoas'),
(NEWID(), 'Bisoprololi fumaras'),
(NEWID(), 'Podophyllotoxinum'),
(NEWID(), 'Pantoprazolum'),
(NEWID(), 'Acidum valproicum'),
(NEWID(), 'Amiodaroni hydrochloridum'),
(NEWID(), 'Nandroloni decanoas'),
(NEWID(), 'Fludrocortisoni acetas'),
(NEWID(), 'Losartanum kalicum'),
(NEWID(), 'Natrii cromoglicas'),
(NEWID(), 'Ganciclovirum'),
(NEWID(), 'Cytarabinum'),
(NEWID(), 'Prednisonum'),
(NEWID(), 'Ciclopirox olaminum'),
(NEWID(), 'Spironolactonum'),
(NEWID(), 'Clindamycini palmitas'),
(NEWID(), 'Clindamycini hydrochloridum'),
(NEWID(), 'Clindamycinum'),
(NEWID(), 'Clindamycini phosphas'),
(NEWID(), 'Tolterodini tartras'),
(NEWID(), 'Lamivudinum'),
(NEWID(), 'Triptorelinum'),
(NEWID(), 'Ambroxoli hydrochloridu'),
(NEWID(), 'Natrii valproas'),
(NEWID(), 'Desferoxamini mesilas'),
(NEWID(), 'Dexamethasonum'),
(NEWID(), 'Dexamethasoni natrii phosphas'),
(NEWID(), 'Ethinylestradiolum'),
(NEWID(), 'Fluconazolum'),
(NEWID(), 'Diltiazemi hydrochloridum'),
(NEWID(), 'Promethazini hydrochloridum'),
(NEWID(), 'Propofolum'),
(NEWID(), 'Betamethasoni dipropionas'),
(NEWID(), 'Magnesii valproas'),
(NEWID(), 'Levothyroxinum natricum'),
(NEWID(), 'Oxybutynini hydrochloridum'),
(NEWID(), 'Iprazochromum'),
(NEWID(), 'Dobutamini hydrochloridum'),
(NEWID(), 'Coffeinum'),
(NEWID(), 'Methyldopum'),
(NEWID(), 'Midazolami maleas'),
(NEWID(), 'Cefadroxilum'),
(NEWID(), 'Mebeverini hydrochloridum'),
(NEWID(), 'Urapidili hydrochloridum'),
(NEWID(), 'Olej z wątroby rekina'),
(NEWID(), 'Vancomycini hydrochloridum'),
(NEWID(), 'Paracetamolum '),
(NEWID(), 'Etilefrini hydrochloridum'),
(NEWID(), ''),
(NEWID(), 'Isosorbidi mononitras'),
(NEWID(), 'Fluorouracilum'),
(NEWID(), 'Lidocainum'),
(NEWID(), 'Prilocainum'),
(NEWID(), 'Prednisolonum'),
(NEWID(), 'Tapentadolum'),
(NEWID(), 'Cyclophosphamidum'),
(NEWID(), 'Phenytoinum natricum'),
(NEWID(), 'symetykon '),
(NEWID(), 'Dimeticonum'),
(NEWID(), 'Estradiolum'),
(NEWID(), 'Acidum tranexamicum'),
(NEWID(), 'Piroxicamum'),
(NEWID(), 'Gestodenum'),
(NEWID(), 'Betainum anhydrousum'),
(NEWID(), 'Ferri hydroxidum dextranum'),
(NEWID(), 'Ferri hydroxidum saccharum'),
(NEWID(), 'Fluvoxamini maleas'),
(NEWID(), 'Flupentixoli decanoas'),
(NEWID(), 'Fluocinoloni acetonidum'),
(NEWID(), 'Fluorometholonum'),
(NEWID(), 'Fluoresceinum natricum'),
(NEWID(), 'Flutamidum'),
(NEWID(), 'Isofluranum'),
(NEWID(), 'Nadroparinum calcicum'),
(NEWID(), 'Furaginum '),
(NEWID(), 'Gentamicini sulfas'),
(NEWID(), 'Nilotinibum'),
(NEWID(), 'nilotinib'),
(NEWID(), 'Somatropinum'),
(NEWID(), 'Ginkgo bilobae extractum '),
(NEWID(), 'Cholini alfosceras'),
(NEWID(), 'Nicethamidum'),
(NEWID(), 'Glucosum'),
(NEWID(), 'Acarbosum'),
(NEWID(), 'Trandolaprilum'),
(NEWID(), 'Metronidazolum'),
(NEWID(), 'Midodrini hydrochloridum'),
(NEWID(), 'Econazoli nitras'),
(NEWID(), 'Panitumumabum'),
(NEWID(), 'Bencyclani fumaras'),
(NEWID(), 'Opipramoli dihydrochloridum'),
(NEWID(), 'Cetylpyridinii chloridum'),
(NEWID(), 'Clomethiazoli edisylas'),
(NEWID(), 'Ornithini aspartas'),
(NEWID(), 'Timonacicum'),
(NEWID(), 'Heparinum natricum'),
(NEWID(), 'Amoksycylina trójwodna'),
(NEWID(), 'Mucopolisaccharidum polisulphatum'),
(NEWID(), 'Ifosfamidum'),
(NEWID(), 'Insulinum lisprum injectio neutralis'),
(NEWID(), 'Natrii hyaluronas'),
(NEWID(), 'Hydrocortisonum'),
(NEWID(), 'Chlortalidonum'),
(NEWID(), 'Etomidatum'),
(NEWID(), 'Azathioprinum'),
(NEWID(), 'Amorolfini hydrochloridum'),
(NEWID(), 'Cilazaprilum'),
(NEWID(), 'Nifuroxazidum'),
(NEWID(), 'Insulinum humanum isophanum'),
(NEWID(), 'Drospirenonum'),
(NEWID(), 'Hyperici intractum'),
(NEWID(), 'Oleum sojae purificatum'),
(NEWID(), 'Pregabalinum'),
(NEWID(), 'Kalii iodidum'),
(NEWID(), 'Docetaxelum'),
(NEWID(), 'Kalii chloridum'),
(NEWID(), 'Hydroxycarbamidum'),
(NEWID(), 'Ketamini hydrochloridum'),
(NEWID(), 'Ketoprofenum'),
(NEWID(), 'Ketoprofenu'),
(NEWID(), 'Clarithromycinum'),
(NEWID(), 'Norethisteroni acetas'),
(NEWID(), 'Clozapinum'),
(NEWID(), 'Lincomycini hydrochloridum'),
(NEWID(), 'Pancreatinum'),
(NEWID(), 'Lactulosum'),
(NEWID(), 'Terbinafini hydrochloridum'),
(NEWID(), 'Thioguaninum'),
(NEWID(), 'Hydrocortisoni butyras'),
(NEWID(), 'Mianserini hydrochloridum'),
(NEWID(), 'Bromazepamum'),
(NEWID(), 'Lidocaini hydrochloridum'),
(NEWID(), 'Lincomycinum'),
(NEWID(), 'Afliberceptum'),
(NEWID(), 'Ciprofibratum'),
(NEWID(), 'Fenofibratum (zmikronizowany)'),
(NEWID(), 'Desogestrelum'),
(NEWID(), 'Cetuximabum'),
(NEWID(), 'Lithii carbonas'),
(NEWID(), 'Tibolonu'),
(NEWID(), 'Amorolfinum'),
(NEWID(), 'Flumetasoni pivalas'),
(NEWID(), 'Clioquinolum'),
(NEWID(), 'Benazeprili hydrochloridu'),
(NEWID(), 'Benazeprili hydrochloridum'),
(NEWID(), 'Minoxidilum'),
(NEWID(), 'Leuprorelini acetas'),
(NEWID(), 'Maprotilini hydrochloridum'),
(NEWID(), 'Nifuratelum'),
(NEWID(), 'Nystatinum'),
(NEWID(), 'Levodopum'),
(NEWID(), 'Benserazidi hydrochloridum'),
(NEWID(), 'Bupiwakainy chlorowodorek'),
(NEWID(), 'Epinefryny winian'),
(NEWID(), 'Bupivacaini hydrochloridum'),
(NEWID(), 'Gabapentinum'),
(NEWID(), 'Extractum propolis, ekstrahent- etanol'),
(NEWID(), 'Sevofluranum'),
(NEWID(), 'Methylprednisolonum'),
(NEWID(), 'Buspironi hydrochloridum'),
(NEWID(), 'Meropenemum trihydricum'),
(NEWID(), 'Indometacinum'),
(NEWID(), 'Thiamazolum'),
(NEWID(), 'Metoprololi tartras'),
(NEWID(), 'Methylprednisoloni natrii succinas'),
(NEWID(), 'Levonorgestrelum'),
(NEWID(), 'Allopurinolum'),
(NEWID(), 'Carbacholi chloridum'),
(NEWID(), 'Acidum zoledronicum'),
(NEWID(), 'Fosfomycinum'),
(NEWID(), 'Fosfomycinum '),
(NEWID(), 'Trometamolum '),
(NEWID(), 'mikonazol'),
(NEWID(), 'Mazipredoni hydrochloridum'),
(NEWID(), 'Bifonazolum'),
(NEWID(), 'Ureum'),
(NEWID(), 'Tolperisoni hydrochloridum'),
(NEWID(), 'Undecylenamidum'),
(NEWID(), 'Zinci undecylenas'),
(NEWID(), 'Busulfanum'),
(NEWID(), 'Ambenonii chloridum'),
(NEWID(), 'Carbidopum'),
(NEWID(), 'Vinorelbini tartras'),
(NEWID(), 'Acitretinum'),
(NEWID(), 'Phosphocreatinum natricum'),
(NEWID(), 'Carbamazepinum'),
(NEWID(), 'Nicotinum (w postaci kompleksu żywicy nikotynowej'),
(NEWID(), 'Nicergolinum'),
(NEWID(), 'Nimodipinum'),
(NEWID(), 'Nitrazepamum'),
(NEWID(), 'Nitrendipinum'),
(NEWID(), 'Galantamini hydrobromidum'),
(NEWID(), 'Ketoconazolum'),
(NEWID(), 'Norfloxacinum'),
(NEWID(), 'Tamoxifeni citras'),
(NEWID(), 'Piracetamum'),
(NEWID(), 'Quinagolidum'),
(NEWID(), 'Pridinoli hydrochloridum'),
(NEWID(), 'Iohexolum'),
(NEWID(), 'Gadodiamidum'),
(NEWID(), 'Lynestrenolum'),
(NEWID(), 'Omeprazolum'),
(NEWID(), 'Phenoxymethylpenicillinum kalicum'),
(NEWID(), 'Benzathini phenoxymethylpenicillinum'),
(NEWID(), 'Estriolum'),
(NEWID(), 'Oxazepamum'),
(NEWID(), 'Oxytocinum'),
(NEWID(), 'Nonoxinolum'),
(NEWID(), 'Mesalazinum'),
(NEWID(), 'Glyceroli trinitras'),
(NEWID(), 'Capsaicinum'),
(NEWID(), 'Ethosuximidum'),
(NEWID(), 'Triamcinoloni acetonidum'),
(NEWID(), 'Tigecyclinum'),
(NEWID(), 'Natamycinum'),
(NEWID(), 'Neomycinum'),
(NEWID(), 'Felodipinum'),
(NEWID(), 'Methoxypolyethylene glycolum-epoetinum beta'),
(NEWID(), 'Triamcinolonum'),
(NEWID(), 'Candesartanum cilexetili'),
(NEWID(), 'Sevelameri carbonas'),
(NEWID(), 'Gonadotrophinum chorionicum'),
(NEWID(), 'Dinoprostonum'),
(NEWID(), 'Denotivirum'),
(NEWID(), 'Tribenosidum'),
(NEWID(), 'Progesteronum'),
(NEWID(), 'Promazini hydrochloridum'),
(NEWID(), 'Finasteridum'),
(NEWID(), 'Sabalis serrulatae extractum'),
(NEWID(), 'Alprostadilum'),
(NEWID(), 'Propafenoni hydrochloridum'),
(NEWID(), 'Medroxyprogesteroni acetas'),
(NEWID(), 'Zinci oxidum'),
(NEWID(), 'Mentholum'),
(NEWID(), 'Propolis extractum'),
(NEWID(), 'Benzocainum'),
(NEWID(), 'Budesonidum'),
(NEWID(), 'Dornasum alfa'),
(NEWID(), 'Acidum thiocticum'),
(NEWID(), 'Ranitidini hydrochloridum'),
(NEWID(), 'Rease'),
(NEWID(), 'Diazepamum'),
(NEWID(), 'Beta Aescinum'),
(NEWID(), 'Natrii polistyreni sulfonas'),
(NEWID(), 'Spiramycinum'),
(NEWID(), 'Azithromycinum'),
(NEWID(), 'Vigabatrinum'),
(NEWID(), 'Cetalkonii chloridum'),
(NEWID(), 'Ciclosporinum'),
(NEWID(), 'Octreotidi acetas'),
(NEWID(), 'Mepivacaini hydrochloridum'),
(NEWID(), 'Sennae foliolum'),
(NEWID(), 'Fluoxetini hydrochloridum'),
(NEWID(), 'Acenocoumarolum'),
(NEWID(), 'Acidum azelaicum'),
(NEWID(), 'Diosmectitum'),
(NEWID(), 'Ethanolum'),
(NEWID(), 'Alcohol isopropylicus'),
(NEWID(), 'Sucha masa bezbiałkowego dializatu z krwi cieląt'),
(NEWID(), 'Zolpidemi tartras'),
(NEWID(), 'Echinacaeae herbae recentis succus '),
(NEWID(), 'Farfarae succus'),
(NEWID(), 'Hyperici succus'),
(NEWID(), 'Taraxaci succus'),
(NEWID(), 'Sulfasalazinum w postaci granulatu z powidonem -'),
(NEWID(), 'Cytisinum'),
(NEWID(), 'Ginkgo bilobae extractum'),
(NEWID(), 'Teicoplaninum'),
(NEWID(), 'Piperacillinum Natricum'),
(NEWID(), 'Tazobactamum natricum'),
(NEWID(), 'Thymostimulinum'),
(NEWID(), 'Theophyllinum'),
(NEWID(), 'Immunoglobulinum antilymphocytum (królicza)'),
(NEWID(), 'Timololi maleas'),
(NEWID(), 'Levomepromazini maleas'),
(NEWID(), 'Levomepromazinum'),
(NEWID(), 'Tobramycini sulfas'),
(NEWID(), 'Thiethylperazini dimaleas'),
(NEWID(), 'Atracurii besilas'),
(NEWID(), 'Kalii clorazepas'),
(NEWID(), 'Dikalii clorazepas'),
(NEWID(), 'Isoconazoli nitras'),
(NEWID(), 'Methotrexatum'),
(NEWID(), 'Dorzolamidi hydrochloridum'),
(NEWID(), 'Epinephrinum'),
(NEWID(), 'Distigmini bromidum'),
(NEWID(), 'Iopromidum'),
(NEWID(), 'Sultamycyllinum'),
(NEWID(), 'Testosteroni undecanoas'),
(NEWID(), 'Mesnum'),
(NEWID(), 'Cefovecin'),
(NEWID(), 'o-beta-hydroxyethylrutosidae'),
(NEWID(), 'Mebendazolum'),
(NEWID(), 'Tretinoinum'),
(NEWID(), 'Sulodexidum'),
(NEWID(), 'Cholecalciferolum'),
(NEWID(), 'Cholecalciferolum (proszek)'),
(NEWID(), 'Amantadini hydrochloridum'),
(NEWID(), 'Tromantadini hydrochloridum'),
(NEWID(), 'Thiamini hydrochloridum (vitaminum '),
(NEWID(), 'Duloxetinum'),
(NEWID(), 'Natrii iodidum'),
(NEWID(), 'Xylometazolini hydrochloridum'),
(NEWID(), 'Idarubicini hydrochloridum'),
(NEWID(), 'Sildenafilum'),
(NEWID(), 'tert-Butylamini perindoprilum'),
(NEWID(), 'Indapamidum'),
(NEWID(), 'Simvastatinum'),
(NEWID(), 'Ondansetroni hydrochloridum dihydricum'),
(NEWID(), 'Goserelini acetas'),
(NEWID(), 'Silodosinum'),
(NEWID(), 'Quinaprili hydrochloridum'),
(NEWID(), 'Methylprednisoloni aceponas'),
(NEWID(), 'Mycophenolas mofetil'),
(NEWID(), 'Carvedilolum'),
(NEWID(), 'Natrii fusidas'),
(NEWID(), 'Acidum fusidicum hemihydricum'),
(NEWID(), 'Telmisartanum'),
(NEWID(), 'Hydrochlorothiazidum'),
(NEWID(), 'Diflucortoloni valeras'),
(NEWID(), 'Tamsulosini hydrochloridum'),
(NEWID(), 'Morphini sulfas'),
(NEWID(), 'Natrii fluoridum'),
(NEWID(), 'Lansoprazolum'),
(NEWID(), 'Rilmenidinum'),
(NEWID(), 'Troxerutinum'),
(NEWID(), 'Tacalcitolum monohydricum'),
(NEWID(), 'Etofenamatum'),
(NEWID(), 'Benzyli nicotinas'),
(NEWID(), 'Indinaviri sulfas'),
(NEWID(), 'Pancuronii bromidum'),
(NEWID(), 'Olanzapinum'),
(NEWID(), 'Benserazidum'),
(NEWID(), 'Morphini hydrochloridum'),
(NEWID(), 'Donepezili hydrochloridum'),
(NEWID(), 'Irinotecani hydrochloridum'),
(NEWID(), 'Antithrombinum III'),
(NEWID(), 'Aseptinu'),
(NEWID(), 'Urticae radicis extractum siccum'),
(NEWID(), 'Sevofluranu'),
(NEWID(), 'Doxycyclinum'),
(NEWID(), 'Sertralini hydrochloridum'),
(NEWID(), 'Pyridoxini hydrochloridum (Vitaminum '),
(NEWID(), 'Terazosini dihydricum hydrochloridum'),
(NEWID(), 'Imatinibum'),
(NEWID(), 'Azelastini hydrochloridum'),
(NEWID(), 'Beta Hydroxyethylrutosidum'),
(NEWID(), 'Levocetirizini dihydrochloridum'),
(NEWID(), 'Desmopressini acetas'),
(NEWID(), 'Zidovudinum'),
(NEWID(), 'Cefuroximum natricum'),
(NEWID(), 'Filgrastimum'),
(NEWID(), 'Dalteparinum natricum'),
(NEWID(), 'Codeini phosphas'),
(NEWID(), 'Acamprosatum'),
(NEWID(), 'Cefadroxilum monohydricum'),
(NEWID(), 'Tramadoli hydrochloridu'),
(NEWID(), 'Atorvastatinum calcicum trihydricu'),
(NEWID(), 'Paraffinum liquidum'),
(NEWID(), 'Ondansetronum'),
(NEWID(), 'Amlodipini besilas '),
(NEWID(), 'Rocuronii bromidum'),
(NEWID(), 'Sennae angustifoliae fructus extractum siccum'),
(NEWID(), 'Glipizidum'),
(NEWID(), 'Calcitoninum salmonis'),
(NEWID(), 'Formoteroli fumaras'),
(NEWID(), 'Dextromethorphani hydrobromidum'),
(NEWID(), 'Clopidogrelum'),
(NEWID(), 'Aciclovirum natricum'),
(NEWID(), 'Selegilini hydrochloridum'),
(NEWID(), 'Somatostatinum'),
(NEWID(), 'Interferonum beta'),
(NEWID(), 'Moxonidinum'),
(NEWID(), 'Sildenafili citras'),
(NEWID(), 'Ornithini asparta'),
(NEWID(), 'Dinitrogenii oxidum >'),
(NEWID(), 'Alfuzosini hydrochloridum'),
(NEWID(), 'Latanoprostum'),
(NEWID(), 'Cisatracurii besilas'),
(NEWID(), 'Bezbiałkowy dializat z krwi cieląt'),
(NEWID(), 'Acemetacinum'),
(NEWID(), 'Rituximabum'),
(NEWID(), 'Lanreotidi acetas'),
(NEWID(), 'Entacaponum'),
(NEWID(), 'Naftifini hydrochloridum'),
(NEWID(), 'Candesartanum cilexetilum'),
(NEWID(), 'Enrofloxacinum'),
(NEWID(), 'Cefazolinum natricum'),
(NEWID(), 'Megestroli acetas'),
(NEWID(), 'Acidum mefenamicum'),
(NEWID(), 'Raloxifeni hydrochloridum'),
(NEWID(), 'Remifentanili hydrochloridum'),
(NEWID(), 'Follitropinum alfa'),
(NEWID(), 'Efavirenzum'),
(NEWID(), 'Ferri proteinatosuccinas'),
(NEWID(), 'Naproxenum'),
(NEWID(), 'Propylthiouracilum'),
(NEWID(), 'Fosamprenavirum'),
(NEWID(), 'Albuminum humanum'),
(NEWID(), 'Milrinonum'),
(NEWID(), 'Doxorubicini hydrochloridum'),
(NEWID(), 'Fluorometholoni acetas'),
(NEWID(), 'Celecoxibum'),
(NEWID(), 'Sumatriptanum'),
(NEWID(), 'Pantoprazolum natricum sesquihydricum'),
(NEWID(), 'Fotemustinum'),
(NEWID(), 'Iodixanolum'),
(NEWID(), 'lewamizolu chlorowodorek'),
(NEWID(), 'Cabergolinum'),
(NEWID(), 'Lisinoprilum dihydricum'),
(NEWID(), 'Imiquimodum'),
(NEWID(), 'Triptorelini acetas'),
(NEWID(), 'Cetrorelixum'),
(NEWID(), 'Fenofibratum'),
(NEWID(), 'Venlafaxini hydrochloridum'),
(NEWID(), 'Hexylresorcinolum'),
(NEWID(), 'Benzalkonii chloridum'),
(NEWID(), 'Captoprilum'),
(NEWID(), 'Abacaviri sulfas'),
(NEWID(), 'Carbocisteinum'),
(NEWID(), 'Carbocisteinum do'),
(NEWID(), 'Emedastini difumaras'),
(NEWID(), 'Cerebrolysinum'),
(NEWID(), 'Temozolomidum'),
(NEWID(), 'Palivizumabum'),
(NEWID(), 'Oxcarbazepinum'),
(NEWID(), 'Naproxen Hasc'),
(NEWID(), 'Oxygeniu'),
(NEWID(), 'Moroctocogum alfa'),
(NEWID(), 'Fipronil'),
(NEWID(), 'Ofloxacinum'),
(NEWID(), 'Trimetazidini dihydrochloridum'),
(NEWID(), 'Amisulpridum'),
(NEWID(), 'Reboxetinum'),
(NEWID(), 'Adapalenum'),
(NEWID(), 'Dexibuprofenum'),
(NEWID(), 'Piribedilum'),
(NEWID(), 'Ranitidinum'),
(NEWID(), 'Tiapridum'),
(NEWID(), 'Atosibanum'),
(NEWID(), 'Insulina ludzka rekombinowana'),
(NEWID(), 'Mesalazinu'),
(NEWID(), 'Trastuzumabum'),
(NEWID(), 'Benfothiaminum'),
(NEWID(), 'Harpagophyti extractum aq. Siccum'),
(NEWID(), 'Sulfasalazinum (w postaci mieszaniny z powidonem)'),
(NEWID(), 'Brimonidini tartras'),
(NEWID(), 'Pemetrexedum'),
(NEWID(), 'Clobetasoli propionas'),
(NEWID(), 'Aciclovirum'),
(NEWID(), 'Eprosartanum'),
(NEWID(), 'Dydrogesteronum'),
(NEWID(), 'Brinzolamidum'),
(NEWID(), 'Epoetinum beta'),
(NEWID(), 'Natrii chloridum'),
(NEWID(), 'Montelukastum natricum'),
(NEWID(), 'Trimebutini maleas'),
(NEWID(), 'Insulinum aspartum'),
(NEWID(), 'Ganirelixi acetas'),
(NEWID(), 'Rutosidum trihydricum'),
(NEWID(), 'Nomegestroli acetas'),
(NEWID(), 'Alverini citras'),
(NEWID(), 'Simeticonum'),
(NEWID(), 'Degarelix'),
(NEWID(), 'Cinacalcetum'),
(NEWID(), 'Fluvastatinum'),
(NEWID(), 'Insulinum humanum'),
(NEWID(), 'Terazosinum'),
(NEWID(), 'Capecitabinum'),
(NEWID(), 'Sirolimusum'),
(NEWID(), 'Triptorelini pamoas'),
(NEWID(), 'Kalii clavulonas'),
(NEWID(), 'Mupirocinum'),
(NEWID(), 'Citaloprami hydrobromidum'),
(NEWID(), 'Follitropinum beta'),
(NEWID(), 'Gadobutrolum'),
(NEWID(), 'Infliximabum'),
(NEWID(), 'Nateglinide'),
(NEWID(), 'Levetiracetamum'),
(NEWID(), 'Esomeprazolum magnesicum'),
(NEWID(), 'Esomeprazolum'),
(NEWID(), 'Betahistini dihydrochloridum'),
(NEWID(), 'Amlodipinum'),
(NEWID(), 'Alprazolamu'),
(NEWID(), 'Levodropropizinum'),
(NEWID(), 'Saccharum'),
(NEWID(), 'Gliclazidum'),
(NEWID(), 'Rasagilinum'),
(NEWID(), 'Dihydrocodeini tartras'),
(NEWID(), 'Interferonum pegylateum alfa'),
(NEWID(), 'Linezolidum'),
(NEWID(), 'Verteporfin'),
(NEWID(), 'Furosemidum'),
(NEWID(), 'Aqua ad iniectabili'),
(NEWID(), 'Danazolum'),
(NEWID(), 'Nefopami hydrochloridum'),
(NEWID(), 'Lercanidipini hydrochloridum'),
(NEWID(), 'Valsartanum'),
(NEWID(), 'Dextranum'),
(NEWID(), 'Hypromellosum'),
(NEWID(), 'Glycine max.semen extractum siccum'),
(NEWID(), 'Diosminum'),
(NEWID(), 'Factor IX coagulationis humanus'),
(NEWID(), 'Dinatrii pamidronas'),
(NEWID(), 'Dinitrogenii oxidum nie mniej niż'),
(NEWID(), 'Glucosum (roztwór'),
(NEWID(), 'Tobramycinum'),
(NEWID(), 'Rasburicasum'),
(NEWID(), 'Hedera helix extractum'),
(NEWID(), 'Eletriptanum'),
(NEWID(), 'Acidum tolfenamicum'),
(NEWID(), 'Celiprololi hydrochloridum'),
(NEWID(), 'Nikotyna z kationitem'),
(NEWID(), 'Diosminu'),
(NEWID(), 'Dalteparinum natricum ad.'),
(NEWID(), 'Diphenhydramini hydrochloridum'),
(NEWID(), 'Vaccinum hepatitidis B (ADNr)'),
(NEWID(), 'Nabumetonum'),
(NEWID(), 'Sertralinum'),
(NEWID(), 'Amlodipini maleas'),
(NEWID(), 'Lymecyclinum (równoważna tetracyklinie)'),
(NEWID(), 'Pimecrolimusum'),
(NEWID(), 'Buprenorphinum'),
(NEWID(), 'Sevelamerum'),
(NEWID(), 'Sevelameri hydrochloridum'),
(NEWID(), 'Agalsidasum beta'),
(NEWID(), 'Lamotriginu'),
(NEWID(), 'Lamotriginum'),
(NEWID(), 'Mitotanum'),
(NEWID(), 'Pojedyncze alergoidy pyłków roślin'),
(NEWID(), 'Ferrum'),
(NEWID(), 'Ferri hydroxydum polymaltosum'),
(NEWID(), 'Carbomerum'),
(NEWID(), 'Menotropinum humanum'),
(NEWID(), 'Heparynoidy'),
(NEWID(), 'Peginterferonum alfa'),
(NEWID(), 'Nicotinum'),
(NEWID(), 'Factor VIII coagulationis humanus'),
(NEWID(), 'Ertapenemum'),
(NEWID(), 'Benzoxonii chloridum'),
(NEWID(), 'Lutropinum alfa'),
(NEWID(), 'Oseltamivirum'),
(NEWID(), 'Voriconazolum'),
(NEWID(), 'Atorvastatinum'),
(NEWID(), 'Nicergolinu'),
(NEWID(), 'Donepezili hydrochloridum monohydricum'),
(NEWID(), 'Vardenafilum'),
(NEWID(), 'Tadalafilum'),
(NEWID(), 'Nimesulidum'),
(NEWID(), 'Meloxicamu'),
(NEWID(), 'Plantaginis lanceolatae herbae extractun fluidum '),
(NEWID(), 'Atorvastatinum calcicum trihydricum'),
(NEWID(), 'Ribavirinum'),
(NEWID(), 'Aluminii acetotartras'),
(NEWID(), 'Etacridini lactas'),
(NEWID(), 'Naproxenu'),
(NEWID(), 'Oxygenium nie mniej niż'),
(NEWID(), 'Memantini hydrochloridum'),
(NEWID(), 'Paroxetini hydrochloridum'),
(NEWID(), 'Sunitinibum'),
(NEWID(), 'Camphorum'),
(NEWID(), 'Paraffinum liquidu'),
(NEWID(), 'Cefuroximum'),
(NEWID(), 'Cefuroximum axetilum'),
(NEWID(), 'Ambazonum'),
(NEWID(), 'Prothrombinum multiplex humanum'),
(NEWID(), 'Pyridostigmini bromidum'),
(NEWID(), 'Glycerolum'),
(NEWID(), 'Olopatadini hydrochloridum'),
(NEWID(), 'Omalizumabum'),
(NEWID(), 'Dienogestum'),
(NEWID(), 'Sufentanilum (cytrynian)'),
(NEWID(), 'toremifenum'),
(NEWID(), 'Ioversolum'),
(NEWID(), 'Isotretinoinum'),
(NEWID(), 'Metformini hydrochloridum'),
(NEWID(), 'Nitrogenii oxidu'),
(NEWID(), 'Acidum undecylenicum'),
(NEWID(), 'Cynarae extractum siccum'),
(NEWID(), 'Amitriptylinum hydrochloridum'),
(NEWID(), 'Glycinis seminis extractum siccum'),
(NEWID(), 'Zaleplonum'),
(NEWID(), 'Calcii dobesilas'),
(NEWID(), 'Białko'),
(NEWID(), 'Letrozolum'),
(NEWID(), 'Cefotaximum natricum'),
(NEWID(), 'Cefotaximum'),
(NEWID(), 'Maropitant citrate'),
(NEWID(), 'Maropitant'),
(NEWID(), 'Imidaprili hydrochloridum'),
(NEWID(), 'Estradioli valeras'),
(NEWID(), 'Ibuprofenum q.s'),
(NEWID(), 'Wyciągi alergenow'),
(NEWID(), 'Ceftriaxonum natricum'),
(NEWID(), 'Ioflupanum '),
(NEWID(), 'Enfuvirtidum'),
(NEWID(), 'NeoRecormo'),
(NEWID(), 'Reteplasum'),
(NEWID(), 'Teriparatidum'),
(NEWID(), 'Basiliximabum'),
(NEWID(), 'Fondaparinuxum natricum'),
(NEWID(), 'Fulvestrantum'),
(NEWID(), 'Interferonum alfa'),
(NEWID(), 'Insulinum lisprum'),
(NEWID(), 'Thyrotropinum alfa'),
(NEWID(), 'Iloprostum'),
(NEWID(), 'Ibritumomabum tiuxetanum'),
(NEWID(), 'Yttrii '),
(NEWID(), 'Pegvisomantum '),
(NEWID(), 'Caspofunginum'),
(NEWID(), 'Anakinrum'),
(NEWID(), 'Darbepoetinum alfa'),
(NEWID(), 'Insulinum detemirum'),
(NEWID(), 'Vivanz'),
(NEWID(), 'Isopropanolum'),
(NEWID(), 'Tenofovirum disoproxilum'),
(NEWID(), 'Emtricitabinum'),
(NEWID(), 'Chondroityny siarczan kwaśny'),
(NEWID(), 'Cefoperazonum natricum'),
(NEWID(), 'Sulbactamum natricum'),
(NEWID(), 'Levofloxacinum'),
(NEWID(), 'Paroxetinum'),
(NEWID(), 'Ibuprofenu'),
(NEWID(), 'Anastrozolum'),
(NEWID(), 'Sertindolum'),
(NEWID(), 'Estazolamum'),
(NEWID(), 'Zincum'),
(NEWID(), 'Amlodipine besilate'),
(NEWID(), 'Darifenacinum'),
(NEWID(), 'Stalev'),
(NEWID(), 'Salbutamoli sulfas'),
(NEWID(), 'Sumatriptani succinas'),
(NEWID(), 'gadoksetynian disodowy'),
(NEWID(), 'Sumatriptani succina'),
(NEWID(), 'Esomeprazol sodowy'),
(NEWID(), 'Arsenii trioxidum'),
(NEWID(), 'Quetiapinum'),
(NEWID(), 'Everolimusum'),
(NEWID(), 'Nicotynamidum'),
(NEWID(), 'Ciclesonidu'),
(NEWID(), 'Ramiprilum'),
(NEWID(), 'Bexarotene'),
(NEWID(), 'Mercaptamini bitartras'),
(NEWID(), 'Acidum carglumicum'),
(NEWID(), 'Ammonii bituminosulfonas'),
(NEWID(), 'Natrii ibandronas monohydricum'),
(NEWID(), 'Meloxicamum'),
(NEWID(), 'Zofenoprilum calcicum'),
(NEWID(), 'Solifenacyny bursztynia'),
(NEWID(), 'Epinastyny chlorowodorek'),
(NEWID(), 'Rosuvastatinum calicum'),
(NEWID(), 'Deferasiroxum'),
(NEWID(), 'Pseudoephedrini hydrochloridum'),
(NEWID(), 'Betamethasonum'),
(NEWID(), 'Alclometasoni dipropionas'),
(NEWID(), 'Mirtazapinum hemihydricum'),
(NEWID(), 'Metoprololi succinas'),
(NEWID(), 'Acidum mycophenolicum'),
(NEWID(), 'Rifaximinum'),
(NEWID(), 'Etoricoxibum'),
(NEWID(), 'Ezetimibum'),
(NEWID(), 'Saquinavirum'),
(NEWID(), 'Butaconazoli nitras'),
(NEWID(), 'Dapagliflozinum'),
(NEWID(), 'Terbinafinum'),
(NEWID(), 'Tarcev'),
(NEWID(), 'Lapatinibum'),
(NEWID(), 'Quetiapini fumaras'),
(NEWID(), 'Nepafenac'),
(NEWID(), 'Posaconazolum'),
(NEWID(), 'Perindoprilum argininum'),
(NEWID(), 'Glimepiridum'),
(NEWID(), 'Macrogolum'),
(NEWID(), 'Fludarabini phosphas'),
(NEWID(), 'Zolpidemi tartra'),
(NEWID(), 'Ezetimibu'),
(NEWID(), 'Filgrastimu'),
(NEWID(), 'Aqua ad iniectabilia'),
(NEWID(), 'Hexylis aminolevulinatis hydrochloridum'),
(NEWID(), 'Aliskirenum'),
(NEWID(), 'Natrii chloridu'),
(NEWID(), 'Etonogestrelum'),
(NEWID(), 'Acidum alendronicum'),
(NEWID(), 'Sitagliptinum'),
(NEWID(), 'Carbo activatu'),
(NEWID(), 'Levonorgestrelu'),
(NEWID(), 'Iodum'),
(NEWID(), 'Acidum boricum'),
(NEWID(), 'Hydrogenii peroxidum'),
(NEWID(), 'Oxymetholonum'),
(NEWID(), 'Somatropinu'),
(NEWID(), 'Aprove'),
(NEWID(), 'Zinci aspartas'),
(NEWID(), 'Atomoxetini hydrochloridum'),
(NEWID(), 'Thymolum'),
(NEWID(), 'Immunoglobulinum humanum normal'),
(NEWID(), 'Travoprostum'),
(NEWID(), 'Timololum'),
(NEWID(), 'Neupr'),
(NEWID(), 'Perindoprilum'),
(NEWID(), 'Natrii phenylbutyras'),
(NEWID(), 'Immunoglobulinum humanum normale'),
(NEWID(), 'Carbetocinum'),
(NEWID(), 'Eplerenonum'),
(NEWID(), 'tert-Butylamini perindoprilu'),
(NEWID(), 'Omega'),
(NEWID(), 'Megestroli aceta'),
(NEWID(), 'Galsufaze'),
(NEWID(), 'Itraconazolum'),
(NEWID(), 'Dexketoprofenum'),
(NEWID(), 'Natrii valproa'),
(NEWID(), 'Acidum valproicu'),
(NEWID(), 'Beclometasoni dipropiona'),
(NEWID(), 'Risperidonum'),
(NEWID(), 'Simvastatinu'),
(NEWID(), 'Warfarinum natricum'),
(NEWID(), 'Alglukozydaza alfa'),
(NEWID(), 'Ranibizumabum'),
(NEWID(), 'Daptomycinum'),
(NEWID(), 'Ceftiofurum'),
(NEWID(), 'Tetracyclini hydrochloridum'),
(NEWID(), 'Calcii gluconas'),
(NEWID(), 'Kolistyny siarczan'),
(NEWID(), 'Flumetryna'),
(NEWID(), 'Propoksur'),
(NEWID(), 'Carprofenum'),
(NEWID(), 'Oleum Jecoris Aselli'),
(NEWID(), 'tylozyna (w postaci fosforanu)'),
(NEWID(), 'Amitraza'),
(NEWID(), 'Levamisoli hydrochloridum'),
(NEWID(), 'Cefapirin benzathine'),
(NEWID(), 'Tiamulini hydrogenofumaras '),
(NEWID(), 'Bromhexini hydrochloridum'),
(NEWID(), 'Tiamulinum '),
(NEWID(), 'Detomidyny chlorowodorek '),
(NEWID(), 'Karbetocyna'),
(NEWID(), 'Doxycyclinum monohydricum'),
(NEWID(), 'Butorphanolum'),
(NEWID(), 'Ceftiofuri hydrochloridum'),
(NEWID(), 'Sapropterin dihydrochloride'),
(NEWID(), 'Oxytetracyclini hydrochloridum'),
(NEWID(), 'Marbofloksacyna'),
(NEWID(), 'Chlortetracyclini hydrochloridum'),
(NEWID(), 'Doxycyclini hyclas'),
(NEWID(), 'Paromomycyna'),
(NEWID(), 'Permethrinum'),
(NEWID(), 'Piryproxyfen'),
(NEWID(), 'insulina wieprzowa'),
(NEWID(), 'Ampicillinum trihydricum'),
(NEWID(), 'Karazololu chlorowodorek'),
(NEWID(), 'Ivermectinum'),
(NEWID(), 'Tafluprostum'),
(NEWID(), 'Fluniksyna'),
(NEWID(), 'Azaperon'),
(NEWID(), 'Propentofylina'),
(NEWID(), 'Ketaminum'),
(NEWID(), 'Pyranteli embonas '),
(NEWID(), 'Imidokarbu dipropionian'),
(NEWID(), 'Cefalexinum monohydricum'),
(NEWID(), 'Metamizolum natricum monohydricum'),
(NEWID(), 'busereliny octan'),
(NEWID(), 'Streptomycyny siarczan'),
(NEWID(), 'Benzylpenicillinum procainum'),
(NEWID(), 'Sulfadoxinum'),
(NEWID(), 'Ziprasidonum'),
(NEWID(), 'Cefacetryl sodowy'),
(NEWID(), 'Fentanylum'),
(NEWID(), 'Glatirameri acetas'),
(NEWID(), 'stiripentolum'),
(NEWID(), 'Mirtazapinum'),
(NEWID(), 'Heminum humanum'),
(NEWID(), 'Exenatidum'),
(NEWID(), 'Chlorhexidini digluconas'),
(NEWID(), 'Phleum pratense'),
(NEWID(), 'Venlafaxinum'),
(NEWID(), 'Tetralysa'),
(NEWID(), 'Treprostinilum'),
(NEWID(), 'alfa'),
(NEWID(), 'Doconazolum'),
(NEWID(), 'Topiramatum'),
(NEWID(), 'Nelarabinum'),
(NEWID(), 'Vildagliptinum'),
(NEWID(), 'Desmopressinum'),
(NEWID(), 'Tobramycinum '),
(NEWID(), 'recombinant human erythropoietin alfa'),
(NEWID(), 'Epoetinum alfa'),
(NEWID(), 'Erythropoietinum alfa humanum recombinatum'),
(NEWID(), 'Maraviroc'),
(NEWID(), 'Anidulafunginum'),
(NEWID(), 'Pravastatinum natricum'),
(NEWID(), 'Fesoterodine'),
(NEWID(), 'Rimantadini hydrochloridum'),
(NEWID(), 'Temsirolimusum'),
(NEWID(), 'Natrii risedronas'),
(NEWID(), 'Rupatadinum'),
(NEWID(), 'Escitalopramum'),
(NEWID(), 'D-Kloprostenol'),
(NEWID(), 'Immunoglobulinum humanum anti-D'),
(NEWID(), 'Fenbendazol '),
(NEWID(), 'Tylmikozyna'),
(NEWID(), 'Calciglu'),
(NEWID(), 'Flumechina'),
(NEWID(), 'Tylozyna '),
(NEWID(), 'Oksytetracyklina'),
(NEWID(), 'Magnesii sulfas'),
(NEWID(), 'Clofarabine'),
(NEWID(), 'Flumetazon'),
(NEWID(), 'Tiamfenikol'),
(NEWID(), 'Fungidermi'),
(NEWID(), 'Florfenicolum'),
(NEWID(), 'Enrofloksacyna Vetos-Farm'),
(NEWID(), 'Alfaprostol'),
(NEWID(), 'Tibolonum'),
(NEWID(), 'Micafunginum'),
(NEWID(), 'Praziquantelum'),
(NEWID(), 'Fenylopropanoloamina'),
(NEWID(), 'Flunixin meglumine'),
(NEWID(), 'Trilostan'),
(NEWID(), 'Sól sodowa deksakloprostenolu'),
(NEWID(), 'Iodum do'),
(NEWID(), 'Medetomidini hydrochloridum'),
(NEWID(), 'Policresulenum'),
(NEWID(), 'Trabectedinum'),
(NEWID(), 'Azytromycyna dwuwodna'),
(NEWID(), 'Nebivololum'),
(NEWID(), 'Raltegrawir'),
(NEWID(), 'Glucosaminum'),
(NEWID(), 'Fludeoxyglucosum'),
(NEWID(), 'Tizanidinum'),
(NEWID(), 'Topotecanum'),
(NEWID(), 'Methylprednisoloni acetas'),
(NEWID(), 'Eculizumab'),
(NEWID(), 'Dorzolamidum'),
(NEWID(), 'OxyConti'),
(NEWID(), 'Oxycodoni hydrochloridum'),
(NEWID(), 'Immunoglobulin huma'),
(NEWID(), 'Bacitracinum'),
(NEWID(), 'Tolterodini hydrogenotartras'),
(NEWID(), 'Nebivololi hydrochloridum'),
(NEWID(), 'Melissae herbae recentis intractum '),
(NEWID(), 'Chlorambucilum'),
(NEWID(), 'Mometasoni furoas (zmikronizowany)'),
(NEWID(), 'Clopidogrelum hydrosulfas'),
(NEWID(), 'Gamitromycyna'),
(NEWID(), 'Tylwalozyna'),
(NEWID(), 'Tylvalosin'),
(NEWID(), 'Oksym milbemycyny'),
(NEWID(), 'Praziquantelum '),
(NEWID(), 'Tetracainum'),
(NEWID(), 'Sugammadexum'),
(NEWID(), 'Danofloksacyna'),
(NEWID(), 'Methylnaltrexoni bromidum'),
(NEWID(), 'Lacosamidum'),
(NEWID(), 'Urticae succus'),
(NEWID(), 'Hexamidini diisetionas'),
(NEWID(), 'Tilmicosinum'),
(NEWID(), 'vinorelbinum'),
(NEWID(), 'Doxycycline hyclate'),
(NEWID(), 'Pyriproxyfenum'),
(NEWID(), 'Proligeston'),
(NEWID(), 'Natrii alendronas'),
(NEWID(), 'Enilkonazol'),
(NEWID(), 'Ronidazol'),
(NEWID(), 'Clonidini hydrochloridum'),
(NEWID(), 'Tocilizumabum'),
(NEWID(), 'Mycobacterium bovis BCG, sczep duński'),
(NEWID(), 'Spektynomycyna'),
(NEWID(), 'Aliskireni hemifumaras'),
(NEWID(), 'kloprostenol sodowy'),
(NEWID(), 'Glucagoni hydrochloridum'),
(NEWID(), 'Flubendazol'),
(NEWID(), 'Silybi mariani extractum siccum'),
(NEWID(), 'Pramipexolum'),
(NEWID(), 'Agomelatinum'),
(NEWID(), 'Prasugrelum'),
(NEWID(), 'Telbivudinum'),
(NEWID(), 'Pyrantel tartrate'),
(NEWID(), 'Hydroxocobalamin'),
(NEWID(), 'Certolizumabum pegol'),
(NEWID(), 'Romiplostim'),
(NEWID(), 'Bicalutamidum'),
(NEWID(), 'Metocard Z'),
(NEWID(), 'Amprolium chlorowodorek'),
(NEWID(), 'Tacrolimusum monohydricum')

insert into ActiveSubstances
values(NEWID(), 'Ergometryny maleinian '),
(NEWID(), 'Olanzapini benzoas'),
(NEWID(), 'Eflornithinum'),
(NEWID(), 'Nimvasti'),
(NEWID(), 'Etanerceptum'),
(NEWID(), 'Isoniazidum'),
(NEWID(), 'Inhibitor '),
(NEWID(), 'Metronidazolu'),
(NEWID(), 'Imiglucerasum'),
(NEWID(), 'Golimumabum'),
(NEWID(), 'Gefitinibum'),
(NEWID(), 'Firocoxib'),
(NEWID(), 'Liraglutidum'),
(NEWID(), 'Peforelinum'),
(NEWID(), 'Hydrocortisoni acetas'),
(NEWID(), 'Immunoglobulinum humanum normale (IgG)'),
(NEWID(), 'Białko osocza ludzkiego'),
(NEWID(), 'Valganciclovirum'),
(NEWID(), 'Sitagliptinu'),
(NEWID(), 'Plerixafor'),
(NEWID(), 'Saxagliptin'),
(NEWID(), 'Osaterone acetate'),
(NEWID(), 'Acidum'),
(NEWID(), 'Ropiniroli hydrochloridum'),
(NEWID(), 'Interferon rekombinowany'),
(NEWID(), 'Nevirapinum'),
(NEWID(), 'Immunoglobulinum humanum hepatitidis B'),
(NEWID(), 'Vinflunine ditartrate'),
(NEWID(), 'Torasemidum'),
(NEWID(), 'Cilazaprilum monohydricum'),
(NEWID(), 'Moxifloxacini hydrochloridum'),
(NEWID(), 'Indacateroli maleas'),
(NEWID(), 'Amantadini sulfas'),
(NEWID(), 'Dexmedetomidinum'),
(NEWID(), 'Tulathromycin'),
(NEWID(), 'Toceranibum'),
(NEWID(), 'Vedaprofenum '),
(NEWID(), 'Selamectin'),
(NEWID(), 'Mavacoxib'),
(NEWID(), 'Dibotermin alfa'),
(NEWID(), 'Escitalopramum w postaci szczawianu -'),
(NEWID(), 'Escitalopramum w postaci'),
(NEWID(), 'Escitalopramum w posatci szczawianu -'),
(NEWID(), 'Eltrombopagum'),
(NEWID(), 'Rivastigmine'),
(NEWID(), 'Escitaloprami oxalas'),
(NEWID(), 'Ciclopiroxum'),
(NEWID(), 'Rivastigmine Sando'),
(NEWID(), 'Clopidogrelum besilate'),
(NEWID(), 'Tocofersolanum'),
(NEWID(), 'Dinitrogenii oxidum'),
(NEWID(), 'Oxygenium'),
(NEWID(), 'Spiritus salicylatus'),
(NEWID(), 'Progesteronum (mikronizowany)'),
(NEWID(), 'Imatinibi mesilas'),
(NEWID(), 'Żelazo (w postaci derizomaltozy żelazowej)'),
(NEWID(), 'Rosuvastatinum'),
(NEWID(), 'Rivastigmini hydrogenotartras'),
(NEWID(), 'Wyciąg alergenów z pyłków traw '),
(NEWID(), 'Roflumilastum'),
(NEWID(), 'Thymi extractum fluidum'),
(NEWID(), 'Mannitolum'),
(NEWID(), 'Ibuprofenum lysinum'),
(NEWID(), 'Tizanidini hydrochloridum'),
(NEWID(), 'Fluticasoni propionas'),
(NEWID(), 'Exemestanum'),
(NEWID(), 'Zolmitriptanum'),
(NEWID(), 'Suvardi'),
(NEWID(), 'Olanzapine Apote'),
(NEWID(), 'Asenapinum '),
(NEWID(), 'Corifollitropin alfa'),
(NEWID(), 'Conestatum alfa'),
(NEWID(), 'Paroxetini hydrochloridum (semihydricum)'),
(NEWID(), 'Chlormadinoni acetas'),
(NEWID(), 'Bendamustini hydrochloridum'),
(NEWID(), 'Olmesartanum medoxomilum'),
(NEWID(), 'Azomy'),
(NEWID(), 'Neoclarity'),
(NEWID(), 'Białko całkowite (mniej /równo'),
(NEWID(), 'Imipenemum'),
(NEWID(), 'Cilastatinum natricum'),
(NEWID(), 'Menotropina'),
(NEWID(), 'Rabeprazolum natricum'),
(NEWID(), 'Butorphanolum Otoczka Opadry II'),
(NEWID(), 'Sennae fructus angustifoliae'),
(NEWID(), 'Sennae folium'),
(NEWID(), 'Prednisoloni acetas'),
(NEWID(), 'Toltrazurilum'),
(NEWID(), 'Telmisartanu'),
(NEWID(), 'Itopridi hydrochloridum'),
(NEWID(), 'Epoetinum theta'),
(NEWID(), 'Olanzapiny dichlorowodorek trójwodny'),
(NEWID(), 'Sarolaner'),
(NEWID(), 'Carprofenum do'),
(NEWID(), 'Orlistatum'),
(NEWID(), 'Ketotifeni hydrofumaras'),
(NEWID(), 'Atipamezoli hydrochloridum'),
(NEWID(), 'Kompleks dekstranu i żelaza (III)'),
(NEWID(), 'Oxydolo'),
(NEWID(), 'Kalii bromidum'),
(NEWID(), 'Amaryl'),
(NEWID(), 'Glucosu'),
(NEWID(), 'Hydroxycarbamid Tev'),
(NEWID(), 'Bactrim Fort'),
(NEWID(), 'Clorsulon'),
(NEWID(), 'Tilmicosini phosphas'),
(NEWID(), 'Salbutamolum'),
(NEWID(), 'Triptorelini embonas'),
(NEWID(), 'Cimicoxibum'),
(NEWID(), 'Cabazitaxelum'),
(NEWID(), 'Bicalutamide Accor'),
(NEWID(), 'Natrii pentosani polysulfas'),
(NEWID(), 'Ropinirolum'),
(NEWID(), 'Fingolimodum'),
(NEWID(), 'Itraconazolu'),
(NEWID(), 'Leflunomidum'),
(NEWID(), 'Fibrinogenum humanum'),
(NEWID(), 'Coffeini citras'),
(NEWID(), 'Propolis extractu'),
(NEWID(), 'Butamirati citras'),
(NEWID(), 'Lovastatinum'),
(NEWID(), 'Glucosamini sulfas'),
(NEWID(), 'Bromfenacum'),
(NEWID(), 'Diethylamini salicylas'),
(NEWID(), 'Cyproheptadini hydrochloridum'),
(NEWID(), 'Factor humanus von Willebrandi'),
(NEWID(), 'Zuclopenthixoli dihydrochloridum'),
(NEWID(), 'Pantoprazolum '),
(NEWID(), 'Salmeterolu ksynafonian'),
(NEWID(), 'Acidum ibandronicum'),
(NEWID(), 'Propofolum '),
(NEWID(), 'tylozyna (w postaci winianu)'),
(NEWID(), 'Fiproni'),
(NEWID(), 'Tianeptinum natricum'),
(NEWID(), 'Denosumabum'),
(NEWID(), 'Galantaminum'),
(NEWID(), 'Gonadorelinum'),
(NEWID(), 'Gonadorelini acetas'),
(NEWID(), 'Tildipirozinum'),
(NEWID(), 'Instany'),
(NEWID(), 'Pimobendanum '),
(NEWID(), 'Thiotepum'),
(NEWID(), 'Loperamidi hydrochloridum'),
(NEWID(), 'Atorwastyatyna z L-lizyną'),
(NEWID(), 'Rizatriptani benzoas'),
(NEWID(), 'Cholecalciferolum, pulvis'),
(NEWID(), 'Furaginum'),
(NEWID(), 'Cisatracurium Kab'),
(NEWID(), 'Levocetirizini dihydrochloridum '),
(NEWID(), 'Szczepionka wieloważna'),
(NEWID(), 'Imidaclopridum'),
(NEWID(), 'Amikacini sulfas'),
(NEWID(), 'Debrida'),
(NEWID(), 'Hedera helix extractum ekstrahent-etanol'),
(NEWID(), 'Roze'),
(NEWID(), 'Rybosomy bakteryjne'),
(NEWID(), 'Proteoglikany'),
(NEWID(), 'Rivaroxaban'),
(NEWID(), 'Inhibac'),
(NEWID(), 'Calcium-Sandoz Fort'),
(NEWID(), 'Cellulosum microcristallinum'),
(NEWID(), 'Phenobarbitalum '),
(NEWID(), 'Zobux'),
(NEWID(), 'Adrenalinu'),
(NEWID(), 'Prilactone Nex'),
(NEWID(), 'Saxagliptinum'),
(NEWID(), 'Pioglitazonum'),
(NEWID(), 'Euthyrox N'),
(NEWID(), 'Luteny'),
(NEWID(), 'Suxibuzone (microcapsules)'),
(NEWID(), 'Racecadotrilum'),
(NEWID(), 'Salmeterolum'),
(NEWID(), 'Xifaxa'),
(NEWID(), 'Concor'),
(NEWID(), 'Telmisartan Actavi'),
(NEWID(), 'Diprosali'),
(NEWID(), 'Convival Chron'),
(NEWID(), 'Nicorette FreshMint Gu'),
(NEWID(), 'Diosmectiteum'),
(NEWID(), 'Deslorelin acetate'),
(NEWID(), 'Tobre'),
(NEWID(), 'Vandetanib'),
(NEWID(), 'Vemurafenibum'),
(NEWID(), 'Fidaxomicin'),
(NEWID(), 'Loges'),
(NEWID(), 'Femode'),
(NEWID(), 'Mydocalm Fort'),
(NEWID(), 'Accordeo'),
(NEWID(), 'Zinna'),
(NEWID(), 'Xana'),
(NEWID(), 'Perito'),
(NEWID(), 'Bactroba'),
(NEWID(), 'Reparil Gel '),
(NEWID(), 'Kidofe'),
(NEWID(), 'Quinaprilum'),
(NEWID(), 'Mirtage'),
(NEWID(), 'AC'),
(NEWID(), 'Ivipri'),
(NEWID(), 'Ferrosi sulfas'),
(NEWID(), 'Acidum folicum'),
(NEWID(), 'Calcii glubionas'),
(NEWID(), 'Betaloc ZOK'),
(NEWID(), 'Canakinumabum'),
(NEWID(), 'Betaser'),
(NEWID(), 'Cornerege'),
(NEWID(), 'Tiapridi hydrochloridum'),
(NEWID(), 'Levofloxacini hemihydras'),
(NEWID(), 'Theraflu Max Gri'),
(NEWID(), 'Kroskarmelozy sól sodowa'),
(NEWID(), 'Metamizolum natricum'),
(NEWID(), 'Rupatadini fumaras'),
(NEWID(), 'Vizarsi'),
(NEWID(), 'Dapoxetinum'),
(NEWID(), 'Tapentadoli hydrochloridum'),
(NEWID(), 'Povidonum'),
(NEWID(), 'Krzemionka koloidalna'),
(NEWID(), 'Oxycodoni hydrochloridum ad'),
(NEWID(), 'Ciclopiroxum ad'),
(NEWID(), 'Fucidi'),
(NEWID(), 'Glycopyrronii bromidum'),
(NEWID(), 'Trider'),
(NEWID(), 'Verege'),
(NEWID(), 'Procto-Glyveno'),
(NEWID(), 'Aclidinii bromidum'),
(NEWID(), 'Capecitabine Glenmar'),
(NEWID(), 'Desloratadine Genephar'),
(NEWID(), 'Magnesii stearas'),
(NEWID(), 'Axitinibum'),
(NEWID(), 'Crizotinibum'),
(NEWID(), 'Brentuximabum vedotini'),
(NEWID(), 'Mifamurtidum'),
(NEWID(), 'Almotryptanu jabłczan'),
(NEWID(), 'Pentobarbital sodium'),
(NEWID(), 'Controlin'),
(NEWID(), 'Ecansy'),
(NEWID(), 'Urapidilum'),
(NEWID(), 'Francja 
 Austri'),
(NEWID(), 'Dalacin '),
(NEWID(), 'Oilatu'),
(NEWID(), 'Xylometazolin Tev'),
(NEWID(), 'Dexmedetomidini hydrochloridum'),
(NEWID(), 'Cataflam'),
(NEWID(), 'Cloprostenol Vey'),
(NEWID(), 'Sofosbuvirum'),
(NEWID(), 'Oekolp fort'),
(NEWID(), 'GeloProm'),
(NEWID(), 'Simvacard'),
(NEWID(), 'Sinupre'),
(NEWID(), 'Nitroxolinum'),
(NEWID(), 'Pharmathen International S.A'),
(NEWID(), 'Meteospasmy'),
(NEWID(), 'Floxa'),
(NEWID(), 'Chibroxi'),
(NEWID(), 'Sative'),
(NEWID(), 'Hyalga'),
(NEWID(), 'Duphasto'),
(NEWID(), 'Betadin'),
(NEWID(), 'Hiszpania 
 Hiszpani'),
(NEWID(), 'Cefquinomum'),
(NEWID(), 'Histige'),
(NEWID(), 'Voltaren Emulge'),
(NEWID(), 'Tranxen'),
(NEWID(), 'Mirzaten'),
(NEWID(), 'Primolut-No'),
(NEWID(), 'Urostad'),
(NEWID(), 'Duspatalin retar'),
(NEWID(), 'Nizora'),
(NEWID(), 'Lixisenatidum'),
(NEWID(), 'Zente'),
(NEWID(), 'Amlopin'),
(NEWID(), 'Concor Cor'),
(NEWID(), 'CoAprove'),
(NEWID(), 'Beto'),
(NEWID(), 'Kaldyu'),
(NEWID(), 'Tramadol Aurobind'),
(NEWID(), 'Midazolami hydrochloridum'),
(NEWID(), 'Storvas CR'),
(NEWID(), 'Procapen tubostrzykawk'),
(NEWID(), 'Mirabegronum'),
(NEWID(), 'Perindoprili tosilas'),
(NEWID(), 'Francja   
'),
(NEWID(), 'Irbesartan Zentiv'),
(NEWID(), 'Lorinden '),
(NEWID(), 'Nibi'),
(NEWID(), 'Cymeven'),
(NEWID(), 'Fampyr'),
(NEWID(), 'Digoxinum'),
(NEWID(), 'Bosutinib'),
(NEWID(), 'Bosutinibum'),
(NEWID(), 'Ocriplasminum'),
(NEWID(), 'Fusacid '),
(NEWID(), 'Marbofloksacyna do ustalenia p'),
(NEWID(), 'Ivermectinum do ustalenia p'),
(NEWID(), 'Monensin (Monensin sodium)'),
(NEWID(), 'Buscopa'),
(NEWID(), 'Betesd'),
(NEWID(), 'AzitroLEK'),
(NEWID(), 'Pertuzumabum'),
(NEWID(), 'Nalmefeni hydrochloridum dihydricum'),
(NEWID(), 'Nootropi'),
(NEWID(), 'Clenbuterol hydrochloride'),
(NEWID(), 'Agapurin SR'),
(NEWID(), 'Cerazett'),
(NEWID(), 'Vicks VapoRu'),
(NEWID(), 'Biosuis M.hyo, emulsja do wstrzykiwań dla świ'),
(NEWID(), 'Ferrii (III) isomaltosidum'),
(NEWID(), 'Kelacy'),
(NEWID(), 'Flupentixoli dihydrochloridum'),
(NEWID(), 'Dexamytre'),
(NEWID(), 'Escitalopramu'),
(NEWID(), 'Polmatin'),
(NEWID(), 'Vestib'),
(NEWID(), 'Arthry'),
(NEWID(), 'Apoque'),
(NEWID(), 'Oclacitinibum'),
(NEWID(), 'Regorafenibum'),
(NEWID(), 'Teriflunomidum'),
(NEWID(), 'Butorfanolu winian'),
(NEWID(), 'Duphala'),
(NEWID(), 'Vectra'),
(NEWID(), 'Nitrofuralu'),
(NEWID(), 'Cilostazolum'),
(NEWID(), 'Nicorette Classic Gu'),
(NEWID(), 'Wellico'),
(NEWID(), 'Theraflu Kasze'),
(NEWID(), 'Sintro'),
(NEWID(), 'Leflunomide meda'),
(NEWID(), 'Trastuzumabum emtansinum'),
(NEWID(), 'Dolutegravirum'),
(NEWID(), 'Dexlansoprazolum'),
(NEWID(), 'Octenisep'),
(NEWID(), 'Bisoprololi fumara'),
(NEWID(), 'Levopron'),
(NEWID(), 'Fluralanerum'),
(NEWID(), 'Olopatadinum'),
(NEWID(), 'Afoba'),
(NEWID(), 'Actraphane'),
(NEWID(), 'Loxapinum'),
(NEWID(), 'Aztreonamum'),
(NEWID(), 'Sacubitrilum'),
(NEWID(), 'Zomet'),
(NEWID(), 'Azilsartanum medoxomilum'),
(NEWID(), 'Emen'),
(NEWID(), 'Enurev Breezhale'),
(NEWID(), 'Ferripro'),
(NEWID(), 'Deferipronum'),
(NEWID(), 'Amifampridinum'),
(NEWID(), 'Perampanelum'),
(NEWID(), 'Urea'),
(NEWID(), 'Tenofovir Zentiv'),
(NEWID(), 'Methadoni hydrochloridum'),
(NEWID(), 'Xigdu'),
(NEWID(), 'Fenisti'),
(NEWID(), 'Lexota'),
(NEWID(), 'Cefepimi dihydrochloridum'),
(NEWID(), 'Bosentanum'),
(NEWID(), 'Alogliptinum'),
(NEWID(), 'Aqua pro injectione do'),
(NEWID(), 'Rufinamidum'),
(NEWID(), 'Kinzalmon'),
(NEWID(), 'Leflunomide Zentiv'),
(NEWID(), 'Legant'),
(NEWID(), 'Rotigotinum'),
(NEWID(), 'Lomitapidum'),
(NEWID(), 'Perflutrenum'),
(NEWID(), 'Toxinum botulinicum typum A ad iniectabile'),
(NEWID(), 'Augmenti'),
(NEWID(), 'Hormon folikulotropowy'),
(NEWID(), 'Lacidipinum'),
(NEWID(), 'Bimatoprost'),
(NEWID(), 'Acidum cholicum'),
(NEWID(), 'Zonisamidum'),
(NEWID(), 'Pixantroni dimaleas'),
(NEWID(), 'Pravastatinum'),
(NEWID(), 'Eslicarbazepini acetas'),
(NEWID(), 'Lorazepamum'),
(NEWID(), 'Solifenacini succinas'),
(NEWID(), 'Protaphane InnoLe'),
(NEWID(), 'Protaphan'),
(NEWID(), 'Radium dichloridum R'),
(NEWID(), 'Sertraline Apote'),
(NEWID(), 'Vantav'),
(NEWID(), 'Cobicistatum'),
(NEWID(), 'Regadenosonum'),
(NEWID(), 'Insulinum degludecum'),
(NEWID(), 'Repaglinide Krk'),
(NEWID(), 'Acidum gadotericum'),
(NEWID(), 'Formoteroli fumaras dihydricus'),
(NEWID(), 'Elosulfasum alfa'),
(NEWID(), 'Phenobarbitalum'),
(NEWID(), 'Granisetroni hydrochloridum'),
(NEWID(), 'Besilesomabum'),
(NEWID(), 'Epoetinum zeta'),
(NEWID(), 'Kabozantynibum'),
(NEWID(), 'Vortioxetini hydrobromidum'),
(NEWID(), 'Pantoprazolum natricum sesquihydricum '),
(NEWID(), 'Phospholipidum essentiale'),
(NEWID(), 'Altrenogestum'),
(NEWID(), 'Mometasoni furoas monohydricum'),
(NEWID(), 'Trametinibum'),
(NEWID(), 'Brimonidinum'),
(NEWID(), 'Bromonidyna'),
(NEWID(), 'Riociguatum'),
(NEWID(), 'Factor XIII'),
(NEWID(), 'Pregabalin Pfize'),
(NEWID(), 'Fumaran dimetylu'),
(NEWID(), 'Azithromycinum dihydricum'),
(NEWID(), 'Fenticonazoli nitras'),
(NEWID(), 'Metyraponum'),
(NEWID(), 'Belar'),
(NEWID(), 'Ofloxacin'),
(NEWID(), 'Moxifloxacini hydrochloridu'),
(NEWID(), 'Pneumospecti'),
(NEWID(), 'Sulbactamum'),
(NEWID(), 'Biocan '),
(NEWID(), 'Lokren'),
(NEWID(), 'Propyphenazonum'),
(NEWID(), 'Klimadyno'),
(NEWID(), 'Lisinoprilum'),
(NEWID(), 'Translarn'),
(NEWID(), 'Obinutuzumabum'),
(NEWID(), 'Acidum fusidicum'),
(NEWID(), 'Bisacodylum'),
(NEWID(), 'Flutemetamolum'),
(NEWID(), 'Isoconazoli nitra'),
(NEWID(), 'Diflucortoloni valera'),
(NEWID(), 'Buprenorphini hydrochloridum'),
(NEWID(), 'Idelalizybum'),
(NEWID(), 'Inosinum pranobexum'),
(NEWID(), 'Benzydamini hydrochloridum'),
(NEWID(), 'Bortezomibum'),
(NEWID(), 'Dutasteridum'),
(NEWID(), 'Natrii citras'),
(NEWID(), 'Chondroitini sulfas'),
(NEWID(), 'Pivmecilinami hydrochloridum'),
(NEWID(), 'Omaco'),
(NEWID(), 'Hederae helicis folii extractum siccum'),
(NEWID(), 'Hydrocortisoni natrii phosphas'),
(NEWID(), 'Ruxolitinibum'),
(NEWID(), 'Aripiprazolum'),
(NEWID(), 'Cinacalcetii hydrochloridum'),
(NEWID(), 'Apomorphini hydrochloridum'),
(NEWID(), 'Espumisa'),
(NEWID(), 'Colchicinum'),
(NEWID(), 'Oxytocin'),
(NEWID(), 'Produkt złożony'),
(NEWID(), 'Atovaquonum'),
(NEWID(), 'Proguanili hydrochloridum'),
(NEWID(), 'Polidocanolum'),
(NEWID(), 'Eucalypti aetheroleum'),
(NEWID(), 'Albendazolum'),
(NEWID(), 'Desfera'),
(NEWID(), 'Azelastini hydrochloridu'),
(NEWID(), 'Valganciclovirum w postaci chlorowodorku:'),
(NEWID(), 'Acidum cromoglicicum'),
(NEWID(), 'Pasireotidum'),
(NEWID(), 'Noradrenalinum'),
(NEWID(), 'Adrenaline Acid Tartrate'),
(NEWID(), 'Insulinum glargine'),
(NEWID(), 'Apremilastum'),
(NEWID(), 'Spinosadum'),
(NEWID(), 'Naloxegolum'),
(NEWID(), 'Klacid Un'),
(NEWID(), 'Duloxetine Lill'),
(NEWID(), 'Secukinumabum'),
(NEWID(), 'Carteololi hydrochloridum'),
(NEWID(), 'Entacapone'),
(NEWID(), 'Hederae helicis folii extractum siccum '),
(NEWID(), 'Aceclofenacum'),
(NEWID(), 'Tetrabenazinum'),
(NEWID(), 'Landiololi hydrochloridum'),
(NEWID(), 'Ambroksol Hasc'),
(NEWID(), 'Olaparibum'),
(NEWID(), 'Afamelanotidum'),
(NEWID(), 'Milbemycini oxime'),
(NEWID(), 'Abacaviri hydrochloridum'),
(NEWID(), 'Ramucirumabum'),
(NEWID(), 'Eliglustatum'),
(NEWID(), 'Citicolinum natricum'),
(NEWID(), 'Nonacogum gamma (rDNA)'),
(NEWID(), 'Sevelamer carbonate Winthro'),
(NEWID(), 'Suveze'),
(NEWID(), 'Ezetymib'),
(NEWID(), 'Betamethasoni valeras'),
(NEWID(), 'Fipronilum'),
(NEWID(), 'Oroxin'),
(NEWID(), 'Levothyroxinum natricu'),
(NEWID(), 'Hydrocortisonum-S'),
(NEWID(), 'Cisatracurium'),
(NEWID(), 'Valerianae extractum hydroalcoholicum siccum'),
(NEWID(), 'Linezolid Zentiv'),
(NEWID(), 'Bedicort sali'),
(NEWID(), 'Ospemifenum'),
(NEWID(), 'Ceftazidimum pentahydricum'),
(NEWID(), 'Ceftazidimum'),
(NEWID(), 'Nitrogenii oxydum'),
(NEWID(), 'Ondansetroni hydrochloridum dihydricu'),
(NEWID(), 'Safinamidum'),
(NEWID(), 'Rasagilini tartras'),
(NEWID(), 'Progesterone'),
(NEWID(), 'Darunavirum'),
(NEWID(), 'Nobilis MS Liv'),
(NEWID(), 'Hepa-Merz'),
(NEWID(), 'Gynoxin Un'),
(NEWID(), 'Lewozymendan'),
(NEWID(), 'Ropivacaini hydrochloridum'),
(NEWID(), 'Triptorelini embona'),
(NEWID(), 'Advil Zatok'),
(NEWID(), 'Clotrimazolum Amar'),
(NEWID(), '(S)-methoprenum'),
(NEWID(), 'Dinotefuranum'),
(NEWID(), 'Caspofungini acetas'),
(NEWID(), 'Desloratadinu'),
(NEWID(), 'Desmopressini aceta'),
(NEWID(), 'Tedizolidii phosphas'),
(NEWID(), 'Desmopressinu'),
(NEWID(), 'Prazykwantel'),
(NEWID(), 'Ceritinibum'),
(NEWID(), 'Cangrelori tetranatricum'),
(NEWID(), 'Diosmectite'),
(NEWID(), 'Erythromycinum cum zinco'),
(NEWID(), 'Rosmarini oleum'),
(NEWID(), 'Duloxetini hydrochloridu'),
(NEWID(), 'Duloxetinu'),
(NEWID(), 'Tardyfero'),
(NEWID(), 'Escinum'),
(NEWID(), 'Zinci sulphas'),
(NEWID(), 'Naphazolini nitras'),
(NEWID(), 'Metronidazol Polpharm'),
(NEWID(), 'Dameliu'),
(NEWID(), 'Desfluranum'),
(NEWID(), 'Colistini sulfas'),
(NEWID(), 'Biofena'),
(NEWID(), 'Ibandronic Acid Myla'),
(NEWID(), 'Aluminii acetas tartras'),
(NEWID(), 'Eloco'),
(NEWID(), 'Alpicort '),
(NEWID(), 'Evolocumabum'),
(NEWID(), 'Pregabalin Zentiv'),
(NEWID(), 'Bupropioni hydrochloridum'),
(NEWID(), 'Dimetindeni maleas'),
(NEWID(), 'Silybi mariani fructus extractum siccum'),
(NEWID(), 'Tramapar Fort'),
(NEWID(), 'Rasagilini hemitartras'),
(NEWID(), 'Ziri'),
(NEWID(), 'Artill'),
(NEWID(), 'Flurhina'),
(NEWID(), 'Axuda'),
(NEWID(), 'Yasmi'),
(NEWID(), 'Diuve'),
(NEWID(), 'Izotek'),
(NEWID(), 'Lymecyclinum'),
(NEWID(), 'Duloxetini hydrochloridum'),
(NEWID(), 'Phenylephrinum'),
(NEWID(), 'Benzydamini hydrochloridu'),
(NEWID(), 'Cetylpyridinii chloridu'),
(NEWID(), 'Marbofloxacinum '),
(NEWID(), 'Drotaverini hydrochloridum'),
(NEWID(), 'Quetiapini fumara'),
(NEWID(), 'Alepto'),
(NEWID(), 'Gardasil'),
(NEWID(), 'Lenvatinibum'),
(NEWID(), 'Torseme'),
(NEWID(), 'Lenzett'),
(NEWID(), 'Lidocain-Egi'),
(NEWID(), 'Hirudoi'),
(NEWID(), 'ACC optim'),
(NEWID(), 'Escitalopram Aurovita'),
(NEWID(), 'Clobazamum'),
(NEWID(), 'Edoxabanum'),
(NEWID(), 'Agen'),
(NEWID(), 'Sarido'),
(NEWID(), 'Cinie'),
(NEWID(), 'Panobinostatum'),
(NEWID(), 'Miconazoli nitras'),
(NEWID(), 'Flurbiprofen'),
(NEWID(), 'Aspirin '),
(NEWID(), 'Foste'),
(NEWID(), 'Kreon Travi'),
(NEWID(), 'Voltaren SR'),
(NEWID(), 'Canespo'),
(NEWID(), 'Deprilep'),
(NEWID(), 'Doxylamini hydrogenosuccinas'),
(NEWID(), 'Adenosine Kab'),
(NEWID(), 'Citabax'),
(NEWID(), 'Ditriso'),
(NEWID(), 'Hetlio'),
(NEWID(), 'Indix Comb'),
(NEWID(), 'Lutetu '),
(NEWID(), 'Octenidini dihydrochloridum'),
(NEWID(), 'Phenoxyethanolum'),
(NEWID(), 'Prednisoloni hemisuccinas'),
(NEWID(), 'Chlorhexidini hydrochloridum'),
(NEWID(), 'Ortanol Ma'),
(NEWID(), 'Acidum deoxycholicum'),
(NEWID(), 'Lesin'),
(NEWID(), 'Alocutan Fort'),
(NEWID(), 'Alirocumabum'),
(NEWID(), 'Hygroto'),
(NEWID(), 'Sintrediu'),
(NEWID(), 'D-Cloprostenolum'),
(NEWID(), 'Fortran'),
(NEWID(), 'Tegafurum'),
(NEWID(), 'Gimeracilum'),
(NEWID(), 'Oteracilum'),
(NEWID(), 'Benzydamine hydrochloride'),
(NEWID(), 'Aripiprazole Sando'),
(NEWID(), 'Chlorphenamini maleas'),
(NEWID(), 'Solifenacin Medre'),
(NEWID(), 'Irinotecani hydrochloridum trihydricum'),
(NEWID(), 'Sebelipazum alfa'),
(NEWID(), 'Asfotasum alfa'),
(NEWID(), 'Bilokor'),
(NEWID(), 'Gentamicinum'),
(NEWID(), 'Femosto'),
(NEWID(), 'Flurbiprofenum'),
(NEWID(), 'Escitalopram Actavi'),
(NEWID(), 'Sanva'),
(NEWID(), 'Proki'),
(NEWID(), 'Afoxolanerum'),
(NEWID(), 'Ivabradine Anphar'),
(NEWID(), 'Acidum folinicum'),
(NEWID(), 'Ginkgo folii extractum siccum'),
(NEWID(), 'Dinatrii clodronas hedrahydricus'),
(NEWID(), 'Lidocainu'),
(NEWID(), 'Ipratropium /Salbutamol Cipl'),
(NEWID(), 'Solur'),
(NEWID(), 'Ipratropii bromidu'),
(NEWID(), 'Salbutamoli sulfa'),
(NEWID(), 'Robenacoxibum'),
(NEWID(), 'Onsio'),
(NEWID(), 'Ritonavirum'),
(NEWID(), 'Pegbovigrastim'),
(NEWID(), 'Diprogent'),
(NEWID(), 'Fortekor Plu'),
(NEWID(), 'Dacepto'),
(NEWID(), 'Essentiale fort'),
(NEWID(), 'Dostine'),
(NEWID(), 'Levofloxacini hemihydra'),
(NEWID(), 'Ketoprofenum lysinum'),
(NEWID(), 'Cobimetinibum'),
(NEWID(), 'Aspirin Cardi'),
(NEWID(), 'Androto'),
(NEWID(), 'Sarolanerum'),
(NEWID(), 'Fluorocholini '),
(NEWID(), 'Ivadia'),
(NEWID(), 'Cloprostenol'),
(NEWID(), 'Blinatumomabum'),
(NEWID(), 'Carfilzomibum'),
(NEWID(), 'Ivabradinum'),
(NEWID(), 'Ivabradini hydrochloridum'),
(NEWID(), 'Masitinib mesylate'),
(NEWID(), 'Monepantelum'),
(NEWID(), 'Pradofloxacinum'),
(NEWID(), 'Pyriprole'),
(NEWID(), 'Ivabradini oxala'),
(NEWID(), 'Hidrasec'),
(NEWID(), 'Tobrade'),
(NEWID(), 'Emodepsyd'),
(NEWID(), 'Prazikwantel'),
(NEWID(), 'Emodepsidum'),
(NEWID(), 'Imidaklopryd'),
(NEWID(), 'Moksydektyna'),
(NEWID(), 'Nobivac B'),
(NEWID(), 'Estriol'),
(NEWID(), 'Halofuginon'),
(NEWID(), 'Valnemulinum'),
(NEWID(), 'Axudan HC'),
(NEWID(), 'Amsacrinum'),
(NEWID(), 'Clomipramine hydrochloridum'),
(NEWID(), 'Remolexa'),
(NEWID(), 'Osurni'),
(NEWID(), 'Zulvac SB'),
(NEWID(), 'Furazidinum'),
(NEWID(), 'Cytote'),
(NEWID(), 'Glyceroli phenylbutyras'),
(NEWID(), 'Movali'),
(NEWID(), 'Permetrinum'),
(NEWID(), 'Amlodipini besila'),
(NEWID(), 'Pharmavat'),
(NEWID(), 'Bonade'),
(NEWID(), 'Canephron '),
(NEWID(), 'Tranexamic Acid Tillome'),
(NEWID(), 'Pegasparagasum'),
(NEWID(), 'Dinolytic Fort'),
(NEWID(), 'Amylmetacresolum'),
(NEWID(), 'Dichlorobenzyl Alcohol'),
(NEWID(), 'Latalu'),
(NEWID(), 'Avamina S'),
(NEWID(), 'Nasivin soft'),
(NEWID(), 'Deltametryna'),
(NEWID(), 'Eprynomektyna'),
(NEWID(), 'gentamycyna'),
(NEWID(), 'Moxifloxacinum'),
(NEWID(), 'Diforta'),
(NEWID(), 'Azithromycinum dihydricu'),
(NEWID(), 'Dutasteridu'),
(NEWID(), 'Carbidopum monohydricum'),
(NEWID(), 'Duloxetine hydrochloride'),
(NEWID(), 'Tagriss'),
(NEWID(), 'Osimertinibum'),
(NEWID(), 'Rozo'),
(NEWID(), 'Acidum acetylsalicylicum '),
(NEWID(), 'AirFluSa'),
(NEWID(), 'Fluticasoni propiona'),
(NEWID(), 'Methylprednisoloni natrii succina'),
(NEWID(), 'Caspofungini aceta'),
(NEWID(), 'Maxitro'),
(NEWID(), 'Latanoprost Horus Pharm'),
(NEWID(), 'Stilno'),
(NEWID(), 'Tardyferon-Fo'),
(NEWID(), 'Cinnarizinum'),
(NEWID(), 'Dimenhydrinatum'),
(NEWID(), 'Tadalafilum '),
(NEWID(), 'Oculobri'),
(NEWID(), 'Aprepitantum'),
(NEWID(), 'Akineto'),
(NEWID(), 'Macmiror Complex'),
(NEWID(), 'Lorista H'),
(NEWID(), 'Calcifediolum'),
(NEWID(), 'Bonogren S'),
(NEWID(), 'Oxytetracyclinum'),
(NEWID(), 'BioEquin '),
(NEWID(), 'Elice'),
(NEWID(), 'Ferrum (III)'),
(NEWID(), 'LisiHEXAL'),
(NEWID(), 'Acidum gadotericu'),
(NEWID(), 'Necitumumabum'),
(NEWID(), 'Lesinuradum'),
(NEWID(), 'Ethinylestradiolu'),
(NEWID(), 'Chlormadinoni aceta'),
(NEWID(), 'Bronle'),
(NEWID(), 'Ranitydyna Aurovita'),
(NEWID(), 'Ozenoxacinum'),
(NEWID(), 'Aldacton'),
(NEWID(), 'Cyclo'),
(NEWID(), 'Midian'),
(NEWID(), 'Formetic S'),
(NEWID(), 'Zy'),
(NEWID(), 'O-(beta-hydroxyethyl)-rutosidea (Oxerutins)'),
(NEWID(), 'Agrege'),
(NEWID(), 'Dexmedetomidinu'),
(NEWID(), 'Vardenafil hydrochloride trihydrat'),
(NEWID(), 'Brivaracetamum'),
(NEWID(), 'Adace'),
(NEWID(), 'Everolimus Tev'),
(NEWID(), 'Ertapenemum natricum'),
(NEWID(), 'Vitalipid N Infan'),
(NEWID(), 'Waki'),
(NEWID(), 'Tylosini tartars '),
(NEWID(), 'Zinery'),
(NEWID(), 'Eftrenonacogum alpha'),
(NEWID(), 'Clobasamum'),
(NEWID(), 'Pitolisantum'),
(NEWID(), 'Thiocolchicosidum'),
(NEWID(), 'Abacavirum'),
(NEWID(), 'Alfacalcidolu'),
(NEWID(), 'Naloxoni hydrochloridum'),
(NEWID(), 'Nasone'),
(NEWID(), 'Tenofovirum alafenamidum'),
(NEWID(), 'Trifluridinum'),
(NEWID(), 'Tipiracilum'),
(NEWID(), 'Arilin Rapi'),
(NEWID(), 'Briliqu'),
(NEWID(), 'Lorafe'),
(NEWID(), 'Travoprostu'),
(NEWID(), 'Timololi malea'),
(NEWID(), 'Glatirameri aceta'),
(NEWID(), 'Lorist'),
(NEWID(), 'Tacefu'),
(NEWID(), 'Iloprostu'),
(NEWID(), 'Tamsulosini hydrochloridu'),
(NEWID(), 'Metindol Retar'),
(NEWID(), 'Uptrav'),
(NEWID(), 'Pandemic influenza vaccine '),
(NEWID(), 'Albutrepenonacogum alfa'),
(NEWID(), 'Primun Salmonella '),
(NEWID(), 'Metoclopramidi hydrochloridum'),
(NEWID(), 'Mieszanina mentolu i izowalerianianu mentylu'),
(NEWID(), 'Idelvio'),
(NEWID(), 'Neparvi'),
(NEWID(), 'Atazanaviri sulfas'),
(NEWID(), 'Biblo'),
(NEWID(), 'KETREL X'),
(NEWID(), 'Palonosetroni hydrochloridum'),
(NEWID(), 'Entecavirum monohydricum'),
(NEWID(), 'Entecavirum'),
(NEWID(), 'Milgamma '),
(NEWID(), 'Erlotinibum'),
(NEWID(), 'Paxtin'),
(NEWID(), 'Nevirapinum anhydricum'),
(NEWID(), 'Reslizumabum'),
(NEWID(), 'Paracetamolum Farmalide'),
(NEWID(), 'Thiopentalum natricum et natrii carbonas'),
(NEWID(), 'Pimafucor'),
(NEWID(), 'Sunitinib Tev'),
(NEWID(), 'Ibuprofen Alta'),
(NEWID(), 'Clavasepti'),
(NEWID(), 'Propentofyllinum'),
(NEWID(), 'Vizibi'),
(NEWID(), 'Trazodone Neuraxphar'),
(NEWID(), 'Trazodoni hydrochloridum'),
(NEWID(), 'Tiopental sodowy'),
(NEWID(), 'Pioglitazone Accor'),
(NEWID(), 'Fenbendazolum'),
(NEWID(), 'Bexo'),
(NEWID(), 'Nervosol TAB'),
(NEWID(), 'Anastrozol Tev'),
(NEWID(), 'Zulbe'),
(NEWID(), 'Betiatide'),
(NEWID(), 'Propylene glycol'),
(NEWID(), 'Imatinib LEK-A'),
(NEWID(), 'Seizpa'),
(NEWID(), 'Mibre'),
(NEWID(), 'Atazanavirum'),
(NEWID(), 'Velpatasvirum'),
(NEWID(), 'Elbasvirum'),
(NEWID(), 'Grazoprevirum'),
(NEWID(), 'Skinore'),
(NEWID(), 'Cabomety'),
(NEWID(), 'Prostamol un'),
(NEWID(), 'Doxa'),
(NEWID(), 'Sumamigre'),
(NEWID(), 'Latanoprostu'),
(NEWID(), 'Sonoxe'),
(NEWID(), 'Rupatadini fumara'),
(NEWID(), 'Luceta'),
(NEWID(), 'Eurican DAPP'),
(NEWID(), 'Nebivololi hydrochloridu'),
(NEWID(), 'Flustad MA'),
(NEWID(), 'Palbociclibum'),
(NEWID(), 'Anagrelidum'),
(NEWID(), 'Teeni'),
(NEWID(), 'Paromomycin'),
(NEWID(), 'Codeinum'),
(NEWID(), 'Methoxyfluranum'),
(NEWID(), 'Cyanocobalaminum'),
(NEWID(), 'Atracurium'),
(NEWID(), 'Menotropinum (FSH i LH)'),
(NEWID(), 'Ixazomibum'),
(NEWID(), 'Etelcalcetidum'),
(NEWID(), 'Acidum obeticholicum'),
(NEWID(), 'Folitropinum delta'),
(NEWID(), 'Levomine min'),
(NEWID(), 'Tyletaminum'),
(NEWID(), 'Zolazepamum'),
(NEWID(), 'Halofuginone ( as lactate salt)'),
(NEWID(), 'Calcibe'),
(NEWID(), 'Dexamethasoni natrii phospha'),
(NEWID(), 'Lornoxicamum'),
(NEWID(), 'Tenofovirum disoproxilum fumaras'),
(NEWID(), 'Colime'),
(NEWID(), 'Envil kata'),
(NEWID(), 'Alectinibum'),
(NEWID(), 'Bezlotoxumabum'),
(NEWID(), 'Lonoctocog alfa'),
(NEWID(), 'Insulinum glarginum'),
(NEWID(), 'Furaginum Tev'),
(NEWID(), 'Polverti'),
(NEWID(), 'Miconazolum'),
(NEWID(), 'Atywi'),
(NEWID(), 'Physiotens'),
(NEWID(), 'Sylibi mariani fructus extractum siccum'),
(NEWID(), 'triamcinolu acetonid'),
(NEWID(), 'Acepromazinum'),
(NEWID(), 'Tanaceti parthenii herba'),
(NEWID(), 'Tolbasadi'),
(NEWID(), 'Tolterodinum'),
(NEWID(), 'Anagrelid Nordi'),
(NEWID(), 'Travoge'),
(NEWID(), 'Maxicorta'),
(NEWID(), 'Gliquidonum'),
(NEWID(), 'Myw'),
(NEWID(), 'Ceftobiprol'),
(NEWID(), 'Cyclopentolati hydrochloridum'),
(NEWID(), 'Dermipre'),
(NEWID(), 'Pembrolizumabum'),
(NEWID(), 'Baricitinibum'),
(NEWID(), 'Tofacitinibi citras'),
(NEWID(), 'Spamila'),
(NEWID(), 'Calcipotriolum'),
(NEWID(), 'Deltamethrinum'),
(NEWID(), 'Amgevit'),
(NEWID(), 'Adalimumabum'),
(NEWID(), 'Miglustatum'),
(NEWID(), 'Cefaleksyna (jako cefaleksyna jednowodna) '),
(NEWID(), 'Żelazo (III) (jako gleptoferron)'),
(NEWID(), 'Cefquinom'),
(NEWID(), 'Enterol'),
(NEWID(), 'Humir'),
(NEWID(), 'Neurovi'),
(NEWID(), 'Sortis'),
(NEWID(), 'Vihum'),
(NEWID(), 'Chenodeoxycholic acid Leadian'),
(NEWID(), 'Naproxen Genopti'),
(NEWID(), 'Mercaptamini hydrochloridum'),
(NEWID(), 'Nolipre'),
(NEWID(), 'Opicaponum'),
(NEWID(), 'Agomelatyna'),
(NEWID(), 'Carprodyl Quadr'),
(NEWID(), 'Chlordiazepoxidum'),
(NEWID(), 'Metamizole Kab'),
(NEWID(), 'Pirfenidonum'),
(NEWID(), 'Pergoveri'),
(NEWID(), 'Dasatinibum'),
(NEWID(), 'Rotea'),
(NEWID(), 'Tadalafil Lill'),
(NEWID(), 'Ilari'),
(NEWID(), 'Apo-Zolpi'),
(NEWID(), 'Esomeprazolum natricum'),
(NEWID(), 'Colistinum'),
(NEWID(), 'Cosopt PF Mult'),
(NEWID(), 'cholekalcyferol'),
(NEWID(), 'Baclofenum'),
(NEWID(), 'Anagrelidi hydrochloridum monohydricu'),
(NEWID(), 'Tiotropium'),
(NEWID(), 'Paliperidonum'),
(NEWID(), 'Sarilumabum'),
(NEWID(), 'Ribociclibi succinas'),
(NEWID(), 'Cariprazine'),
(NEWID(), 'Lenalidomide Sando'),
(NEWID(), 'Lenalidomidum'),
(NEWID(), 'Nusinersenum natricum'),
(NEWID(), 'Sphero'),
(NEWID(), 'Pentozanu wielosiarczan sodowy'),
(NEWID(), 'Refixi'),
(NEWID(), 'Nonacogum beta pegylateum'),
(NEWID(), 'Febuxostatum'),
(NEWID(), 'Cenegerminum'),
(NEWID(), 'Dexmedetomidine Myla'),
(NEWID(), 'inotuzumabum ozogamicini'),
(NEWID(), 'Voltaren Emulgel'),
(NEWID(), 'Sedam'),
(NEWID(), 'Dupilumabum'),
(NEWID(), 'Rydap'),
(NEWID(), 'Norgestimatum'),
(NEWID(), 'Cavinton Fort'),
(NEWID(), 'Amiodaron hamel'),
(NEWID(), 'Levomine mid'),
(NEWID(), 'Cladribinum'),
(NEWID(), 'Flumetrinum'),
(NEWID(), 'Levothyroxine sodium'),
(NEWID(), 'Midazolamum'),
(NEWID(), 'Pelargonii radicis extractum siccum'),
(NEWID(), 'Plantaginis lanceolatae extractum'),
(NEWID(), 'Erlotinibi hydrochloridum'),
(NEWID(), 'Parlode'),
(NEWID(), 'Afrin ND Mento'),
(NEWID(), 'Preat'),
(NEWID(), 'Phenylbutazonum '),
(NEWID(), 'Dekta'),
(NEWID(), 'Ibunid dla dzieci Fort'),
(NEWID(), 'Symtuz'),
(NEWID(), 'Fosfomycin Sando'),
(NEWID(), 'Atezolizumabum'),
(NEWID(), 'Tafluprostu'),
(NEWID(), 'Co-Valsaco'),
(NEWID(), 'Amanti'),
(NEWID(), 'Geibrox o smaku Mięt'),
(NEWID(), 'Enoxaparinum natricu'),
(NEWID(), 'Doxycyclini hyclas '),
(NEWID(), 'Plenix L'),
(NEWID(), 'S-Methoprenu'),
(NEWID(), 'Ulipristali acetas'),
(NEWID(), 'Cerliponasum alfa'),
(NEWID(), 'Memorio'),
(NEWID(), 'Orion Corporatio'),
(NEWID(), 'Cytosa'),
(NEWID(), 'Tasign'),
(NEWID(), 'Vinorelbine Zentiv'),
(NEWID(), 'Rifamycinum'),
(NEWID(), 'Octreotidum'),
(NEWID(), 'Lotilanerum'),
(NEWID(), 'Telotristati etipratun'),
(NEWID(), 'Mitoxantronum'),
(NEWID(), 'Pseudoephedrine Espef'),
(NEWID(), 'Amoksikla'),
(NEWID(), 'Aide'),
(NEWID(), 'Biotinum'),
(NEWID(), 'Fluimucil Fort'),
(NEWID(), 'Bilastinum'),
(NEWID(), 'Sirdalu'),
(NEWID(), 'Sorec'),
(NEWID(), 'Acidum tiocticum'),
(NEWID(), 'Argosulfa'),
(NEWID(), 'Norepinephrinu'),
(NEWID(), 'Temazepamum'),
(NEWID(), 'Ocrelizumabum'),
(NEWID(), 'Nitisinonum'),
(NEWID(), 'Alev'),
(NEWID(), 'Frimi'),
(NEWID(), 'Vesolig'),
(NEWID(), 'Ritonavir Myla'),
(NEWID(), 'Sumigra'),
(NEWID(), 'Diemon'),
(NEWID(), 'Orgametri'),
(NEWID(), 'Padeliporfinum'),
(NEWID(), 'Prevymi'),
(NEWID(), 'Letermovirum'),
(NEWID(), 'Bevacizumabum')

insert into ActiveSubstances
values(NEWID(), 'Rurioctocogum alfa pegolum'),
(NEWID(), 'Oxycodone hydrochloride'),
(NEWID(), 'Ibum Forte Pur'),
(NEWID(), 'Paracetamol Synopti'),
(NEWID(), 'Ticagrelorum'),
(NEWID(), 'Dextromethorphani hydrochloridum'),
(NEWID(), 'Acidum zoledronicum monohydricum'),
(NEWID(), 'Oxalic acid dihydrat'),
(NEWID(), 'Lagos'),
(NEWID(), 'Darunavir Krk'),
(NEWID(), 'Prasteronum'),
(NEWID(), 'Dexmedetomidini hydrochloridu'),
(NEWID(), 'Caspofunginum w postaci octanu:'),
(NEWID(), 'Detomidini hydrochloridum '),
(NEWID(), 'Doxybacti'),
(NEWID(), 'Innovax-ND-IB'),
(NEWID(), 'Burosumabum'),
(NEWID(), 'Melatoninum'),
(NEWID(), 'Calcii gluconas ad iniectabile'),
(NEWID(), 'Activyl'),
(NEWID(), 'Dymist'),
(NEWID(), 'Febuxostat Soline'),
(NEWID(), 'Efavirenz/Emtricitabine/Tenofovir disoproxil Krk'),
(NEWID(), 'Emicizumabum'),
(NEWID(), 'Grapriprant'),
(NEWID(), 'Velmanasum alfa'),
(NEWID(), 'Darvadstrocelum'),
(NEWID(), 'Silodosin Aurovita'),
(NEWID(), 'MiPet Easecto '),
(NEWID(), 'MiPet Easecto'),
(NEWID(), 'Ertugliflozinum'),
(NEWID(), 'Rilpivirini hydrochloridum'),
(NEWID(), 'Cortexonave'),
(NEWID(), 'Bismuthi subnitras ponderosum'),
(NEWID(), 'Gemtuzumabum ozogamicinum'),
(NEWID(), 'Flecainidi acetas'),
(NEWID(), 'Camili'),
(NEWID(), 'Carmustinum'),
(NEWID(), 'Peramivirum'),
(NEWID(), 'Formic acid'),
(NEWID(), 'Oxalic acid dihydrate '),
(NEWID(), 'LETIFEN'),
(NEWID(), 'Benzylpenicillinum procainum monohydricum'),
(NEWID(), 'Febuxostatum hemihydricum'),
(NEWID(), 'Megalotect C'),
(NEWID(), 'Magnefar '),
(NEWID(), 'Magnesii citras'),
(NEWID(), 'Pyridoxini hydrochloridum'),
(NEWID(), 'Kanjint'),
(NEWID(), 'Stiepro'),
(NEWID(), 'Glibenclamide'),
(NEWID(), 'Pemetrexedum dinatricum hemipentahydricum'),
(NEWID(), 'Nove'),
(NEWID(), 'Xyzal'),
(NEWID(), 'Moxidectinum'),
(NEWID(), 'Otrivin Mentho'),
(NEWID(), 'Grecja 
 Polsk'),
(NEWID(), 'Amitrazum'),
(NEWID(), 'Inupri'),
(NEWID(), 'Levothyroxine Accor'),
(NEWID(), 'Herpe'),
(NEWID(), 'Butafosfanum'),
(NEWID(), 'Tiamulin hydrogen fumarate for veterinary use'),
(NEWID(), 'Ketospray Fort'),
(NEWID(), 'Flunixini megluminum '),
(NEWID(), 'Telmize'),
(NEWID(), 'Contri'),
(NEWID(), 'Eprinomectinum'),
(NEWID(), 'Spryce'),
(NEWID(), 'Hyrimo'),
(NEWID(), 'Ciloze'),
(NEWID(), 'Levomethadone Hydrochloride Molten'),
(NEWID(), 'Candesartanum cilexetilu'),
(NEWID(), 'Amlodipinu'),
(NEWID(), 'Magnesii sulfas heptahydricus'),
(NEWID(), 'Betula Verrucosa'),
(NEWID(), 'Tenaxu'),
(NEWID(), 'Metreleptinum'),
(NEWID(), 'Manti Extr'),
(NEWID(), 'Halimato'),
(NEWID(), 'Erenumabum'),
(NEWID(), 'Methylprednisoloni acepona'),
(NEWID(), 'Eszopiclonum'),
(NEWID(), 'Nity'),
(NEWID(), 'Tisagenlecleucelum'),
(NEWID(), 'Vonicogum alfa'),
(NEWID(), 'Axicabtagenum ciloleucelum'),
(NEWID(), 'Vestronidasum alfa'),
(NEWID(), 'Patisiranum natricum'),
(NEWID(), 'Rigevido'),
(NEWID(), 'Alvent'),
(NEWID(), 'Acatar Care Kid'),
(NEWID(), 'Chlorhexidini dihydrochloridum'),
(NEWID(), 'Treosulfan'),
(NEWID(), 'Kigabe'),
(NEWID(), 'Encorafenibum'),
(NEWID(), 'Binimetinibum'),
(NEWID(), 'Tildrakizumabum'),
(NEWID(), 'Aspirin Pr'),
(NEWID(), 'Bixebr'),
(NEWID(), 'Pegfilgrastimum'),
(NEWID(), 'Durvalumabum'),
(NEWID(), 'Tela'),
(NEWID(), 'Cisatracuriu'),
(NEWID(), 'Eravacyclinum'),
(NEWID(), 'Dalfaz Un'),
(NEWID(), 'Biotylek Ma'),
(NEWID(), 'kabergolina'),
(NEWID(), 'Candepre'),
(NEWID(), 'Methylphenidati hydrochloridum'),
(NEWID(), 'Lorabe'),
(NEWID(), 'Trifarotenum'),
(NEWID(), 'Soledu'),
(NEWID(), 'Carbocisteinu'),
(NEWID(), 'Abemaciclibum'),
(NEWID(), 'Fosfomycinum trometamolum'),
(NEWID(), 'Vemonis Fem'),
(NEWID(), 'Karbi'),
(NEWID(), 'Semaglutidum'),
(NEWID(), 'Doret'),
(NEWID(), 'Primaco'),
(NEWID(), 'Sildenafil citrate'),
(NEWID(), 'Lecalpi'),
(NEWID(), 'Polopiryna Gardło Spra'),
(NEWID(), 'Efferalgan Codein'),
(NEWID(), 'Passiflorae herba extractum siccum'),
(NEWID(), 'Noradrenaline Aguettan'),
(NEWID(), 'Coxite'),
(NEWID(), 'Rolpryna S'),
(NEWID(), 'Erdosteinum'),
(NEWID(), 'Anidulafungin Myla'),
(NEWID(), 'Treprostinil Zentiv'),
(NEWID(), 'Prestarium'),
(NEWID(), 'Tantum Verd'),
(NEWID(), 'Dutamsol Mon'),
(NEWID(), 'Micafunginum natricum'),
(NEWID(), 'Ossmi'),
(NEWID(), 'Cypr  
 Polsk'),
(NEWID(), 'Metamizol Krk'),
(NEWID(), 'Oseltamiwiru fosforan'),
(NEWID(), 'Azacitidinum'),
(NEWID(), 'Vizimpr'),
(NEWID(), 'Dacomitinibum'),
(NEWID(), 'Codeini phosphas hemihydricus'),
(NEWID(), 'Fenylefryny chlorowodorek'),
(NEWID(), 'Selamectinum'),
(NEWID(), 'Apramycinum'),
(NEWID(), 'Regulo'),
(NEWID(), 'Jiv'),
(NEWID(), 'Doravirinum'),
(NEWID(), 'Romazi'),
(NEWID(), 'Enzalutamidum'),
(NEWID(), 'Mogamulizumabum'),
(NEWID(), 'Lusutrombopagum'),
(NEWID(), 'Ropeginterferonum alfa'),
(NEWID(), 'Brigatinibum '),
(NEWID(), 'Naldemedinum'),
(NEWID(), 'Dionell'),
(NEWID(), 'Fremanezumabum'),
(NEWID(), 'Lorlatinibum'),
(NEWID(), 'Halofuginone'),
(NEWID(), 'Ampril'),
(NEWID(), 'Ludzki inhibitor alf'),
(NEWID(), 'Kyntheu'),
(NEWID(), 'Dexamethasone Krk'),
(NEWID(), 'Rubrac'),
(NEWID(), 'Nuwi'),
(NEWID(), 'Diclac'),
(NEWID(), 'Paclitaxelum'),
(NEWID(), 'Timololu'),
(NEWID(), 'Hydrokortyzon Hasc'),
(NEWID(), 'Fungizon'),
(NEWID(), 'Tantum Verde Fort'),
(NEWID(), 'Thinba'),
(NEWID(), 'Karbocysteina'),
(NEWID(), 'Gynoxin Optim'),
(NEWID(), 'Tritace'),
(NEWID(), 'Differi'),
(NEWID(), 'Cinacalcet Aurovita'),
(NEWID(), 'Traumeel LT ad us. vet'),
(NEWID(), 'Loteprednolu etabonian'),
(NEWID(), 'Sotagliflozinum'),
(NEWID(), 'Andexanetum alfa'),
(NEWID(), 'Sitagliptin hydrochloride monohydrate'),
(NEWID(), 'Vaccinum Variolae (vivum) nie mniej niż'),
(NEWID(), 'Arnicae tinctura'),
(NEWID(), 'Alphafloroso'),
(NEWID(), 'Dialginu'),
(NEWID(), 'Herzum'),
(NEWID(), 'Furaginum Hasc'),
(NEWID(), 'Triseno'),
(NEWID(), 'Palynzi'),
(NEWID(), 'Pegvaliasum'),
(NEWID(), 'Sorafenibum'),
(NEWID(), 'Sorafenibi Tosilas'),
(NEWID(), 'Metforminum'),
(NEWID(), 'Syldenafilu cytrynian'),
(NEWID(), 'Ambrisentanum'),
(NEWID(), 'Nivali'),
(NEWID(), 'wapnia węglan'),
(NEWID(), 'Cetraxal Plu'),
(NEWID(), 'Paromomycyna '),
(NEWID(), 'Ferrum III'),
(NEWID(), 'Felisecto Plus'),
(NEWID(), 'ReproCyc ParvoFLE'),
(NEWID(), 'Methotrexatum natricum'),
(NEWID(), 'Milbemycinum oximum '),
(NEWID(), 'Pemetrexed Sando'),
(NEWID(), 'Hedussin o smaku owocowy'),
(NEWID(), 'Rivaroxabanum'),
(NEWID(), 'Ketofli'),
(NEWID(), 'Entero'),
(NEWID(), 'Xrom'),
(NEWID(), 'Ultomiri'),
(NEWID(), 'Turoctocogum alfa pegylateum'),
(NEWID(), 'Telmisartan/hydrochlorothiazide EGI'),
(NEWID(), 'Talazoparibum'),
(NEWID(), 'Versican Plus Bb Ora'),
(NEWID(), 'Lesinell'),
(NEWID(), 'Asikreb'),
(NEWID(), 'Sunitinib malate'),
(NEWID(), 'Sunitynibu jabłaczan'),
(NEWID(), 'Ibuprom Rapi'),
(NEWID(), 'Fludeoxythymidinum '),
(NEWID(), 'Pitavastinum calicum'),
(NEWID(), 'Atracurium Kalcek'),
(NEWID(), 'Sildenafil Aurovita'),
(NEWID(), 'Tetryzolini hydrochloridum'),
(NEWID(), 'Fampridinum'),
(NEWID(), 'Qsiv'),
(NEWID(), 'Phentermini hydrochloridum'),
(NEWID(), 'Cefalonium'),
(NEWID(), 'Sitagliptin STAD'),
(NEWID(), 'Primulae extractum'),
(NEWID(), 'Thymus vulgaris'),
(NEWID(), 'Terlipressini acetas'),
(NEWID(), 'Alprage'),
(NEWID(), 'Hyoscini butylbromidum (Scopolamini butylbromidum)'),
(NEWID(), 'Sorbifer Durule'),
(NEWID(), 'Virgan'),
(NEWID(), 'Betahistine dihydrochloride Aurovita'),
(NEWID(), 'Thiogamm'),
(NEWID(), 'Xefo Rapi'),
(NEWID(), 'Peditrac'),
(NEWID(), 'Cefuroxime Hel'),
(NEWID(), 'Abirateroni acetas'),
(NEWID(), 'Diclofenacum diethylammonium'),
(NEWID(), 'Dexamethasoni phosphas'),
(NEWID(), 'Abirateron Arist'),
(NEWID(), 'Vardenafil hydrochloride trihydrate'),
(NEWID(), 'Rotico'),
(NEWID(), 'Larotrectinibum'),
(NEWID(), 'Aknemyci'),
(NEWID(), 'Abiraterone Richte'),
(NEWID(), 'Tamsige'),
(NEWID(), 'Tobramycinu'),
(NEWID(), 'Dexamethasonu'),
(NEWID(), 'Lamivudine Aurovita'),
(NEWID(), 'Addipho'),
(NEWID(), 'Natrii glycerophosphas'),
(NEWID(), 'Agni casti fructus extractum siccum'),
(NEWID(), 'Feiba N'),
(NEWID(), 'Zivafer'),
(NEWID(), 'Pyrantelum'),
(NEWID(), 'Apixabanum'),
(NEWID(), 'Atomoxetinum'),
(NEWID(), 'Lactulosum liquidum'),
(NEWID(), 'Vicks Sinex Aloes i Eukaliptu'),
(NEWID(), 'Tiaprida'),
(NEWID(), 'Firody'),
(NEWID(), 'Mirtazapinum (as hemihydrate)'),
(NEWID(), 'Metamizol-S'),
(NEWID(), 'NuvaRin'),
(NEWID(), 'Eml'),
(NEWID(), 'Apsasol Hido'),
(NEWID(), 'Netarsudili mesilas'),
(NEWID(), 'Noradrenaliny winian'),
(NEWID(), 'Romosozumabum'),
(NEWID(), 'Pergolidi mesilas'),
(NEWID(), 'Fostamatinibum'),
(NEWID(), 'Osilodrostatum'),
(NEWID(), 'Calcitriolum'),
(NEWID(), 'Frontpr'),
(NEWID(), 'Polatuzumabum vedotinum'),
(NEWID(), 'Pridinol mesylate'),
(NEWID(), 'Menthae piperitae aetheroleum'),
(NEWID(), 'Dulsevi'),
(NEWID(), 'Sulfapre'),
(NEWID(), 'Romifidini hydrochloridum'),
(NEWID(), 'Ryaltri'),
(NEWID(), 'Linagliptinum'),
(NEWID(), 'Saccharomyces boulardii CNCM I'),
(NEWID(), 'Helminthe'),
(NEWID(), 'Bisacodyl V'),
(NEWID(), 'Optiglobi'),
(NEWID(), 'Brolucizumabum'),
(NEWID(), 'Imikwimod'),
(NEWID(), 'Thiamazolum '),
(NEWID(), 'Igzely'),
(NEWID(), 'Fampridine Zentiv'),
(NEWID(), 'Dabigatranu eteksylan w postaci mezylanu'),
(NEWID(), 'Levosimendanum'),
(NEWID(), 'Vigamo'),
(NEWID(), 'Adalimumabu'),
(NEWID(), 'Darolutamidum'),
(NEWID(), 'Sunitinib Krk'),
(NEWID(), 'Tramadol hydrochlorid'),
(NEWID(), 'Paracetamol Accor'),
(NEWID(), 'Pemetrexed Fresenius Kab'),
(NEWID(), 'Nystatin TZ'),
(NEWID(), 'Crisaborolum'),
(NEWID(), 'Rywastygmina'),
(NEWID(), 'Tapentadolu maleinian półwodny'),
(NEWID(), 'Solriamfetolum'),
(NEWID(), 'Tigilanol tiglate'),
(NEWID(), 'Isatuximabum'),
(NEWID(), 'Karbicomb'),
(NEWID(), 'Bismuthi subgallas'),
(NEWID(), 'Paliperydonu palmitynian'),
(NEWID(), 'Betaserc OD'),
(NEWID(), 'Tulathromycinum'),
(NEWID(), 'Prevendo'),
(NEWID(), 'Apomorphini hydrochloridum hemihydricum'),
(NEWID(), 'Fesoterodine fumarate Arist'),
(NEWID(), 'Fesoterodini fumaras'),
(NEWID(), 'Azaperonum'),
(NEWID(), 'Imidocarbi dipropionas'),
(NEWID(), 'Tulip Comb'),
(NEWID(), 'Atorvastatin calcium trihydrate'),
(NEWID(), 'Streptokinasum'),
(NEWID(), 'Streptodornasum'),
(NEWID(), 'Clotidal MA'),
(NEWID(), 'Norditropin NordiFle'),
(NEWID(), 'Metrocar'),
(NEWID(), 'Bilafle'),
(NEWID(), 'metyloprednizolonu octan'),
(NEWID(), 'Prednisoloni pivalas'),
(NEWID(), 'Propodin'),
(NEWID(), 'Prestilo'),
(NEWID(), 'N'),
(NEWID(), 'Toksyna botulinowa typu A'),
(NEWID(), 'Oxybutynin Medic'),
(NEWID(), 'Metoklopramidu chlorowodorek jednowodny'),
(NEWID(), 'Remdesivirum'),
(NEWID(), 'Icatibanti acetas'),
(NEWID(), 'Icatibantum'),
(NEWID(), 'Oftaqui'),
(NEWID(), 'Chlortalidon'),
(NEWID(), 'Hydroxychloroquini sulphas'),
(NEWID(), 'Uldiula'),
(NEWID(), 'Dabigatranum etexilatum'),
(NEWID(), 'Sitagliptini hydrochloridum monohydricum'),
(NEWID(), 'Fentanyli citras'),
(NEWID(), 'Rozlytre'),
(NEWID(), 'Entrectinibum'),
(NEWID(), 'Alpelisibum'),
(NEWID(), 'Pretomanidum'),
(NEWID(), 'Onasemnogenum abeparvovecum'),
(NEWID(), 'Glasdegibum'),
(NEWID(), 'Aybinti'),
(NEWID(), 'Levosert Eas'),
(NEWID(), 'Ioflupane '),
(NEWID(), 'Netilmicini sulfas'),
(NEWID(), 'Tetracosactidum'),
(NEWID(), 'Rosucar'),
(NEWID(), 'Oxtra D'),
(NEWID(), 'Cevac MD Rispen'),
(NEWID(), 'Uromitexa'),
(NEWID(), 'Sympagesi'),
(NEWID(), 'Chlorhexidini digluconatis solutio'),
(NEWID(), 'Halofuginoni lactas'),
(NEWID(), 'Cabotegravirum'),
(NEWID(), 'Musteligen '),
(NEWID(), 'Filgotinibum'),
(NEWID(), 'Imlifidasum'),
(NEWID(), 'Indakaterol'),
(NEWID(), 'Bupivacainum'),
(NEWID(), 'Lyumje'),
(NEWID(), 'Vedolizumabum'),
(NEWID(), 'Afloder'),
(NEWID(), 'Ledipasvirum'),
(NEWID(), 'Teicoplanin AptaPharm'),
(NEWID(), 'Bortezomib'),
(NEWID(), 'Midazolamu maleinian'),
(NEWID(), 'Sugammadexum natricum'),
(NEWID(), 'Macrosy'),
(NEWID(), 'Primope'),
(NEWID(), 'Aurex'),
(NEWID(), 'Rukobi'),
(NEWID(), 'Abirateronu octan'),
(NEWID(), 'Primun Bronchitis '),
(NEWID(), 'XABOPLA'),
(NEWID(), 'Pazopanibi hydrochloridum'),
(NEWID(), 'Walsartan'),
(NEWID(), 'Obiltoxaximab SF'),
(NEWID(), 'Oxlum'),
(NEWID(), 'Dobutamine hydrochloride'),
(NEWID(), 'Bedinvetmab'),
(NEWID(), 'Ranolazinum'),
(NEWID(), 'Levosimendan Kalcek'),
(NEWID(), 'Bendamustini hydrochloridum monohydricum'),
(NEWID(), 'Fingolimodi hydrochloridum'),
(NEWID(), 'Sugammadeks sodowy'),
(NEWID(), 'Baloxaviri marboxilum'),
(NEWID(), 'Nobivac DP PLU'),
(NEWID(), 'Dulaglutidum'),
(NEWID(), 'Frisium'),
(NEWID(), 'Vectormune FP IL'),
(NEWID(), 'Albumini humani solutio'),
(NEWID(), 'Netarsudilum'),
(NEWID(), 'Tagraxofuspum'),
(NEWID(), 'Trastuzumabum deruxtecanum'),
(NEWID(), 'Deferoxamini mesilas'),
(NEWID(), 'Nebilet HC'),
(NEWID(), 'Vaxzevri'),
(NEWID(), 'Atara'),
(NEWID(), 'AirFluSal Forspir'),
(NEWID(), 'Wellbutrin X'),
(NEWID(), 'Blisse'),
(NEWID(), 'Betalo'),
(NEWID(), 'Selpercatinibum'),
(NEWID(), 'Tucatinibum'),
(NEWID(), 'Lenalidomide Fresenius Kab'),
(NEWID(), 'Glucagon hydrochloride'),
(NEWID(), 'Moxetumomabum pasudotoxum'),
(NEWID(), 'Calcii lactogluconas'),
(NEWID(), 'Pirfenidon Stad'),
(NEWID(), 'Tirbanibulinum'),
(NEWID(), 'Fluoroethyl-L-tyrosinum '),
(NEWID(), 'Levomethadoni hydrochloridum'),
(NEWID(), 'Suxibuzonum'),
(NEWID(), 'Dopegy'),
(NEWID(), 'Depakin'),
(NEWID(), 'Arnica montana '),
(NEWID(), 'Risdiplamum'),
(NEWID(), 'Selinexorum'),
(NEWID(), 'Perindopril'),
(NEWID(), 'Tapentadolu winian'),
(NEWID(), 'Rosuvastatin calcium'),
(NEWID(), 'Trilostanu'),
(NEWID(), 'Heksamidyna'),
(NEWID(), 'Cenobamate'),
(NEWID(), 'Ofatumumabum'),
(NEWID(), 'Fluticasone Propionate'),
(NEWID(), 'Viganto'),
(NEWID(), 'DIUVE'),
(NEWID(), 'Ketosteri'),
(NEWID(), 'Teze'),
(NEWID(), 'Sudafed XyloSpray dla dziec'),
(NEWID(), 'Bismuthi subnitras'),
(NEWID(), 'Sertaconazoli nitras'),
(NEWID(), 'Leflunomide Aurovita'),
(NEWID(), 'Convule'),
(NEWID(), 'Olej etiodowany'),
(NEWID(), 'Pantoprazol sodowy półtorawodny'),
(NEWID(), 'Credelio Plu'),
(NEWID(), 'Frunevetmab'),
(NEWID(), 'Sunitinibi maleas'),
(NEWID(), 'Meldonium dihydratum'),
(NEWID(), 'Scopolamine butylbromide Kalcek'),
(NEWID(), 'Esciti'),
(NEWID(), 'Huvamo'),
(NEWID(), 'Amlodypiny bezylan'),
(NEWID(), 'Ganirelix acetate'),
(NEWID(), 'Estetrolum'),
(NEWID(), 'Surricox'),
(NEWID(), 'Hydroksychlorochina'),
(NEWID(), 'Lapatynibu ditozylan jednowodny'),
(NEWID(), 'Insisto'),
(NEWID(), 'Aryfreni'),
(NEWID(), 'Pentohexal'),
(NEWID(), 'Satralizumabum'),
(NEWID(), 'Dorax'),
(NEWID(), 'Roxadustatum'),
(NEWID(), 'Bromazepam'),
(NEWID(), 'kwas acetylosalicylowy'),
(NEWID(), 'Evinacumabum'),
(NEWID(), 'Selumetinibum'),
(NEWID(), 'Kalii clavulanas'),
(NEWID(), 'Abiraterone acetate'),
(NEWID(), 'Tralokinumabum'),
(NEWID(), 'Berotralstatum'),
(NEWID(), 'Duvelisibum'),
(NEWID(), 'Metoclopramide hydrochloride'),
(NEWID(), 'Pirami'),
(NEWID(), 'Kelev'),
(NEWID(), 'Dimethylis fumaras'),
(NEWID(), 'Vivace'),
(NEWID(), 'Cordaron'),
(NEWID(), 'Omeprazol sodowy'),
(NEWID(), 'ABILIU'),
(NEWID(), 'Solacuta'),
(NEWID(), 'Karbidopa'),
(NEWID(), 'Oxaliplatinum'),
(NEWID(), 'Sulfadiazinum'),
(NEWID(), 'Daryfenacyny bromowodorek'),
(NEWID(), 'Bosentanum monohydricum'),
(NEWID(), 'Citalopram BIJO'),
(NEWID(), 'Enflicoxib'),
(NEWID(), 'Naltrexoni hydrochloridum'),
(NEWID(), 'vericiguatum'),
(NEWID(), 'Odevixibatum'),
(NEWID(), 'Fingolimod'),
(NEWID(), 'Zaldia'),
(NEWID(), 'Aregal'),
(NEWID(), 'Flubendazolum'),
(NEWID(), 'Bimekizumabum'),
(NEWID(), 'Vosoritidum'),
(NEWID(), 'FATROVAX RH'),
(NEWID(), 'Dexak'),
(NEWID(), 'Hypnomidat'),
(NEWID(), 'Erythromycini cyclocarbonas'),
(NEWID(), 'Calcii lactoglucona'),
(NEWID(), 'Calcii carbona'),
(NEWID(), 'Wenlafaksyny chlorowodorek'),
(NEWID(), 'Firocoxibum'),
(NEWID(), 'Sumatryptanu bursztynian'),
(NEWID(), 'Piperacilli'),
(NEWID(), 'Tazobactam Kalcek'),
(NEWID(), 'Protamine sulfate'),
(NEWID(), 'Emla Plaste'),
(NEWID(), 'Pentobarbitalum natricum'),
(NEWID(), 'Cloxacillinum benzathinum'),
(NEWID(), 'Bortezomib Fresenius Kab'),
(NEWID(), 'Escytalopramu szczawian'),
(NEWID(), 'Apovomi'),
(NEWID(), 'Sugammadex Redd'),
(NEWID(), 'Sildenafil Biodemad'),
(NEWID(), 'Sacituzumabum govitecanum'),
(NEWID(), 'Nolpaza'),
(NEWID(), 'Paromomycinum'),
(NEWID(), 'Nalte'),
(NEWID(), 'Abiraterone Accor'),
(NEWID(), 'Solia'),
(NEWID(), 'ApoMigr'),
(NEWID(), 'Dopsolvo'),
(NEWID(), 'Pulmicor'),
(NEWID(), 'NVX-Co'),
(NEWID(), 'Diroximelis fumaras'),
(NEWID(), 'Somapacitanum'),
(NEWID(), 'Anifrolumabum'),
(NEWID(), 'Ravulizumabum'),
(NEWID(), 'Sotorasibum'),
(NEWID(), 'Indocyanine green'),
(NEWID(), 'Vomend ve'),
(NEWID(), 'Metrocloprimidi hydrochloridum monohydricum'),
(NEWID(), 'Lactulose-MI'),
(NEWID(), 'Acar'),
(NEWID(), 'Lipanthyl NT'),
(NEWID(), 'Acidum formicum'),
(NEWID(), 'Artesunatum'),
(NEWID(), 'Abrocitinibum'),
(NEWID(), 'Latroxi'),
(NEWID(), 'Phytomenadionum'),
(NEWID(), 'Alvesco'),
(NEWID(), 'Nasometi'),
(NEWID(), 'Lorazepam'),
(NEWID(), 'Sytagliptyny chlorwodorek jednowodny'),
(NEWID(), 'Nirmatrelvirum'),
(NEWID(), 'Produkt złożon'),
(NEWID(), 'Liberell'),
(NEWID(), 'Nolpaza contro'),
(NEWID(), 'Piramil'),
(NEWID(), 'Akynze'),
(NEWID(), 'Sumame'),
(NEWID(), 'Finerenonum'),
(NEWID(), 'Metformina'),
(NEWID(), 'Metforminy chlorowodorek'),
(NEWID(), 'Leflunomide Orio'),
(NEWID(), 'Somatrogonum'),
(NEWID(), 'Teriparatide'),
(NEWID(), 'Tixagevimabum'),
(NEWID(), 'Cilgavimabum'),
(NEWID(), 'Atorvo'),
(NEWID(), 'Kaltetan fort'),
(NEWID(), 'Dexamethasoni Natrii phosphas'),
(NEWID(), 'Tepotynib'),
(NEWID(), 'Bactri'),
(NEWID(), 'Clobe'),
(NEWID(), 'Egolanz'),
(NEWID(), 'Abiraterone Arit'),
(NEWID(), 'Metizo'),
(NEWID(), 'Semaglutide'),
(NEWID(), 'Glucarpidasum'),
(NEWID(), 'Apexxna'),
(NEWID(), 'Ephedrini hydrochloridum'),
(NEWID(), 'Opicapone'),
(NEWID(), 'Dasatinib Accor'),
(NEWID(), 'Dasatinib Accordpharm'),
(NEWID(), 'Baloxavir marboxil'),
(NEWID(), 'Broncho-Vaxo'),
(NEWID(), 'Truvelog Mix'),
(NEWID(), 'Cefalexinum benzathinum'),
(NEWID(), 'NO-SPA Fort'),
(NEWID(), 'Enfortumabum vedotini'),
(NEWID(), 'Nimotop '),
(NEWID(), 'Aspiri'),
(NEWID(), 'Naloxonum Hydrochloricum WZ'),
(NEWID(), 'Alprami'),
(NEWID(), 'Bioestrovet Swin'),
(NEWID(), 'Mosunetuzumabum'),
(NEWID(), 'betaine anhydrous'),
(NEWID(), 'Relugolixum'),
(NEWID(), 'Jodek potasu SER'),
(NEWID(), 'Albumina osocza ludzkiego w postaci nanokoloidu'),
(NEWID(), 'Diaprel M'),
(NEWID(), 'Capmatinibum'),
(NEWID(), 'Pirfenidone'),
(NEWID(), 'Olipudase alfa'),
(NEWID(), 'Midazolamu chlorowodorek'),
(NEWID(), 'Buserelinum'),
(NEWID(), 'Lexapr'),
(NEWID(), 'Lonafarnibum'),
(NEWID(), 'Dupixen'),
(NEWID(), 'Hydrocortisone aceponate'),
(NEWID(), 'Indigotinum'),
(NEWID(), 'Farycymab'),
(NEWID(), 'Dexa'),
(NEWID(), 'Tezspir'),
(NEWID(), 'Ximluc'),
(NEWID(), 'Miren'),
(NEWID(), 'Asciminibum'),
(NEWID(), 'Nexviadym'),
(NEWID(), 'Melphalani flufenamidum'),
(NEWID(), 'Acepromazini maleas'),
(NEWID(), 'Lenacapavir'),
(NEWID(), 'Ranibizumab'),
(NEWID(), 'Talidomid'),
(NEWID(), 'Vutrisiranum'),
(NEWID(), 'Tirzepatydum'),
(NEWID(), 'Xanax S'),
(NEWID(), 'Nolici'),
(NEWID(), 'Progesterone Besin'),
(NEWID(), 'Voltaren MA'),
(NEWID(), 'VidPrevtyn Bet'),
(NEWID(), 'Locoid Lipocrea'),
(NEWID(), 'Lotilaner Elanco'),
(NEWID(), 'Asubtel'),
(NEWID(), 'Sutimlimabum'),
(NEWID(), 'Nirsevimabum'),
(NEWID(), 'Teryflunomid'),
(NEWID(), 'Gozetotyd'),
(NEWID(), 'Biopronil spot-o'),
(NEWID(), 'Lasmiditanum'),
(NEWID(), 'Travocor'),
(NEWID(), 'Mycapss'),
(NEWID(), 'Cephapirinum benzathinum'),
(NEWID(), 'Targoci'),
(NEWID(), 'Aklie'),
(NEWID(), 'Huvexxi'),
(NEWID(), 'Cardisa'),
(NEWID(), 'Loncastuximabum tesirini'),
(NEWID(), 'Pleryksafor'),
(NEWID(), 'Abaloparatidum'),
(NEWID(), 'Pyrukyn'),
(NEWID(), 'Mitapivati sulfas'),
(NEWID(), 'Delamanidum'),
(NEWID(), 'Almotriptanum'),
(NEWID(), 'Cortoti'),
(NEWID(), 'Etranacogenum dezaparvovecum'),
(NEWID(), 'Alcain'),
(NEWID(), 'Fevari'),
(NEWID(), 'Acalabrutinibum'),
(NEWID(), 'Tolwaptan')