insert into ActiveSubstances 
values(NEWID(), 'Naproxenum natricum'),
(NEWID(), 'Amlodipini besilas'),
(NEWID(), 'Ciprofloxacinum'),
(NEWID(), 'Irbesartanum'),
(NEWID(), 'Amphotericinum B'),
(NEWID(), 'Natrii hydroxybutyras'),
(NEWID(), 'Roxithromycinum'),
(NEWID(), 'Rivastigminum'),
(NEWID(), 'Acidum ursodeoxycholicum'),
(NEWID(), 'Repaglinidum'),
(NEWID(), 'Neomycini sulfas'),
(NEWID(), 'Articaini hydrochloridum'),
(NEWID(), 'Adrenalinum'),
(NEWID(), 'Atorvastatinum calcicum'),
(NEWID(), 'Tramadoli hydrochloridum'),
(NEWID(), 'Zopiclonum'),
(NEWID(), 'Alprazolamum'),
(NEWID(), 'Diclofenacum natricum'),
(NEWID(), 'Ticlopidini hydrochloridum'),
(NEWID(), 'Citalopramum'),
(NEWID(), 'Montelukastum'),
(NEWID(), 'Misoprostolum'),
(NEWID(), 'Factor VII coagulationis humanus'),
(NEWID(), 'Cetirizini dihydrochloridum'),
(NEWID(), 'Pefloxacini mesylas'),
(NEWID(), 'Acidum lacticum'),
(NEWID(), 'Acidum salicylicum'),
(NEWID(), 'Acetylcysteinum'),
(NEWID(), 'Acidum acetylsalicylicum'),
(NEWID(), 'Acidum acetylsalicylicum do'),
(NEWID(), 'Acidum ascorbicum'),
(NEWID(), 'Adenosinum'),
(NEWID(), 'Ambroxoli hydrochloridum'),
(NEWID(), 'Oxymetazolini hydrochloridum'),
(NEWID(), 'Pentoxifyllinum'),
(NEWID(), 'Biperideni lactas'),
(NEWID(), 'Biperideni hydrochloridum'),
(NEWID(), 'Erythromycinu'),
(NEWID(), 'Erythromycinum '),
(NEWID(), 'Benzoylis peroxydum'),
(NEWID(), 'Proxymetacaini hydrochloridum'),
(NEWID(), 'Kalii canrenoas'),
(NEWID(), 'Melphalanum'),
(NEWID(), 'Natalizumabum'),
(NEWID(), 'Dihydroxyaluminii natrii carbonas'),
(NEWID(), 'Cyproteroni acetas'),
(NEWID(), 'Phenylephrini hydrochloridum'),
(NEWID(), 'Amoxicillinum natricum'),
(NEWID(), 'Acidum clavulanicum'),
(NEWID(), 'Flucitosinum'),
(NEWID(), 'Magnesii subcarbonas'),
(NEWID(), 'Calcii carbonas'),
(NEWID(), 'Antithrombinum humanum III'),
(NEWID(), 'Carboplatinum'),
(NEWID(), 'Paracetamolum'),
(NEWID(), 'Sodu czteroboran'),
(NEWID(), 'Sulfogaiacolum'),
(NEWID(), 'Pipecuronii bromidum'),
(NEWID(), 'Chloroquini phosphas'),
(NEWID(), 'Sulfathiazolum argentum'),
(NEWID(), 'Esomeprazolum (esomeprazol magnezowy, amorficzny)'),
(NEWID(), 'Hydroxyzini hydrochloridum'),
(NEWID(), 'Atenololum'),
(NEWID(), 'Moclobemidum'),
(NEWID(), 'Sulfamethoxazolum'),
(NEWID(), 'Trimethoprimum'),
(NEWID(), 'Trimebutinum'),
(NEWID(), 'Beta-metylodigoksyna'),
(NEWID(), 'Ibuprofenum'),
(NEWID(), 'Enalaprili maleas'),
(NEWID(), 'Dexpanthenolum'),
(NEWID(), 'Povidonum iodinatum'),
(NEWID(), 'Polyvidonum iodinatum'),
(NEWID(), 'Betaxololi hydrochloridum'),
(NEWID(), 'Verapamili hydrochloridum'),
(NEWID(), 'Sotaloli hydrochloridum'),
(NEWID(), 'Fluoxetinum'),
(NEWID(), 'Białko surowicy ludzkiej'),
(NEWID(), 'Pranoprofenum'),
(NEWID(), 'Bromocriptini mesylas'),
(NEWID(), 'Riluzolum'),
(NEWID(), 'Hyoscini butylbromidum'),
(NEWID(), 'Phenylbutazonum'),
(NEWID(), 'Calcii pantothenas'),
(NEWID(), 'Sulfonianu polistyrenu sól wapniowa'),
(NEWID(), 'Tasonermin'),
(NEWID(), 'Carbo activatus'),
(NEWID(), 'Dexrazoxanum'),
(NEWID(), 'Doxazosini mesilas'),
(NEWID(), 'Doxazosinum'),
(NEWID(), 'Diclofenacum kalicum'),
(NEWID(), 'Pirenoxinum natricum'),
(NEWID(), 'Vinpocetinum'),
(NEWID(), 'Tacrolimus'),
(NEWID(), 'Amoxicillinum trihydricum'),
(NEWID(), 'Cefoperazonum'),
(NEWID(), 'Betamethasoni natrii phosphas'),
(NEWID(), 'Desloratadinum'),
(NEWID(), 'Pseudoephedrini sulfas'),
(NEWID(), 'Chlorquinaldolum'),
(NEWID(), 'Chlorprothixeni hydrochloridum'),
(NEWID(), 'Suxamethonii chloridum'),
(NEWID(), 'Hymecromonum'),
(NEWID(), 'Cholini salicylas'),
(NEWID(), 'Ciprofloxacini hydrochloridum'),
(NEWID(), 'Loratadinum'),
(NEWID(), 'Enoxaparinum natricum'),
(NEWID(), 'Clopamidum'),
(NEWID(), 'Zuclopenthixoli dihydrochloridu'),
(NEWID(), 'Zuclopenthixoli acetas'),
(NEWID(), 'Zuclopenthixoli decanoas'),
(NEWID(), 'Clomifeni citras'),
(NEWID(), 'Clotrimazolum'),
(NEWID(), 'Tianeptinum'),
(NEWID(), 'Mometasoni furoas'),
(NEWID(), 'Bisoprololi fumaras'),
(NEWID(), 'Podophyllotoxinum'),
(NEWID(), 'Pantoprazolum'),
(NEWID(), 'Acidum valproicum'),
(NEWID(), 'Amiodaroni hydrochloridum'),
(NEWID(), 'Nandroloni decanoas'),
(NEWID(), 'Fludrocortisoni acetas'),
(NEWID(), 'Losartanum kalicum'),
(NEWID(), 'Natrii cromoglicas'),
(NEWID(), 'Dinatrii cromoglicas'),
(NEWID(), 'Ganciclovirum'),
(NEWID(), 'Cytarabinum'),
(NEWID(), 'Prednisonum'),
(NEWID(), 'Ciclopirox olaminum'),
(NEWID(), 'Spironolactonum'),
(NEWID(), 'Clindamycini palmitas'),
(NEWID(), 'Clindamycini hydrochloridum'),
(NEWID(), 'Clindamycinum'),
(NEWID(), 'Clindamycini phosphas'),
(NEWID(), 'Tolterodini tartras'),
(NEWID(), 'Lamivudinum'),
(NEWID(), 'Triptorelinum'),
(NEWID(), 'Natrii valproas'),
(NEWID(), 'Desferoxamini mesilas'),
(NEWID(), 'Dexamethasonum'),
(NEWID(), 'Dexamethasoni natrii phosphas'),
(NEWID(), 'Ethinylestradiolum'),
(NEWID(), 'Fluconazolum'),
(NEWID(), 'Diltiazemi hydrochloridum'),
(NEWID(), 'Promethazini hydrochloridum'),
(NEWID(), 'Propofolum'),
(NEWID(), 'Betamethasoni dipropionas'),
(NEWID(), 'Magnesii valproas'),
(NEWID(), 'Levothyroxinum natricum'),
(NEWID(), 'Oxybutynini hydrochloridum'),
(NEWID(), 'Iprazochromum'),
(NEWID(), 'Dobutamini hydrochloridum'),
(NEWID(), 'Coffeinum'),
(NEWID(), 'Methyldopum'),
(NEWID(), 'Midazolami maleas'),
(NEWID(), 'Cefadroxilum'),
(NEWID(), 'Mebeverini hydrochloridum'),
(NEWID(), 'Urapidili hydrochloridum'),
(NEWID(), 'Olej z wątroby rekina'),
(NEWID(), 'Vancomycini hydrochloridum'),
(NEWID(), 'Paracetamolum '),
(NEWID(), 'Etilefrini hydrochloridum'),
(NEWID(), 'Isosorbidi mononitras'),
(NEWID(), 'Fluorouracilum'),
(NEWID(), 'Lidocainum'),
(NEWID(), 'Prilocainum'),
(NEWID(), 'Prednisolonum'),
(NEWID(), 'Tapentadolum'),
(NEWID(), 'Cyclophosphamidum'),
(NEWID(), 'Phenytoinum natricum'),
(NEWID(), 'symetykon '),
(NEWID(), 'Dimeticonum'),
(NEWID(), 'Estradiolum'),
(NEWID(), 'Acidum tranexamicum'),
(NEWID(), 'Piroxicamum'),
(NEWID(), 'Gestodenum'),
(NEWID(), 'Betainum anhydrousum'),
(NEWID(), 'Ferri hydroxidum dextranum'),
(NEWID(), 'Ferri hydroxidum saccharum'),
(NEWID(), 'Fluvoxamini maleas'),
(NEWID(), 'Flupentixoli decanoas'),
(NEWID(), 'Fluocinoloni acetonidum'),
(NEWID(), 'Fluorometholonum'),
(NEWID(), 'Fluoresceinum natricum'),
(NEWID(), 'Flutamidum'),
(NEWID(), 'Isofluranum'),
(NEWID(), 'Nadroparinum calcicum'),
(NEWID(), 'Furaginum '),
(NEWID(), 'Gentamicini sulfas'),
(NEWID(), 'Nilotinibum'),
(NEWID(), 'nilotinib'),
(NEWID(), 'Somatropinum'),
(NEWID(), 'Ginkgo bilobae extractum '),
(NEWID(), 'Cholini alfosceras'),
(NEWID(), 'Nicethamidum'),
(NEWID(), 'Glucosum'),
(NEWID(), 'Acarbosum'),
(NEWID(), 'Trandolaprilum'),
(NEWID(), 'Metronidazolum'),
(NEWID(), 'Midodrini hydrochloridum'),
(NEWID(), 'Econazoli nitras'),
(NEWID(), 'Panitumumabum'),
(NEWID(), 'Bencyclani fumaras'),
(NEWID(), 'Opipramoli dihydrochloridum'),
(NEWID(), 'Cetylpyridinii chloridum'),
(NEWID(), 'Clomethiazoli edisylas'),
(NEWID(), 'Ornithini aspartas'),
(NEWID(), 'Timonacicum'),
(NEWID(), 'Heparinum natricum'),
(NEWID(), 'Amoksycylina trójwodna'),
(NEWID(), 'Mucopolisaccharidum polisulphatum'),
(NEWID(), 'Ifosfamidum'),
(NEWID(), 'Insulinum lisprum injectio neutralis'),
(NEWID(), 'Natrii hyaluronas'),
(NEWID(), 'Hydrocortisonum'),
(NEWID(), 'Chlortalidonum'),
(NEWID(), 'Etomidatum'),
(NEWID(), 'Azathioprinum'),
(NEWID(), 'Amorolfini hydrochloridum'),
(NEWID(), 'Cilazaprilum'),
(NEWID(), 'Nifuroxazidum'),
(NEWID(), 'Insulinum humanum isophanum'),
(NEWID(), 'Drospirenonum'),
(NEWID(), 'Hyperici intractum'),
(NEWID(), 'Oleum sojae purificatum'),
(NEWID(), 'Pregabalinum'),
(NEWID(), 'Kalii iodidum'),
(NEWID(), 'Docetaxelum'),
(NEWID(), 'Kalii chloridum'),
(NEWID(), 'Hydroxycarbamidum'),
(NEWID(), 'Ketamini hydrochloridum'),
(NEWID(), 'Ketoprofenum'),
(NEWID(), 'Clarithromycinum'),
(NEWID(), 'Norethisteroni acetas'),
(NEWID(), 'Clozapinum'),
(NEWID(), 'Lincomycini hydrochloridum'),
(NEWID(), 'Pancreatinum'),
(NEWID(), 'Lactulosum'),
(NEWID(), 'Terbinafini hydrochloridum'),
(NEWID(), 'Thioguaninum'),
(NEWID(), 'Hydrocortisoni butyras'),
(NEWID(), 'Mianserini hydrochloridum'),
(NEWID(), 'Bromazepamum'),
(NEWID(), 'Lidocaini hydrochloridum'),
(NEWID(), 'Lincomycinum'),
(NEWID(), 'Afliberceptum'),
(NEWID(), 'Ciprofibratum'),
(NEWID(), 'Fenofibratum (zmikronizowany)'),
(NEWID(), 'Desogestrelum'),
(NEWID(), 'Cetuximabum'),
(NEWID(), 'Lithii carbonas'),
(NEWID(), 'Tibolonu'),
(NEWID(), 'Amorolfinum'),
(NEWID(), 'Flumetasoni pivalas'),
(NEWID(), 'Clioquinolum'),
(NEWID(), 'Benazeprili hydrochloridu'),
(NEWID(), 'Benazeprili hydrochloridum'),
(NEWID(), 'Minoxidilum'),
(NEWID(), 'Leuprorelini acetas'),
(NEWID(), 'Maprotilini hydrochloridum'),
(NEWID(), 'Nifuratelum'),
(NEWID(), 'Nystatinum'),
(NEWID(), 'Levodopum'),
(NEWID(), 'Benserazidi hydrochloridum'),
(NEWID(), 'Bupiwakainy chlorowodorek'),
(NEWID(), 'Epinefryny winian'),
(NEWID(), 'Bupivacaini hydrochloridum'),
(NEWID(), 'Gabapentinum'),
(NEWID(), 'Extractum propolis, ekstrahent- etanol'),
(NEWID(), 'Sevofluranum'),
(NEWID(), 'Methylprednisolonum'),
(NEWID(), 'Buspironi hydrochloridum'),
(NEWID(), 'Mepivacaini hydrochloridum'),
(NEWID(), 'Meropenemum trihydricum'),
(NEWID(), 'Indometacinum'),
(NEWID(), 'Thiamazolum'),
(NEWID(), 'Metoprololi tartras'),
(NEWID(), 'Methylprednisoloni natrii succinas'),
(NEWID(), 'Levonorgestrelum'),
(NEWID(), 'Allopurinolum'),
(NEWID(), 'Carbacholi chloridum'),
(NEWID(), 'Acidum zoledronicum'),
(NEWID(), 'Fosfomycinum'),
(NEWID(), 'Fosfomycinum '),
(NEWID(), 'Trometamolum '),
(NEWID(), 'mikonazol'),
(NEWID(), 'Mazipredoni hydrochloridum'),
(NEWID(), 'Bifonazolum'),
(NEWID(), 'Ureum'),
(NEWID(), 'Tolperisoni hydrochloridum'),
(NEWID(), 'Undecylenamidum'),
(NEWID(), 'Zinci undecylenas'),
(NEWID(), 'Busulfanum'),
(NEWID(), 'Ambenonii chloridum'),
(NEWID(), 'Carbidopum'),
(NEWID(), 'Vinorelbini tartras'),
(NEWID(), 'Acitretinum'),
(NEWID(), 'Phosphocreatinum natricum'),
(NEWID(), 'Carbamazepinum'),
(NEWID(), 'Nicotinum (w postaci kompleksu żywicy nikotynowej'),
(NEWID(), 'Nicergolinum'),
(NEWID(), 'Nimodipinum'),
(NEWID(), 'Nitrazepamum'),
(NEWID(), 'Nitrendipinum'),
(NEWID(), 'Galantamini hydrobromidum'),
(NEWID(), 'Ketoconazolum'),
(NEWID(), 'Norfloxacinum'),
(NEWID(), 'Tamoxifeni citras'),
(NEWID(), 'Piracetamum'),
(NEWID(), 'Quinagolidum'),
(NEWID(), 'Pridinoli hydrochloridum'),
(NEWID(), 'Iohexolum'),
(NEWID(), 'Gadodiamidum'),
(NEWID(), 'Lynestrenolum'),
(NEWID(), 'Omeprazolum'),
(NEWID(), 'Phenoxymethylpenicillinum kalicum'),
(NEWID(), 'Benzathini phenoxymethylpenicillinum'),
(NEWID(), 'Estriolum'),
(NEWID(), 'Oxazepamum'),
(NEWID(), 'Oxytocinum'),
(NEWID(), 'Nonoxinolum'),
(NEWID(), 'Mesalazinum'),
(NEWID(), 'Glyceroli trinitras'),
(NEWID(), 'Capsaicinum'),
(NEWID(), 'Ethosuximidum'),
(NEWID(), 'Triamcinoloni acetonidum'),
(NEWID(), 'Tigecyclinum'),
(NEWID(), 'Natamycinum'),
(NEWID(), 'Neomycinum'),
(NEWID(), 'Felodipinum'),
(NEWID(), 'Methoxypolyethylene glycolum-epoetinum beta'),
(NEWID(), 'Triamcinolonum'),
(NEWID(), 'Candesartanum cilexetili'),
(NEWID(), 'Sevelameri carbonas'),
(NEWID(), 'Gonadotrophinum chorionicum'),
(NEWID(), 'Dinoprostonum'),
(NEWID(), 'Denotivirum'),
(NEWID(), 'Tribenosidum'),
(NEWID(), 'Progesteronum'),
(NEWID(), 'Promazini hydrochloridum'),
(NEWID(), 'Finasteridum'),
(NEWID(), 'Sabalis serrulatae extractum'),
(NEWID(), 'Alprostadilum'),
(NEWID(), 'Propafenoni hydrochloridum'),
(NEWID(), 'Medroxyprogesteroni acetas'),
(NEWID(), 'Zinci oxidum'),
(NEWID(), 'Mentholum'),
(NEWID(), 'Propolis extractum'),
(NEWID(), 'Benzocainum'),
(NEWID(), 'Budesonidum'),
(NEWID(), 'Dornasum alfa'),
(NEWID(), 'Acidum thiocticum'),
(NEWID(), 'Ranitidini hydrochloridum'),
(NEWID(), 'Diazepamum'),
(NEWID(), 'Beta Aescinum'),
(NEWID(), 'Natrii polistyreni sulfonas'),
(NEWID(), 'Spiramycinum'),
(NEWID(), 'Azithromycinum'),
(NEWID(), 'Vigabatrinum'),
(NEWID(), 'Cetalkonii chloridum'),
(NEWID(), 'Ciclosporinum'),
(NEWID(), 'Octreotidi acetas'),
(NEWID(), 'Sennae foliolum'),
(NEWID(), 'Fluoxetini hydrochloridum'),
(NEWID(), 'Acenocoumarolum'),
(NEWID(), 'Acidum azelaicum'),
(NEWID(), 'Diosmectitum'),
(NEWID(), 'Ethanolum'),
(NEWID(), 'Alcohol isopropylicus'),
(NEWID(), 'Sucha masa bezbiałkowego dializatu z krwi cieląt'),
(NEWID(), 'Zolpidemi tartras'),
(NEWID(), 'Echinacaeae herbae recentis succus '),
(NEWID(), 'Farfarae succus'),
(NEWID(), 'Hyperici succus'),
(NEWID(), 'Taraxaci succus'),
(NEWID(), 'Sulfasalazinum w postaci granulatu z powidonem -'),
(NEWID(), 'Cytisinum'),
(NEWID(), 'Teicoplaninum'),
(NEWID(), 'Piperacillinum Natricum'),
(NEWID(), 'Tazobactamum natricum'),
(NEWID(), 'Thymostimulinum'),
(NEWID(), 'Theophyllinum'),
(NEWID(), 'Immunoglobulinum antilymphocytum (królicza)'),
(NEWID(), 'Timololi maleas'),
(NEWID(), 'Levomepromazini maleas'),
(NEWID(), 'Levomepromazinum'),
(NEWID(), 'Tobramycini sulfas'),
(NEWID(), 'Thiethylperazini dimaleas'),
(NEWID(), 'Atracurii besilas'),
(NEWID(), 'Kalii clorazepas'),
(NEWID(), 'Dikalii clorazepas'),
(NEWID(), 'Isoconazoli nitras'),
(NEWID(), 'Methotrexatum'),
(NEWID(), 'Dorzolamidi hydrochloridum'),
(NEWID(), 'Epinephrinum'),
(NEWID(), 'Distigmini bromidum'),
(NEWID(), 'Iopromidum'),
(NEWID(), 'Sultamycyllinum'),
(NEWID(), 'Testosteroni undecanoas'),
(NEWID(), 'Mesnum'),
(NEWID(), 'Cefovecin'),
(NEWID(), 'o-beta-hydroxyethylrutosidae'),
(NEWID(), 'Mebendazolum'),
(NEWID(), 'Tretinoinum'),
(NEWID(), 'Sulodexidum'),
(NEWID(), 'Cholecalciferolum'),
(NEWID(), 'Cholecalciferolum (proszek)'),
(NEWID(), 'Amantadini hydrochloridum'),
(NEWID(), 'Tromantadini hydrochloridum'),
(NEWID(), 'Thiamini hydrochloridum (vitaminum '),
(NEWID(), 'Duloxetinum'),
(NEWID(), 'Natrii iodidum'),
(NEWID(), 'Xylometazolini hydrochloridum'),
(NEWID(), 'Idarubicini hydrochloridum'),
(NEWID(), 'Sildenafilum'),
(NEWID(), 'tert-Butylamini perindoprilum'),
(NEWID(), 'Indapamidum'),
(NEWID(), 'Simvastatinum'),
(NEWID(), 'Ondansetroni hydrochloridum dihydricum'),
(NEWID(), 'Goserelini acetas'),
(NEWID(), 'Silodosinum'),
(NEWID(), 'Quinaprili hydrochloridum'),
(NEWID(), 'Methylprednisoloni aceponas'),
(NEWID(), 'Mycophenolas mofetil'),
(NEWID(), 'Carvedilolum'),
(NEWID(), 'Natrii fusidas'),
(NEWID(), 'Acidum fusidicum hemihydricum'),
(NEWID(), 'Telmisartanum'),
(NEWID(), 'Hydrochlorothiazidum'),
(NEWID(), 'Diflucortoloni valeras'),
(NEWID(), 'Tamsulosini hydrochloridum'),
(NEWID(), 'Morphini sulfas'),
(NEWID(), 'Natrii fluoridum'),
(NEWID(), 'Lansoprazolum'),
(NEWID(), 'Rilmenidinum'),
(NEWID(), 'Troxerutinum'),
(NEWID(), 'Tacalcitolum monohydricum'),
(NEWID(), 'Etofenamatum'),
(NEWID(), 'Benzyli nicotinas'),
(NEWID(), 'Indinaviri sulfas'),
(NEWID(), 'Pancuronii bromidum'),
(NEWID(), 'Olanzapinum'),
(NEWID(), 'Benserazidum'),
(NEWID(), 'Morphini hydrochloridum'),
(NEWID(), 'Donepezili hydrochloridum'),
(NEWID(), 'Irinotecani hydrochloridum'),
(NEWID(), 'Antithrombinum III'),
(NEWID(), 'Aseptinu'),
(NEWID(), 'Urticae radicis extractum siccum'),
(NEWID(), 'Doxycyclinum'),
(NEWID(), 'Sertralini hydrochloridum'),
(NEWID(), 'Pyridoxini hydrochloridum (Vitaminum '),
(NEWID(), 'Terazosini dihydricum hydrochloridum'),
(NEWID(), 'Imatinibum'),
(NEWID(), 'Azelastini hydrochloridum'),
(NEWID(), 'Venlafaxinum'),
(NEWID(), 'Beta Hydroxyethylrutosidum'),
(NEWID(), 'Levocetirizini dihydrochloridum'),
(NEWID(), 'Desmopressini acetas'),
(NEWID(), 'Zidovudinum'),
(NEWID(), 'Cefuroximum natricum'),
(NEWID(), 'Filgrastimum'),
(NEWID(), 'Dalteparinum natricum'),
(NEWID(), 'Codeini phosphas'),
(NEWID(), 'Acamprosatum'),
(NEWID(), 'Cefadroxilum monohydricum'),
(NEWID(), 'Atorvastatinum calcicum trihydricu'),
(NEWID(), 'Paraffinum liquidum'),
(NEWID(), 'Ondansetronum'),
(NEWID(), 'Amlodipini besilas '),
(NEWID(), 'Rocuronii bromidum'),
(NEWID(), 'Sennae angustifoliae fructus extractum siccum'),
(NEWID(), 'Glipizidum'),
(NEWID(), 'Calcitoninum salmonis'),
(NEWID(), 'Formoteroli fumaras'),
(NEWID(), 'Dextromethorphani hydrobromidum'),
(NEWID(), 'Clopidogrelum'),
(NEWID(), 'Aciclovirum natricum'),
(NEWID(), 'Selegilini hydrochloridum'),
(NEWID(), 'Somatostatinum'),
(NEWID(), 'Interferonum beta'),
(NEWID(), 'Moxonidinum'),
(NEWID(), 'Sildenafili citras'),
(NEWID(), 'Dinitrogenii oxidum >'),
(NEWID(), 'Alfuzosini hydrochloridum'),
(NEWID(), 'Latanoprostum'),
(NEWID(), 'Cisatracurii besilas'),
(NEWID(), 'Bezbiałkowy dializat z krwi cieląt'),
(NEWID(), 'Acemetacinum'),
(NEWID(), 'Rituximabum'),
(NEWID(), 'Lanreotidi acetas'),
(NEWID(), 'Entacaponum'),
(NEWID(), 'Naftifini hydrochloridum'),
(NEWID(), 'Candesartanum cilexetilum'),
(NEWID(), 'Enrofloxacinum'),
(NEWID(), 'Cefazolinum natricum'),
(NEWID(), 'Megestroli acetas'),
(NEWID(), 'Acidum mefenamicum'),
(NEWID(), 'Raloxifeni hydrochloridum'),
(NEWID(), 'Insulini injectio neutralis aspartum'),
(NEWID(), 'Remifentanili hydrochloridum'),
(NEWID(), 'Follitropinum alfa'),
(NEWID(), 'Efavirenzum'),
(NEWID(), 'Ferri proteinatosuccinas'),
(NEWID(), 'Propylthiouracilum'),
(NEWID(), 'Fosamprenavirum'),
(NEWID(), 'Albuminum humanum'),
(NEWID(), 'Milrinonum'),
(NEWID(), 'Doxorubicini hydrochloridum'),
(NEWID(), 'Fluorometholoni acetas'),
(NEWID(), 'Celecoxibum'),
(NEWID(), 'Sumatriptanum'),
(NEWID(), 'Pantoprazolum natricum sesquihydricum'),
(NEWID(), 'Fotemustinum'),
(NEWID(), 'Iodixanolum'),
(NEWID(), 'lewamizolu chlorowodorek'),
(NEWID(), 'Cabergolinum'),
(NEWID(), 'Lisinoprilum dihydricum'),
(NEWID(), 'Imiquimodum'),
(NEWID(), 'Topotecanum'),
(NEWID(), 'Triptorelini acetas'),
(NEWID(), 'Cetrorelixum'),
(NEWID(), 'Venlafaxini hydrochloridum'),
(NEWID(), 'Hexylresorcinolum'),
(NEWID(), 'Benzalkonii chloridum'),
(NEWID(), 'Captoprilum'),
(NEWID(), 'Abacaviri sulfas'),
(NEWID(), 'Carbocisteinum'),
(NEWID(), 'Carbocisteinum do'),
(NEWID(), 'Emedastini difumaras'),
(NEWID(), 'Cerebrolysinum'),
(NEWID(), 'Temozolomidum'),
(NEWID(), 'Palivizumabum'),
(NEWID(), 'Oxcarbazepinum'),
(NEWID(), 'Oxygeniu'),
(NEWID(), 'Moroctocogum alfa'),
(NEWID(), 'Fipronil'),
(NEWID(), 'Ofloxacinum'),
(NEWID(), 'Trimetazidini dihydrochloridum'),
(NEWID(), 'Amisulpridum'),
(NEWID(), 'Reboxetinum'),
(NEWID(), 'Adapalenum'),
(NEWID(), 'Dexibuprofenum'),
(NEWID(), 'Piribedilum'),
(NEWID(), 'Ranitidinum'),
(NEWID(), 'Tiapridum'),
(NEWID(), 'Atosibanum'),
(NEWID(), 'Insulina ludzka rekombinowana'),
(NEWID(), 'Trastuzumabum'),
(NEWID(), 'Benfothiaminum'),
(NEWID(), 'Harpagophyti extractum aq. Siccum'),
(NEWID(), 'Sulfasalazinum (w postaci mieszaniny z powidonem)'),
(NEWID(), 'Brimonidini tartras'),
(NEWID(), 'Pemetrexedum'),
(NEWID(), 'Clobetasoli propionas'),
(NEWID(), 'Eprosartanum'),
(NEWID(), 'Dydrogesteronum'),
(NEWID(), 'Brinzolamidum'),
(NEWID(), 'Epoetinum beta'),
(NEWID(), 'Natrii chloridum'),
(NEWID(), 'Montelukastum natricum'),
(NEWID(), 'Trimebutini maleas'),
(NEWID(), 'Insulinum aspartum'),
(NEWID(), 'Ganirelixi acetas'),
(NEWID(), 'Rutosidum trihydricum'),
(NEWID(), 'Nomegestroli acetas'),
(NEWID(), 'Alverini citras'),
(NEWID(), 'Simeticonum'),
(NEWID(), 'Degarelix'),
(NEWID(), 'Cinacalcetum'),
(NEWID(), 'Fluvastatinum'),
(NEWID(), 'Terazosinum'),
(NEWID(), 'Capecitabinum'),
(NEWID(), 'Sirolimusum'),
(NEWID(), 'Triptorelini pamoas'),
(NEWID(), 'Kalii clavulonas'),
(NEWID(), 'Mupirocinum'),
(NEWID(), 'Citaloprami hydrobromidum'),
(NEWID(), 'Follitropinum beta'),
(NEWID(), 'Desonidum'),
(NEWID(), 'Gadobutrolum'),
(NEWID(), 'Infliximabum'),
(NEWID(), 'Nateglinide'),
(NEWID(), 'Levetiracetamum'),
(NEWID(), 'Esomeprazolum magnesicum'),
(NEWID(), 'Betahistini dihydrochloridum'),
(NEWID(), 'Amlodipinum'),
(NEWID(), 'Levodropropizinum'),
(NEWID(), 'Saccharum'),
(NEWID(), 'Gliclazidum'),
(NEWID(), 'Rasagilinum'),
(NEWID(), 'Dihydrocodeini tartras'),
(NEWID(), 'Interferonum pegylateum alfa'),
(NEWID(), 'Linezolidum'),
(NEWID(), 'Verteporfin'),
(NEWID(), 'Furosemidum'),
(NEWID(), 'Aqua ad iniectabili'),
(NEWID(), 'Danazolum'),
(NEWID(), 'Nefopami hydrochloridum'),
(NEWID(), 'Lercanidipini hydrochloridum'),
(NEWID(), 'Valsartanum'),
(NEWID(), 'Dextranum'),
(NEWID(), 'Hypromellosum'),
(NEWID(), 'Glycine max.semen extractum siccum'),
(NEWID(), 'Diosminum'),
(NEWID(), 'Factor IX coagulationis humanus'),
(NEWID(), 'Dinatrii pamidronas'),
(NEWID(), 'Dinitrogenii oxidum nie mniej niż'),
(NEWID(), 'Glucosum (roztwór'),
(NEWID(), 'Tobramycinum'),
(NEWID(), 'Rasburicasum'),
(NEWID(), 'Hedera helix extractum'),
(NEWID(), 'Eletriptanum'),
(NEWID(), 'Acidum tolfenamicum'),
(NEWID(), 'Celiprololi hydrochloridum'),
(NEWID(), 'Nikotyna z kationitem'),
(NEWID(), 'Dalteparinum natricum ad.'),
(NEWID(), 'Diphenhydramini hydrochloridum'),
(NEWID(), 'Vaccinum hepatitidis B (ADNr)'),
(NEWID(), 'Nabumetonum'),
(NEWID(), 'Sertralinum'),
(NEWID(), 'Amlodipini maleas'),
(NEWID(), 'Lymecyclinum (równoważna tetracyklinie)'),
(NEWID(), 'Pimecrolimusum'),
(NEWID(), 'Buprenorphinum'),
(NEWID(), 'Sevelamerum'),
(NEWID(), 'Sevelameri hydrochloridum'),
(NEWID(), 'Agalsidasum beta'),
(NEWID(), 'Lamotriginu'),
(NEWID(), 'Lamotriginum'),
(NEWID(), 'Mitotanum'),
(NEWID(), 'Pojedyncze alergoidy pyłków roślin'),
(NEWID(), 'Ferrum'),
(NEWID(), 'Ferri hydroxydum polymaltosum'),
(NEWID(), 'Carbomerum'),
(NEWID(), 'Menotropinum humanum'),
(NEWID(), 'Heparynoidy'),
(NEWID(), 'Peginterferonum alfa'),
(NEWID(), 'Factor VIII coagulationis humanus'),
(NEWID(), 'Ertapenemum'),
(NEWID(), 'Benzoxonii chloridum'),
(NEWID(), 'Lutropinum alfa'),
(NEWID(), 'Oseltamivirum'),
(NEWID(), 'Voriconazolum'),
(NEWID(), 'Donepezili hydrochloridum monohydricum'),
(NEWID(), 'Vardenafilum'),
(NEWID(), 'Tadalafilum'),
(NEWID(), 'Nimesulidum'),
(NEWID(), 'Meloxicamum'),
(NEWID(), 'Plantaginis lanceolatae herbae extractun fluidum '),
(NEWID(), 'Atorvastatinum calcicum trihydricum'),
(NEWID(), 'Ribavirinum'),
(NEWID(), 'Aluminii acetotartras'),
(NEWID(), 'Etacridini lactas'),
(NEWID(), 'Oxygenium nie mniej niż'),
(NEWID(), 'Memantini hydrochloridum'),
(NEWID(), 'Paroxetini hydrochloridum'),
(NEWID(), 'Sunitinibum'),
(NEWID(), 'Camphorum'),
(NEWID(), 'Cefuroximum axetilum'),
(NEWID(), 'Ambazonum'),
(NEWID(), 'Prothrombinum multiplex humanum'),
(NEWID(), 'Pyridostigmini bromidum'),
(NEWID(), 'Glycerolum'),
(NEWID(), 'Olopatadini hydrochloridum'),
(NEWID(), 'Perindoprilum argininum'),
(NEWID(), 'Omalizumabum'),
(NEWID(), 'Dienogestum'),
(NEWID(), 'Sufentanilum (cytrynian)'),
(NEWID(), 'toremifenum'),
(NEWID(), 'Ioversolum'),
(NEWID(), 'Isotretinoinum'),
(NEWID(), 'Metformini hydrochloridum'),
(NEWID(), 'Nitrogenii oxidu'),
(NEWID(), 'Acidum undecylenicum'),
(NEWID(), 'Cynarae extractum siccum'),
(NEWID(), 'Amitriptylinum hydrochloridum'),
(NEWID(), 'Glycinis seminis extractum siccum'),
(NEWID(), 'Zaleplonum'),
(NEWID(), 'Calcii dobesilas'),
(NEWID(), 'Letrozolum'),
(NEWID(), 'Cefotaximum natricum'),
(NEWID(), 'Maropitant citrate'),
(NEWID(), 'Imidaprili hydrochloridum'),
(NEWID(), 'Estradioli valeras'),
(NEWID(), 'Ibuprofenum q.s'),
(NEWID(), 'Wyciągi alergenow'),
(NEWID(), 'Ceftriaxonum natricum'),
(NEWID(), 'Ketotifeni hydrofumaras'),
(NEWID(), 'Ioflupanum '),
(NEWID(), 'Enfuvirtidum'),
(NEWID(), 'Reteplasum'),
(NEWID(), 'Teriparatidum'),
(NEWID(), 'Basiliximabum'),
(NEWID(), 'Sulfur hexafluoridum'),
(NEWID(), 'Fondaparinuxum natricum'),
(NEWID(), 'Fulvestrantum'),
(NEWID(), 'Interferonum alfa'),
(NEWID(), 'Laronidasum'),
(NEWID(), 'Thyrotropinum alfa'),
(NEWID(), 'Iloprostum'),
(NEWID(), 'Ibritumomabum tiuxetanum'),
(NEWID(), 'Yttrii '),
(NEWID(), 'Pegvisomantum '),
(NEWID(), 'Caspofunginum'),
(NEWID(), 'Anakinrum'),
(NEWID(), 'Darbepoetinum alfa'),
(NEWID(), 'Insulinum detemirum'),
(NEWID(), 'Histamini dihydrochloridum'),
(NEWID(), 'Propanolum'),
(NEWID(), 'Isopropanolum'),
(NEWID(), 'Tenofovirum disoproxilum'),
(NEWID(), 'Adefoviri dipivoxil'),
(NEWID(), 'Emtricitabinum'),
(NEWID(), 'Chondroityny siarczan kwaśny'),
(NEWID(), 'Cefoperazonum natricum'),
(NEWID(), 'Sulbactamum natricum'),
(NEWID(), 'Levofloxacinum'),
(NEWID(), 'Paroxetinum'),
(NEWID(), 'Anastrozolum'),
(NEWID(), 'Sertindolum'),
(NEWID(), 'Estazolamum'),
(NEWID(), 'Zincum'),
(NEWID(), 'Bevacizumabum'),
(NEWID(), 'Amlodipine besilate'),
(NEWID(), 'Darifenacinum'),
(NEWID(), 'Salbutamoli sulfas'),
(NEWID(), 'Sumatriptani succinas'),
(NEWID(), 'gadoksetynian disodowy'),
(NEWID(), 'Esomeprazol sodowy'),
(NEWID(), 'Arsenii trioxidum'),
(NEWID(), 'Quetiapinum'),
(NEWID(), 'Everolimusum'),
(NEWID(), 'Nicotynamidum'),
(NEWID(), 'Ciclesonidu'),
(NEWID(), 'Ramiprilum'),
(NEWID(), 'Bexarotene'),
(NEWID(), 'Mercaptamini bitartras'),
(NEWID(), 'Acidum carglumicum'),
(NEWID(), 'Ammonii bituminosulfonas'),
(NEWID(), 'Natrii ibandronas monohydricum'),
(NEWID(), 'sól sodowa atorwastatyny'),
(NEWID(), 'Zingiberis rhizoma'),
(NEWID(), 'Zofenoprilum calcicum'),
(NEWID(), 'Solifenacyny bursztynia'),
(NEWID(), 'Epinastyny chlorowodorek'),
(NEWID(), 'Rosuvastatinum calicum'),
(NEWID(), 'Deferasiroxum'),
(NEWID(), 'Pseudoephedrini hydrochloridum'),
(NEWID(), 'Betamethasonum'),
(NEWID(), 'Alclometasoni dipropionas'),
(NEWID(), 'Mirtazapinum hemihydricum'),
(NEWID(), 'Metoprololi succinas'),
(NEWID(), 'Acidum mycophenolicum'),
(NEWID(), 'Rifaximinum'),
(NEWID(), 'Etoricoxibum'),
(NEWID(), 'Ezetimibum'),
(NEWID(), 'Abacavirum'),
(NEWID(), 'Saquinavirum'),
(NEWID(), 'Butaconazoli nitras'),
(NEWID(), 'Dapagliflozinum'),
(NEWID(), 'Terbinafinum'),
(NEWID(), 'Lapatinibum'),
(NEWID(), 'Quetiapini fumaras'),
(NEWID(), 'Nepafenac'),
(NEWID(), 'Posaconazolum'),
(NEWID(), 'Glimepiridum'),
(NEWID(), 'Macrogolum'),
(NEWID(), 'Fludarabini phosphas'),
(NEWID(), 'Aqua ad iniectabilia'),
(NEWID(), 'Hexylis aminolevulinatis hydrochloridum'),
(NEWID(), 'Aliskirenum'),
(NEWID(), 'Etonogestrelum'),
(NEWID(), 'Acidum alendronicum'),
(NEWID(), 'Sitagliptinum'),
(NEWID(), 'Iodum'),
(NEWID(), 'Acidum boricum'),
(NEWID(), 'Hydrogenii peroxidum'),
(NEWID(), 'Oxymetholonum'),
(NEWID(), 'Zinci aspartas'),
(NEWID(), 'Atomoxetini hydrochloridum'),
(NEWID(), 'Thymolum'),
(NEWID(), 'Immunoglobulinum humanum normal'),
(NEWID(), 'Travoprostum'),
(NEWID(), 'Timololum'),
(NEWID(), 'Natrii phenylbutyras'),
(NEWID(), 'Immunoglobulinum humanum normale'),
(NEWID(), 'Carbetocinum'),
(NEWID(), 'Eplerenonum'),
(NEWID(), 'Omega'),
(NEWID(), 'Galsufaze'),
(NEWID(), 'Itraconazolum'),
(NEWID(), 'Dexketoprofenum'),
(NEWID(), 'Beclometasoni dipropiona'),
(NEWID(), 'Risperidonum'),
(NEWID(), 'Warfarinum natricum'),
(NEWID(), 'Alglukozydaza alfa'),
(NEWID(), 'Ranibizumabum'),
(NEWID(), 'Daptomycinum'),
(NEWID(), 'Ceftiofurum'),
(NEWID(), 'Tetracyclini hydrochloridum'),
(NEWID(), 'Calcii gluconas'),
(NEWID(), 'Kolistyny siarczan'),
(NEWID(), 'Flumetryna'),
(NEWID(), 'Propoksur'),
(NEWID(), 'Carprofenum'),
(NEWID(), 'Oleum Jecoris Aselli'),
(NEWID(), 'tylozyna (w postaci fosforanu)'),
(NEWID(), 'Amitraza'),
(NEWID(), 'Levamisoli hydrochloridum'),
(NEWID(), 'Cefapirin benzathine'),
(NEWID(), 'Tiamulini hydrogenofumaras '),
(NEWID(), 'Bromhexini hydrochloridum'),
(NEWID(), 'Tiamulinum '),
(NEWID(), 'Detomidyny chlorowodorek '),
(NEWID(), 'Karbetocyna'),
(NEWID(), 'Doxycyclinum monohydricum'),
(NEWID(), 'Butorphanolum'),
(NEWID(), 'Ceftiofuri hydrochloridum'),
(NEWID(), 'Sapropterin dihydrochloride'),
(NEWID(), 'Oxytetracyclini hydrochloridum'),
(NEWID(), 'Marbofloksacyna'),
(NEWID(), 'Chlortetracyclini hydrochloridum'),
(NEWID(), 'Doxycyclini hyclas'),
(NEWID(), 'Paromomycyna'),
(NEWID(), 'Permethrinum'),
(NEWID(), 'Piryproxyfen'),
(NEWID(), 'insulina wieprzowa'),
(NEWID(), 'Ampicillinum trihydricum'),
(NEWID(), 'Karazololu chlorowodorek'),
(NEWID(), 'Ivermectinum'),
(NEWID(), 'Tafluprostum'),
(NEWID(), 'Fluniksyna'),
(NEWID(), 'Azaperon'),
(NEWID(), 'Propentofylina'),
(NEWID(), 'B-karoten'),
(NEWID(), 'Ketaminum'),
(NEWID(), 'Pyranteli embonas '),
(NEWID(), 'Imidokarbu dipropionian'),
(NEWID(), 'Cefalexinum monohydricum'),
(NEWID(), 'Metamizolum natricum monohydricum'),
(NEWID(), 'busereliny octan'),
(NEWID(), 'Streptomycyny siarczan'),
(NEWID(), 'Benzylpenicillinum procainum'),
(NEWID(), 'Sulfadoxinum'),
(NEWID(), 'Ziprasidonum'),
(NEWID(), 'Menbuton'),
(NEWID(), 'Cefacetryl sodowy'),
(NEWID(), 'Fentanylum'),
(NEWID(), 'Glatirameri acetas'),
(NEWID(), 'stiripentolum'),
(NEWID(), 'Heminum humanum'),
(NEWID(), 'Exenatidum'),
(NEWID(), 'Chlorhexidini digluconas'),
(NEWID(), 'Phleum pratense'),
(NEWID(), 'Treprostinilum'),
(NEWID(), 'Doconazolum'),
(NEWID(), 'Topiramatum'),
(NEWID(), 'Nelarabinum'),
(NEWID(), 'Vildagliptinum'),
(NEWID(), 'Desmopressinum'),
(NEWID(), 'Tobramycinum '),
(NEWID(), 'recombinant human erythropoietin alfa'),
(NEWID(), 'Epoetinum alfa'),
(NEWID(), 'Erythropoietinum alfa humanum recombinatum'),
(NEWID(), 'Maraviroc'),
(NEWID(), 'Anidulafunginum'),
(NEWID(), 'Pravastatinum natricum'),
(NEWID(), 'Fesoterodine'),
(NEWID(), 'Mecaserminum'),
(NEWID(), 'Rimantadini hydrochloridum'),
(NEWID(), 'Temsirolimusum'),
(NEWID(), 'Natrii risedronas'),
(NEWID(), 'Rupatadinum'),
(NEWID(), 'Escitalopramum'),
(NEWID(), 'D-Kloprostenol'),
(NEWID(), 'Immunoglobulinum humanum anti-D'),
(NEWID(), 'Albendazolum'),
(NEWID(), 'Fenbendazol '),
(NEWID(), 'Tylmikozyna'),
(NEWID(), 'Flumechina'),
(NEWID(), 'tylozyna (w postaci winianu)'),
(NEWID(), 'Tylozyna '),
(NEWID(), 'Oksytetracyklina'),
(NEWID(), 'Magnesii sulfas'),
(NEWID(), 'Clofarabine'),
(NEWID(), 'Flumetazon'),
(NEWID(), 'Tiamfenikol'),
(NEWID(), 'Florfenicolum'),
(NEWID(), 'Toltrazurilum'),
(NEWID(), 'Alfaprostol'),
(NEWID(), 'Tibolonum'),
(NEWID(), 'Micafunginum'),
(NEWID(), 'Praziquantelum'),
(NEWID(), 'Fenylopropanoloamina'),
(NEWID(), 'Flunixin meglumine'),
(NEWID(), 'Trilostan'),
(NEWID(), 'Sól sodowa deksakloprostenolu'),
(NEWID(), 'Iodum do'),
(NEWID(), 'Medetomidini hydrochloridum'),
(NEWID(), 'Policresulenum'),
(NEWID(), 'Trabectedinum'),
(NEWID(), 'Azytromycyna dwuwodna'),
(NEWID(), 'Nebivololum'),
(NEWID(), 'Raltegrawir'),
(NEWID(), 'Glucosaminum'),
(NEWID(), 'Fludeoxyglucosum'),
(NEWID(), 'Tizanidinum'),
(NEWID(), 'Ksylazyny chlorowodorek Brak danyc'),
(NEWID(), 'Methylprednisoloni acetas'),
(NEWID(), 'Eculizumab'),
(NEWID(), 'Dorzolamidum'),
(NEWID(), 'Oxycodoni hydrochloridum'),
(NEWID(), 'Immunoglobulin huma'),
(NEWID(), 'Bacitracinum'),
(NEWID(), 'Tolterodini hydrogenotartras'),
(NEWID(), 'Nebivololi hydrochloridum'),
(NEWID(), 'Melissae herbae recentis intractum '),
(NEWID(), 'Chlorambucilum'),
(NEWID(), 'Mometasoni furoas (zmikronizowany)'),
(NEWID(), 'Clopidogrelum hydrosulfas'),
(NEWID(), 'Gamitromycyna'),
(NEWID(), 'Tylwalozyna'),
(NEWID(), 'Tylvalosin'),
(NEWID(), 'Oksym milbemycyny'),
(NEWID(), 'Praziquantelum '),
(NEWID(), 'Tetracainum'),
(NEWID(), 'Sugammadexum'),
(NEWID(), 'Rivaroxaban'),
(NEWID(), 'Danofloksacyna'),
(NEWID(), 'Methylnaltrexoni bromidum'),
(NEWID(), 'PMSG'),
(NEWID(), 'Lacosamidum'),
(NEWID(), 'Urticae succus'),
(NEWID(), 'Hexamidini diisetionas'),
(NEWID(), 'Tilmicosinum'),
(NEWID(), 'vinorelbinum'),
(NEWID(), 'Doxycycline hyclate'),
(NEWID(), 'Pyriproxyfenum'),
(NEWID(), 'Epoetinum zeta'),
(NEWID(), 'Proligeston'),
(NEWID(), 'gonadorelina (w postaci octanu)'),
(NEWID(), 'Natrii alendronas'),
(NEWID(), 'neomycyny siarczan'),
(NEWID(), 'Enilkonazol'),
(NEWID(), 'Ronidazol'),
(NEWID(), 'Deltametryna'),
(NEWID(), 'Clonidini hydrochloridum'),
(NEWID(), 'Tocilizumabum'),
(NEWID(), 'Mycobacterium bovis BCG, sczep duński'),
(NEWID(), 'Spektynomycyna'),
(NEWID(), 'Aliskireni hemifumaras'),
(NEWID(), 'kloprostenol sodowy'),
(NEWID(), 'Glucagoni hydrochloridum'),
(NEWID(), 'Acepromazinum'),
(NEWID(), 'Flubendazol'),
(NEWID(), 'Silybi mariani extractum siccum'),
(NEWID(), 'Pramipexolum'),
(NEWID(), 'Agomelatinum'),
(NEWID(), 'Prasugrelum'),
(NEWID(), 'Telbivudinum'),
(NEWID(), 'Pyrantel tartrate'),
(NEWID(), 'Hydroxocobalamin'),
(NEWID(), 'Certolizumabum pegol'),
(NEWID(), 'Romiplostim'),
(NEWID(), 'Ulipristali acetas'),
(NEWID(), 'Bicalutamidum'),
(NEWID(), 'Amprolium chlorowodorek'),
(NEWID(), 'Tacrolimusum monohydricum'),
(NEWID(), 'Ergometryny maleinian '),
(NEWID(), 'Lornoxicamum'),
(NEWID(), 'Olanzapini benzoas'),
(NEWID(), 'Eflornithinum'),
(NEWID(), 'Etanerceptum'),
(NEWID(), 'Isoniazidum'),
(NEWID(), 'Inhibitor '),
(NEWID(), 'Białko całkowite'),
(NEWID(), 'Imiglucerasum'),
(NEWID(), 'Golimumabum'),
(NEWID(), 'Gefitinibum'),
(NEWID(), 'Firocoxib'),
(NEWID(), 'Liraglutidum'),
(NEWID(), 'Peforelinum'),
(NEWID(), 'Hydrocortisoni acetas'),
(NEWID(), 'Immunoglobulinum humanum normale (IgG)'),
(NEWID(), 'Białko osocza ludzkiego'),
(NEWID(), 'Valganciclovirum'),
(NEWID(), 'Plerixafor'),
(NEWID(), 'Saxagliptin'),
(NEWID(), 'Osaterone acetate'),
(NEWID(), 'Ropiniroli hydrochloridum'),
(NEWID(), 'Interferon rekombinowany'),
(NEWID(), 'Nevirapinum'),
(NEWID(), 'Immunoglobulinum humanum hepatitidis B'),
(NEWID(), 'Vinflunine ditartrate'),
(NEWID(), 'Torasemidum'),
(NEWID(), 'Cilazaprilum monohydricum'),
(NEWID(), 'Moxifloxacini hydrochloridum'),
(NEWID(), 'Indacateroli maleas'),
(NEWID(), 'Epoetinum alpha')

insert into ActiveSubstances
values(NEWID(), 'Amantadini sulfas'),
(NEWID(), 'Dexmedetomidinum'),
(NEWID(), 'Tulathromycin'),
(NEWID(), 'Toceranibum'),
(NEWID(), 'Vedaprofenum '),
(NEWID(), 'Selamectin'),
(NEWID(), 'Mavacoxib'),
(NEWID(), 'Amoxicillin trihydrate'),
(NEWID(), 'Dibotermin alfa'),
(NEWID(), 'Escitalopramum w postaci szczawianu -'),
(NEWID(), 'Escitalopramum w posatci szczawianu -'),
(NEWID(), 'Eltrombopagum'),
(NEWID(), 'Escitaloprami oxalas'),
(NEWID(), 'Ciclopiroxum'),
(NEWID(), 'Clopidogrelum besilate'),
(NEWID(), 'Tocofersolanum'),
(NEWID(), 'Denosumabum'),
(NEWID(), 'Spiritus salicylatus'),
(NEWID(), 'Progesteronum (mikronizowany)'),
(NEWID(), 'Imatinibi mesilas'),
(NEWID(), 'Żelazo (w postaci derizomaltozy żelazowej)'),
(NEWID(), 'Rivastigmini hydrogenotartras'),
(NEWID(), 'Wyciąg alergenów z pyłków traw '),
(NEWID(), 'Roflumilastum'),
(NEWID(), 'Thymi extractum fluidum'),
(NEWID(), 'Mannitolum'),
(NEWID(), 'Ibuprofenum lysinum'),
(NEWID(), 'Tizanidini hydrochloridum'),
(NEWID(), 'Fluticasoni propionas'),
(NEWID(), 'Exemestanum'),
(NEWID(), 'Zolmitriptanum'),
(NEWID(), 'Asenapinum '),
(NEWID(), 'Corifollitropin alfa'),
(NEWID(), 'Conestatum alfa'),
(NEWID(), 'Paroxetini hydrochloridum (semihydricum)'),
(NEWID(), 'Chlormadinoni acetas'),
(NEWID(), 'Bendamustini hydrochloridum'),
(NEWID(), 'Olmesartanum medoxomilum'),
(NEWID(), 'Białko całkowite (mniej /równo'),
(NEWID(), 'Imipenemum'),
(NEWID(), 'Cilastatinum natricum'),
(NEWID(), 'Menotropina'),
(NEWID(), 'Rabeprazolum natricum'),
(NEWID(), 'Butorphanolum Otoczka Opadry II'),
(NEWID(), 'Sennae fructus angustifoliae'),
(NEWID(), 'Sennae folium'),
(NEWID(), 'Prednisoloni acetas'),
(NEWID(), 'Ticagrelorum'),
(NEWID(), 'Itopridi hydrochloridum'),
(NEWID(), 'Epoetinum theta'),
(NEWID(), 'Vernakalant hydrochloride'),
(NEWID(), 'Olanzapiny dichlorowodorek trójwodny'),
(NEWID(), 'Sarolaner'),
(NEWID(), 'Carprofenum do'),
(NEWID(), 'Orlistatum'),
(NEWID(), 'Atipamezoli hydrochloridum'),
(NEWID(), 'Kompleks dekstranu i żelaza (III)'),
(NEWID(), 'Terlipressini acetas'),
(NEWID(), 'Kalii bromidum'),
(NEWID(), 'Clorsulon'),
(NEWID(), 'Tilmicosini phosphas'),
(NEWID(), 'Salbutamolum'),
(NEWID(), 'Triptorelini embonas'),
(NEWID(), 'Cimicoxibum'),
(NEWID(), 'Cabazitaxelum'),
(NEWID(), 'Natrii pentosani polysulfas'),
(NEWID(), 'Ropinirolum'),
(NEWID(), 'Fingolimodum'),
(NEWID(), 'Leflunomidum'),
(NEWID(), 'Fibrinogenum humanum'),
(NEWID(), 'Coffeini citras'),
(NEWID(), 'Butamirati citras'),
(NEWID(), 'Lovastatinum'),
(NEWID(), 'Glucosamini sulfas'),
(NEWID(), 'Bromfenacum'),
(NEWID(), 'Diethylamini salicylas'),
(NEWID(), 'Cyproheptadini hydrochloridum'),
(NEWID(), 'Factor humanus von Willebrandi'),
(NEWID(), 'Zuclopenthixoli dihydrochloridum'),
(NEWID(), 'Salmeterolu ksynafonian'),
(NEWID(), 'Acidum ibandronicum'),
(NEWID(), 'Immunoglobulinum humanum normale (SCIg)'),
(NEWID(), 'Propofolum '),
(NEWID(), 'Tianeptinum natricum'),
(NEWID(), 'Galantaminum'),
(NEWID(), 'Gonadorelinum'),
(NEWID(), 'Gonadorelini acetas'),
(NEWID(), 'Tildipirozinum'),
(NEWID(), 'Pimobendanum '),
(NEWID(), 'Thiotepum'),
(NEWID(), 'Loperamidi hydrochloridum'),
(NEWID(), 'Rizatriptani benzoas'),
(NEWID(), 'Atorwastyatyna z L-lizyną'),
(NEWID(), 'Cholecalciferolum, pulvis'),
(NEWID(), 'Levocetirizini dihydrochloridum '),
(NEWID(), 'Szczepionka wieloważna'),
(NEWID(), 'Imidaclopridum'),
(NEWID(), 'Amikacini sulfas'),
(NEWID(), 'Hedera helix extractum ekstrahent-etanol'),
(NEWID(), 'Rybosomy bakteryjne'),
(NEWID(), 'Proteoglikany'),
(NEWID(), 'Cellulosum microcristallinum'),
(NEWID(), 'Phenobarbitalum '),
(NEWID(), 'Saxagliptinum'),
(NEWID(), 'Pioglitazonum'),
(NEWID(), 'Suxibuzone (microcapsules)'),
(NEWID(), 'Racecadotrilum'),
(NEWID(), 'Salmeterolum'),
(NEWID(), 'Diosmectiteum'),
(NEWID(), 'Deslorelin acetate'),
(NEWID(), 'Vandetanib'),
(NEWID(), 'Vemurafenibum'),
(NEWID(), 'Fidaxomicin'),
(NEWID(), 'Escinum'),
(NEWID(), 'Quinaprilum'),
(NEWID(), 'Fenbendazolum'),
(NEWID(), 'Pasireotidum'),
(NEWID(), 'Ferrosi sulfas'),
(NEWID(), 'Acidum folicum'),
(NEWID(), 'Calcii glubionas'),
(NEWID(), 'Canakinumabum'),
(NEWID(), 'Tiapridi hydrochloridum'),
(NEWID(), 'Levofloxacini hemihydras'),
(NEWID(), 'Kroskarmelozy sól sodowa'),
(NEWID(), 'Rupatadini fumaras'),
(NEWID(), 'Dapoxetinum'),
(NEWID(), 'Tapentadoli hydrochloridum'),
(NEWID(), 'Krzemionka koloidalna'),
(NEWID(), 'Oxycodoni hydrochloridum ad'),
(NEWID(), 'Ciclopiroxum ad'),
(NEWID(), 'Glycopyrronii bromidum'),
(NEWID(), 'Ruxolitinibum'),
(NEWID(), 'cameliae sinensin folii extractum siccum'),
(NEWID(), 'Gentamicinum'),
(NEWID(), 'Aclidinii bromidum'),
(NEWID(), 'Chloroprocaini hydrochloridum'),
(NEWID(), 'Magnesii stearas'),
(NEWID(), 'Axitinibum'),
(NEWID(), 'Crizotinibum'),
(NEWID(), 'Brentuximabum vedotini'),
(NEWID(), 'Mifamurtidum'),
(NEWID(), 'Eribulini mesylas'),
(NEWID(), 'Almotryptanu jabłczan'),
(NEWID(), 'Pentobarbital sodium'),
(NEWID(), 'Urapidilum'),
(NEWID(), 'Cloprostenol sodium'),
(NEWID(), 'Dexmedetomidini hydrochloridum'),
(NEWID(), 'Sofosbuvirum'),
(NEWID(), 'Nitroxolinum'),
(NEWID(), 'Cefquinomum'),
(NEWID(), 'Lixisenatidum'),
(NEWID(), 'Midazolami hydrochloridum'),
(NEWID(), 'Benzylpenicillinum procainum do ustalenia p'),
(NEWID(), 'Doramectinum'),
(NEWID(), 'Mirabegronum'),
(NEWID(), 'Perindoprili tosilas'),
(NEWID(), 'Fampridinum'),
(NEWID(), 'Digoxinum'),
(NEWID(), 'Bosutinib'),
(NEWID(), 'Bosutinibum'),
(NEWID(), 'Ocriplasminum'),
(NEWID(), 'Marbofloksacyna do ustalenia p'),
(NEWID(), 'Ivermectinum do ustalenia p'),
(NEWID(), 'Monensin (Monensin sodium)'),
(NEWID(), 'Pertuzumabum'),
(NEWID(), 'Nalmefeni hydrochloridum dihydricum'),
(NEWID(), 'Pirfenidonum'),
(NEWID(), 'Vismodegibum'),
(NEWID(), 'Clenbuterol hydrochloride'),
(NEWID(), 'Ferrii (III) isomaltosidum'),
(NEWID(), 'Lipegfilgrastim'),
(NEWID(), 'Flupentixoli dihydrochloridum'),
(NEWID(), 'Dabrafenib'),
(NEWID(), 'Enzalutamidum'),
(NEWID(), 'Oclacinibum'),
(NEWID(), 'Oclacitinibum'),
(NEWID(), 'Regorafenibum'),
(NEWID(), 'Alemtuzumabum'),
(NEWID(), 'Teriflunomidum'),
(NEWID(), 'Butorfanolu winian'),
(NEWID(), 'Nitrofuralu'),
(NEWID(), 'Cilostazolum'),
(NEWID(), 'Florbetapirum '),
(NEWID(), 'Trastuzumabum emtansinum'),
(NEWID(), 'Dolutegravirum'),
(NEWID(), 'Dexlansoprazolum'),
(NEWID(), 'Fluralanerum'),
(NEWID(), 'Olopatadinum'),
(NEWID(), 'Loxapinum'),
(NEWID(), 'Midazolamum'),
(NEWID(), 'Aztreonamum'),
(NEWID(), 'Sacubitrilum'),
(NEWID(), 'Colistimethatum natricum'),
(NEWID(), 'Ivabradinum'),
(NEWID(), 'Defibrotidum'),
(NEWID(), 'Azilsartanum medoxomilum'),
(NEWID(), 'Deferipronum'),
(NEWID(), 'Amifampridinum'),
(NEWID(), 'Perampanelum'),
(NEWID(), 'Urea'),
(NEWID(), 'Methadoni hydrochloridum'),
(NEWID(), 'Cefepimi dihydrochloridum'),
(NEWID(), 'Bosentanum'),
(NEWID(), 'Alogliptinum'),
(NEWID(), 'Aqua pro injectione do'),
(NEWID(), 'Rufinamidum'),
(NEWID(), 'Rotigotinum'),
(NEWID(), 'Cladribinum'),
(NEWID(), 'Lomitapidum'),
(NEWID(), 'Perflutrenum'),
(NEWID(), 'Toxinum botulinicum typum A ad iniectabile'),
(NEWID(), 'Hormon folikulotropowy'),
(NEWID(), 'Lacidipinum'),
(NEWID(), 'Bimatoprost'),
(NEWID(), 'Acidum cholicum'),
(NEWID(), 'Zonisamidum'),
(NEWID(), 'Pixantroni dimaleas'),
(NEWID(), 'Eslicarbazepini acetas'),
(NEWID(), 'Lorazepamum'),
(NEWID(), 'Solifenacini succinas'),
(NEWID(), 'Radium dichloridum R'),
(NEWID(), 'Cobicistatum'),
(NEWID(), 'Regadenosonum'),
(NEWID(), 'Insulinum degludecum'),
(NEWID(), 'Acidum gadotericum'),
(NEWID(), 'Formoteroli fumaras dihydricus'),
(NEWID(), 'Elosulfasum alfa'),
(NEWID(), 'Vedolizumabum'),
(NEWID(), 'Granisetroni hydrochloridum'),
(NEWID(), 'Besilesomabum'),
(NEWID(), 'Kwas paraaminosalicylowy'),
(NEWID(), 'Kabozantynibum'),
(NEWID(), 'Vortioxetini hydrobromidum'),
(NEWID(), 'Pantoprazolum natricum sesquihydricum '),
(NEWID(), 'Phospholipidum essentiale'),
(NEWID(), 'Altrenogestum'),
(NEWID(), 'Mometasoni furoas monohydricum'),
(NEWID(), 'Trametinibum'),
(NEWID(), 'Brimonidinum'),
(NEWID(), 'Bromonidyna'),
(NEWID(), 'Florbetaben '),
(NEWID(), 'Riociguatum'),
(NEWID(), 'Factor XIII'),
(NEWID(), 'Propranololi hydrochloridum'),
(NEWID(), 'Fumaran dimetylu'),
(NEWID(), 'Delamanid'),
(NEWID(), 'Azithromycinum dihydricum'),
(NEWID(), 'Fenticonazoli nitras'),
(NEWID(), 'Metyraponum'),
(NEWID(), 'Propyphenazonum'),
(NEWID(), 'Peginterferonum beta'),
(NEWID(), 'Obinutuzumabum'),
(NEWID(), 'Bisacodylum'),
(NEWID(), 'Flutemetamolum'),
(NEWID(), 'Buprenorphini hydrochloridum'),
(NEWID(), 'Idelalizybum'),
(NEWID(), 'tylozyna (zasada)'),
(NEWID(), 'Marbofloxacinum '),
(NEWID(), 'Inosinum pranobexum'),
(NEWID(), 'Benzydamini hydrochloridum'),
(NEWID(), 'Bortezomibum'),
(NEWID(), 'Dutasteridum'),
(NEWID(), 'Natrii citras'),
(NEWID(), 'Chondroitini sulfas'),
(NEWID(), 'Pivmecilinami hydrochloridum'),
(NEWID(), 'Hederae helicis folii extractum siccum'),
(NEWID(), 'Hydrocortisoni natrii phosphas'),
(NEWID(), 'Aripiprazolum'),
(NEWID(), 'Cinacalcetii hydrochloridum'),
(NEWID(), 'Apomorphini hydrochloridum'),
(NEWID(), 'Colchicinum'),
(NEWID(), 'Produkt złożony'),
(NEWID(), 'Atovaquonum'),
(NEWID(), 'Proguanili hydrochloridum'),
(NEWID(), 'Polidocanolum'),
(NEWID(), 'Eucalypti aetheroleum'),
(NEWID(), 'Deferoxamini mesilas'),
(NEWID(), 'Valganciclovirum w postaci chlorowodorku:'),
(NEWID(), 'Acidum cromoglicicum'),
(NEWID(), 'Noradrenalinum'),
(NEWID(), 'Adrenaline Acid Tartrate'),
(NEWID(), 'Insulinum glargine'),
(NEWID(), 'Apremilastum'),
(NEWID(), 'Spinosadum'),
(NEWID(), 'Dulaglutidum'),
(NEWID(), 'Ledipasvirum'),
(NEWID(), 'Naloxegolum'),
(NEWID(), 'Secukinumabum'),
(NEWID(), 'Carteololi hydrochloridum'),
(NEWID(), 'Entacapone'),
(NEWID(), 'Hederae helicis folii extractum siccum '),
(NEWID(), 'Aceclofenacum'),
(NEWID(), 'Tetrabenazinum'),
(NEWID(), 'Landiololi hydrochloridum'),
(NEWID(), 'Olaparibum'),
(NEWID(), 'Estrogeny skoniugowane'),
(NEWID(), 'Bazedoxifenum'),
(NEWID(), 'Afamelanotidum'),
(NEWID(), 'Milbemycini oxime'),
(NEWID(), 'Abacaviri hydrochloridum'),
(NEWID(), 'Ramucirumabum'),
(NEWID(), 'Eliglustatum'),
(NEWID(), 'Citicolinum natricum'),
(NEWID(), 'Nonacogum gamma (rDNA)'),
(NEWID(), 'Ezetymib'),
(NEWID(), 'Betamethasoni valeras'),
(NEWID(), 'Fipronilum'),
(NEWID(), 'Cisatracurium'),
(NEWID(), 'Valerianae extractum hydroalcoholicum siccum'),
(NEWID(), 'Ospemifenum'),
(NEWID(), 'Ceftazidimum pentahydricum'),
(NEWID(), 'Nitrogenii oxydum'),
(NEWID(), 'Safinamidum'),
(NEWID(), 'Rasagilini tartras'),
(NEWID(), 'Progesterone'),
(NEWID(), 'Darunavirum'),
(NEWID(), 'Lewozymendan'),
(NEWID(), 'Ropivacaini hydrochloridum'),
(NEWID(), '(S)-methoprenum'),
(NEWID(), 'Dinotefuranum'),
(NEWID(), 'Caspofungini acetas'),
(NEWID(), 'Tedizolidii phosphas'),
(NEWID(), 'Prazykwantel'),
(NEWID(), 'Ceritinibum'),
(NEWID(), 'Cangrelori tetranatricum'),
(NEWID(), 'Erythromycinum cum zinco'),
(NEWID(), 'Rosmarini oleum'),
(NEWID(), 'Duloxetini hydrochloridu'),
(NEWID(), 'Zinci sulphas'),
(NEWID(), 'Naphazolini nitras'),
(NEWID(), 'Desfluranum'),
(NEWID(), 'Colistini sulfas'),
(NEWID(), 'Aluminii acetas tartras'),
(NEWID(), 'Evolocumabum'),
(NEWID(), 'Dimetindeni maleas'),
(NEWID(), 'Bupropioni hydrochloridum'),
(NEWID(), 'Silybi mariani fructus extractum siccum'),
(NEWID(), 'Rasagilini hemitartras'),
(NEWID(), 'Duloxetini hydrochloridum'),
(NEWID(), 'D-Cloprostenolum'),
(NEWID(), 'Phenylephrinum'),
(NEWID(), 'Drotaverini hydrochloridum'),
(NEWID(), 'Lenvatinibum'),
(NEWID(), 'Clobazamum'),
(NEWID(), 'Edoxabanum'),
(NEWID(), 'Panobinostatum'),
(NEWID(), 'Miconazoli nitras'),
(NEWID(), 'Flurbiprofen'),
(NEWID(), 'Doxylamini hydrogenosuccinas'),
(NEWID(), 'Lutetu '),
(NEWID(), 'Pembrolizumabum'),
(NEWID(), 'Octenidini dihydrochloridum'),
(NEWID(), 'Phenoxyethanolum'),
(NEWID(), 'Prednisoloni hemisuccinas'),
(NEWID(), 'Chlorhexidini hydrochloridum'),
(NEWID(), 'Acidum deoxycholicum'),
(NEWID(), 'Alirocumabum'),
(NEWID(), 'Tegafurum'),
(NEWID(), 'Gimeracilum'),
(NEWID(), 'Oteracilum'),
(NEWID(), 'Benzydamine hydrochloride'),
(NEWID(), 'Chlorphenamini maleas'),
(NEWID(), 'Irinotecani hydrochloridum trihydricum'),
(NEWID(), 'Sebelipazum alfa'),
(NEWID(), 'Asfotasum alfa'),
(NEWID(), 'Ceftolozanum'),
(NEWID(), 'Flurbiprofenum'),
(NEWID(), 'Afoxolanerum'),
(NEWID(), 'Acidum folinicum'),
(NEWID(), 'Ginkgo folii extractum siccum'),
(NEWID(), 'Dinatrii clodronas hedrahydricus'),
(NEWID(), 'Ipratropii bromidum'),
(NEWID(), 'Robenacoxibum'),
(NEWID(), 'Ritonavirum'),
(NEWID(), 'Pegbovigrastim'),
(NEWID(), 'Tylosini tartars '),
(NEWID(), 'Apomorphini hydrochloridum hemihydricu'),
(NEWID(), 'Ketoprofenum lysinum'),
(NEWID(), 'Cobimetinibum'),
(NEWID(), 'Testosteronum'),
(NEWID(), 'Sarolanerum'),
(NEWID(), 'Fluorocholini '),
(NEWID(), 'Blinatumomabum'),
(NEWID(), 'Carfilzomibum'),
(NEWID(), 'Ivabradini hydrochloridum'),
(NEWID(), 'Masitinib mesylate'),
(NEWID(), 'Monepantelum'),
(NEWID(), 'Pradofloxacinum'),
(NEWID(), 'Pyriprole'),
(NEWID(), 'Ivabradini oxala'),
(NEWID(), 'Emodepsyd'),
(NEWID(), 'Prazikwantel'),
(NEWID(), 'Emodepsidum'),
(NEWID(), 'Imidaklopryd'),
(NEWID(), 'Moksydektyna'),
(NEWID(), 'Halofuginon'),
(NEWID(), 'Valnemulinum'),
(NEWID(), 'Amsacrinum'),
(NEWID(), 'Clomipramine hydrochloridum'),
(NEWID(), 'Furazidinum'),
(NEWID(), 'Glyceroli phenylbutyras'),
(NEWID(), 'Permetrinum'),
(NEWID(), 'Eptifibatidum'),
(NEWID(), 'Lopinavirum'),
(NEWID(), 'Pegasparagasum'),
(NEWID(), 'dynoprost (w postaci soli z trometamolem)'),
(NEWID(), 'Amylmetacresolum'),
(NEWID(), 'Dichlorobenzyl Alcohol'),
(NEWID(), 'Eprynomektyna'),
(NEWID(), 'gentamycyna'),
(NEWID(), 'Moxifloxacinum'),
(NEWID(), 'Carbidopum monohydricum'),
(NEWID(), 'Duloxetine hydrochloride'),
(NEWID(), 'Osimertinibum'),
(NEWID(), 'Cinnarizinum'),
(NEWID(), 'Dimenhydrinatum'),
(NEWID(), 'Tadalafilum '),
(NEWID(), 'Aprepitantum'),
(NEWID(), 'Calcifediolum'),
(NEWID(), 'Oxytetracyclinum'),
(NEWID(), 'Ferrum (III)'),
(NEWID(), 'Necitumumabum'),
(NEWID(), 'Lesinuradum'),
(NEWID(), 'Ozenoxacinum'),
(NEWID(), 'O-(beta-hydroxyethyl)-rutosidea (Oxerutins)'),
(NEWID(), 'Vardenafil hydrochloride trihydrat'),
(NEWID(), 'Brivaracetamum'),
(NEWID(), 'Ertapenemum natricum'),
(NEWID(), 'Pitolisantum'),
(NEWID(), 'Eftrenonacogum alpha'),
(NEWID(), 'Clobasamum'),
(NEWID(), 'Thiocolchicosidum'),
(NEWID(), 'Alfacalcidolu'),
(NEWID(), 'Naloxoni hydrochloridum'),
(NEWID(), 'Tenofovirum alafenamidum'),
(NEWID(), 'Trifluridinum'),
(NEWID(), 'Tipiracilum'),
(NEWID(), 'Albutrepenonacogum alfa'),
(NEWID(), 'Metoclopramidi hydrochloridum'),
(NEWID(), 'Mieszanina mentolu i izowalerianianu mentylu'),
(NEWID(), 'Colchici seminis extractum siccum'),
(NEWID(), 'Atazanaviri sulfas'),
(NEWID(), 'Penethamate hydriodide'),
(NEWID(), 'Palonosetroni hydrochloridum'),
(NEWID(), 'Entecavirum monohydricum'),
(NEWID(), 'Erlotinibum'),
(NEWID(), 'Nevirapinum anhydricum'),
(NEWID(), 'Reslizumabum'),
(NEWID(), 'Thiopentalum natricum et natrii carbonas'),
(NEWID(), 'Propentofyllinum'),
(NEWID(), 'Trazodoni hydrochloridum'),
(NEWID(), 'Tiopental sodowy'),
(NEWID(), 'Betiatide'),
(NEWID(), 'Propylene glycol'),
(NEWID(), 'Atazanavirum'),
(NEWID(), 'Velpatasvirum'),
(NEWID(), 'Elbasvirum'),
(NEWID(), 'Grazoprevirum'),
(NEWID(), 'Cabozantinibum'),
(NEWID(), 'Palbociclibum'),
(NEWID(), 'Anagrelidum'),
(NEWID(), 'Paromomycin'),
(NEWID(), 'Codeinum'),
(NEWID(), 'Methoxyfluranum'),
(NEWID(), 'Cyanocobalaminum'),
(NEWID(), 'Atracurium'),
(NEWID(), 'Menotropinum (FSH i LH)'),
(NEWID(), 'Ixazomibum'),
(NEWID(), 'Etelcalcetidum'),
(NEWID(), 'Acidum obeticholicum'),
(NEWID(), 'Folitropinum delta'),
(NEWID(), 'Tyletaminum'),
(NEWID(), 'Zolazepamum'),
(NEWID(), 'Halofuginone ( as lactate salt)'),
(NEWID(), 'Tenofovirum disoproxilum fumaras'),
(NEWID(), 'Alectinibum'),
(NEWID(), 'Bezlotoxumabum'),
(NEWID(), 'Lonoctocog alfa'),
(NEWID(), 'Insulinum glarginum'),
(NEWID(), 'Miconazolum'),
(NEWID(), 'Sylibi mariani fructus extractum siccum'),
(NEWID(), 'triamcinolu acetonid'),
(NEWID(), 'Tanaceti parthenii herba'),
(NEWID(), 'Tolterodinum'),
(NEWID(), 'Gliquidonum'),
(NEWID(), 'Ceftobiprol'),
(NEWID(), 'Cyclopentolati hydrochloridum'),
(NEWID(), 'Baricitinibum'),
(NEWID(), 'Tofacitinibi citras'),
(NEWID(), 'Calcipotriolum'),
(NEWID(), 'Deltamethrinum'),
(NEWID(), 'Adalimumabum'),
(NEWID(), 'Miglustatum'),
(NEWID(), 'Cefaleksyna (jako cefaleksyna jednowodna) '),
(NEWID(), 'Sulfametoksazol'),
(NEWID(), 'Żelazo (III) (jako gleptoferron)'),
(NEWID(), 'Saccharomyces boulardii CNCM I'),
(NEWID(), 'Amoxiciclini trihydricum'),
(NEWID(), 'Mercaptamini hydrochloridum'),
(NEWID(), 'Opicaponum'),
(NEWID(), 'Agomelatyna'),
(NEWID(), 'Chlordiazepoxidum'),
(NEWID(), 'Dasatinibum'),
(NEWID(), 'Esomeprazolum natricum'),
(NEWID(), 'Colistinum'),
(NEWID(), 'cholekalcyferol'),
(NEWID(), 'Baclofenum'),
(NEWID(), 'Anagrelidi hydrochloridum monohydricu'),
(NEWID(), 'Tiotropium'),
(NEWID(), 'Paliperidonum'),
(NEWID(), 'Sarilumabum'),
(NEWID(), 'Ribociclibi succinas'),
(NEWID(), 'Cariprazine'),
(NEWID(), 'Lenalidomidum'),
(NEWID(), 'Nusinersenum natricum'),
(NEWID(), 'Pentozanu wielosiarczan sodowy'),
(NEWID(), 'Nonacogum beta pegylateum'),
(NEWID(), 'Febuxostatum'),
(NEWID(), 'Cenegerminum'),
(NEWID(), 'inotuzumabum ozogamicini'),
(NEWID(), 'Dupilumabum'),
(NEWID(), 'Acidum bempedoicum'),
(NEWID(), 'Midostaurinum'),
(NEWID(), 'bromoheksyny chlorowodorek'),
(NEWID(), 'Norgestimatum'),
(NEWID(), 'Flumetrinum'),
(NEWID(), 'Levothyroxine sodium'),
(NEWID(), 'Pelargonii radicis extractum siccum'),
(NEWID(), 'Plantaginis lanceolatae extractum'),
(NEWID(), 'Erlotinibi hydrochloridum'),
(NEWID(), 'Phenylbutazonum '),
(NEWID(), 'Atezolizumabum'),
(NEWID(), 'Doxycyclini hyclas '),
(NEWID(), 'S-Methoprenu'),
(NEWID(), 'Cerliponasum alfa'),
(NEWID(), 'Rifamycinum'),
(NEWID(), 'Octreotidum'),
(NEWID(), 'Lotilanerum'),
(NEWID(), 'Telotristati etipratun'),
(NEWID(), 'Mitoxantronum'),
(NEWID(), 'Biotinum'),
(NEWID(), 'Bilastinum'),
(NEWID(), 'Acidum tiocticum'),
(NEWID(), 'Norepinephrinu'),
(NEWID(), 'Temazepamum'),
(NEWID(), 'Ocrelizumabum'),
(NEWID(), 'Nitisinonum'),
(NEWID(), 'Avelumabum'),
(NEWID(), 'Padeliporfinum'),
(NEWID(), 'Letermovirum'),
(NEWID(), 'Rurioctocogum alfa pegolum'),
(NEWID(), 'Benralizumabum'),
(NEWID(), 'Oxycodone hydrochloride'),
(NEWID(), 'Dextromethorphani hydrochloridum'),
(NEWID(), 'Acidum zoledronicum monohydricum'),
(NEWID(), 'Oxalic acid dihydrat'),
(NEWID(), 'Semaglutidum'),
(NEWID(), 'Prasteronum'),
(NEWID(), 'Hydrocortisone'),
(NEWID(), 'Caspofunginum w postaci octanu:'),
(NEWID(), 'Detomidini hydrochloridum '),
(NEWID(), 'Burosumabum'),
(NEWID(), 'Melatoninum'),
(NEWID(), 'Calcii gluconas ad iniectabile'),
(NEWID(), 'Emicizumabum'),
(NEWID(), 'Sulfadiazinum'),
(NEWID(), 'Natrii salicylas'),
(NEWID(), 'Grapriprant'),
(NEWID(), 'Velmanasum alfa'),
(NEWID(), 'Darvadstrocelum'),
(NEWID(), 'Ertugliflozinum'),
(NEWID(), 'Rilpivirini hydrochloridum'),
(NEWID(), 'Bismuthi subnitras ponderosum'),
(NEWID(), 'Gemtuzumabum ozogamicinum'),
(NEWID(), 'Flecainidi acetas'),
(NEWID(), 'Carmustinum'),
(NEWID(), 'Peramivirum'),
(NEWID(), 'Formic acid'),
(NEWID(), 'Oxalic acid dihydrate '),
(NEWID(), 'Oxyclozanidum'),
(NEWID(), 'Benzylpenicillinum procainum monohydricum'),
(NEWID(), 'Febuxostatum hemihydricum'),
(NEWID(), 'Cytomegalovirus immunoglobulinum humanum'),
(NEWID(), 'Magnesii citras'),
(NEWID(), 'Cyclopiroxi olaminum'),
(NEWID(), 'Glibenclamide'),
(NEWID(), 'Pemetrexedum dinatricum hemipentahydricum'),
(NEWID(), 'Moxidectinum'),
(NEWID(), 'Amitrazum'),
(NEWID(), 'Sufentanili citras'),
(NEWID(), 'Butafosfanum'),
(NEWID(), 'Tiamulin hydrogen fumarate for veterinary use'),
(NEWID(), 'Flunixini megluminum '),
(NEWID(), 'Eprinomectinum'),
(NEWID(), 'Magnesii sulfas heptahydricus'),
(NEWID(), 'Betula Verrucosa'),
(NEWID(), 'Metreleptinum'),
(NEWID(), 'Erenumabum'),
(NEWID(), 'Eszopiclonum'),
(NEWID(), 'Tisagenlecleucelum'),
(NEWID(), 'Vonicogum alfa'),
(NEWID(), 'Axicabtagenum ciloleucelum'),
(NEWID(), 'Vestronidasum alfa'),
(NEWID(), 'Caplacizumabum'),
(NEWID(), 'Neratinibum'),
(NEWID(), 'Patisiranum natricum'),
(NEWID(), 'Chlorhexidini dihydrochloridum'),
(NEWID(), 'Treosulfan'),
(NEWID(), 'Pegfilgrastimum'),
(NEWID(), 'Encorafenibum'),
(NEWID(), 'Binimetinibum'),
(NEWID(), 'Tildrakizumabum'),
(NEWID(), 'Durvalumabum'),
(NEWID(), 'Eravacyclinum'),
(NEWID(), 'kabergolina'),
(NEWID(), 'Methylphenidati hydrochloridum'),
(NEWID(), 'Trifarotenum'),
(NEWID(), 'Abemaciclibum'),
(NEWID(), 'Galcanezumabum'),
(NEWID(), 'Fosfomycinum trometamolum'),
(NEWID(), 'Dexamethasoni phosphas'),
(NEWID(), 'Sildenafil citrate'),
(NEWID(), 'Passiflorae herba extractum siccum'),
(NEWID(), 'Noradrenalini tartras'),
(NEWID(), 'Erdosteinum'),
(NEWID(), 'Micafunginum natricum'),
(NEWID(), 'Oseltamiwiru fosforan'),
(NEWID(), 'Azacitidinum'),
(NEWID(), 'Dacomitinibum'),
(NEWID(), 'Codeini phosphas hemihydricus'),
(NEWID(), 'Butorphanoli tartras'),
(NEWID(), 'Fenylefryny chlorowodorek'),
(NEWID(), 'Selamectinum'),
(NEWID(), 'Apramycinum'),
(NEWID(), 'Brigatinibum'),
(NEWID(), 'Paclitaxelum'),
(NEWID(), 'Mexiletine hydrochloride'),
(NEWID(), 'Doravirinum'),
(NEWID(), 'Mogamulizumabum'),
(NEWID(), 'Lusutrombopagum'),
(NEWID(), 'Ropeginterferonum alfa'),
(NEWID(), 'Brigatinibum '),
(NEWID(), 'Naldemedinum'),
(NEWID(), 'Poractantum alfa'),
(NEWID(), 'Fremanezumabum'),
(NEWID(), 'Lorlatinibum'),
(NEWID(), 'Tulathromycinum'),
(NEWID(), 'Ludzki inhibitor alf'),
(NEWID(), 'Rucaparibum'),
(NEWID(), 'Karbocysteina'),
(NEWID(), 'Loteprednolu etabonian'),
(NEWID(), 'Sotagliflozinum'),
(NEWID(), 'Andexanetum alfa'),
(NEWID(), 'Sitagliptin hydrochloride monohydrate'),
(NEWID(), 'Dexamethasoni Natrii phosphas'),
(NEWID(), 'Vaccinum Variolae (vivum) nie mniej niż'),
(NEWID(), 'Arnicae tinctura'),
(NEWID(), 'Pegvaliasum'),
(NEWID(), 'Sorafenibum'),
(NEWID(), 'Sorafenibi Tosilas'),
(NEWID(), 'Metforminum'),
(NEWID(), 'Syldenafilu cytrynian'),
(NEWID(), 'Ambrisentanum'),
(NEWID(), 'wapnia węglan'),
(NEWID(), 'Paromomycyna '),
(NEWID(), 'Ferrum III'),
(NEWID(), 'Methotrexatum natricum'),
(NEWID(), 'Milbemycinum oximum '),
(NEWID(), 'Rivaroxabanum'),
(NEWID(), 'Ravulizumabum'),
(NEWID(), 'Turoctocogum alfa pegylateum'),
(NEWID(), 'Talazoparibum'),
(NEWID(), 'Sunitinib malate'),
(NEWID(), 'Sunitynibu jabłaczan'),
(NEWID(), 'Zinci dinatrii edetas'),
(NEWID(), 'Fludeoxythymidinum '),
(NEWID(), 'Pitavastinum calicum'),
(NEWID(), 'Angiotensinamidum'),
(NEWID(), 'Tetryzolini hydrochloridum'),
(NEWID(), 'Phentermini hydrochloridum'),
(NEWID(), 'Cefalonium'),
(NEWID(), 'Primulae extractum'),
(NEWID(), 'Thymus vulgaris'),
(NEWID(), 'Hyoscini butylbromidum (Scopolamini butylbromidum)'),
(NEWID(), 'Abirateroni acetas'),
(NEWID(), 'Diclofenacum diethylammonium'),
(NEWID(), 'Vardenafil hydrochloride trihydrate'),
(NEWID(), 'Larotrectinibum'),
(NEWID(), 'Natrii glycerophosphas'),
(NEWID(), 'Agni casti fructus extractum siccum'),
(NEWID(), 'Pyrantelum'),
(NEWID(), 'Apixabanum'),
(NEWID(), 'Atomoxetinum'),
(NEWID(), 'Lactulosum liquidum'),
(NEWID(), 'Mirtazapinum (as hemihydrate)'),
(NEWID(), 'Gilteritinibi fumaras'),
(NEWID(), 'Doxycyclini hyclas co odpowiada'),
(NEWID(), 'Netarsudili mesilas'),
(NEWID(), 'Noradrenaliny winian'),
(NEWID(), 'Romosozumabum'),
(NEWID(), 'Pergolidi mesilas'),
(NEWID(), 'Fostamatinibum'),
(NEWID(), 'Osilodrostatum'),
(NEWID(), 'Calcitriolum'),
(NEWID(), 'Polatuzumabum vedotinum'),
(NEWID(), 'Pridinol mesylate'),
(NEWID(), 'Menthae piperitae aetheroleum'),
(NEWID(), 'Romifidini hydrochloridum'),
(NEWID(), 'Linagliptinum'),
(NEWID(), 'Brolucizumabum'),
(NEWID(), 'Cloxacillinum (Cloxacillinum natricum)'),
(NEWID(), 'Imikwimod'),
(NEWID(), 'Thiamazolum '),
(NEWID(), 'Dabigatranu eteksylan w postaci mezylanu'),
(NEWID(), 'Levosimendanum'),
(NEWID(), 'Givosiranum'),
(NEWID(), 'Darolutamidum'),
(NEWID(), 'Cylastatyny sol sodowa'),
(NEWID(), 'Crisaborolum'),
(NEWID(), 'Rywastygmina'),
(NEWID(), 'Tapentadolu maleinian półwodny'),
(NEWID(), 'Solriamfetolum'),
(NEWID(), 'Tigilanol tiglate'),
(NEWID(), 'Isatuximabum'),
(NEWID(), 'Bismuthi subgallas'),
(NEWID(), 'Paliperydonu palmitynian'),
(NEWID(), 'Apomorphini hydrochloridum hemihydricum'),
(NEWID(), 'Fesoterodini fumaras'),
(NEWID(), 'Azaperonum'),
(NEWID(), 'Imidocarbi dipropionas'),
(NEWID(), 'Atorvastatin calcium trihydrate'),
(NEWID(), 'Streptokinasum'),
(NEWID(), 'Streptodornasum'),
(NEWID(), 'metyloprednizolonu octan'),
(NEWID(), 'Prednisoloni pivalas'),
(NEWID(), 'Toksyna botulinowa typu A'),
(NEWID(), 'Metoklopramidu chlorowodorek jednowodny'),
(NEWID(), 'Remdesivirum'),
(NEWID(), 'Bibrocatholum'),
(NEWID(), 'Icatibanti acetas'),
(NEWID(), 'Icatibantum'),
(NEWID(), 'Hydroxychloroquini sulphas'),
(NEWID(), 'Dabigatranum etexilatum'),
(NEWID(), 'Sitagliptini hydrochloridum monohydricum'),
(NEWID(), 'Fentanyli citras'),
(NEWID(), 'Entrectinibum'),
(NEWID(), 'Alpelisibum'),
(NEWID(), 'Pretomanidum'),
(NEWID(), 'Onasemnogenum abeparvovecum'),
(NEWID(), 'Bulevirtidum'),
(NEWID(), 'Glasdegibum'),
(NEWID(), 'Alfaxalonum'),
(NEWID(), 'Ioflupane '),
(NEWID(), 'Netilmicini sulfas'),
(NEWID(), 'Tetracosactidum'),
(NEWID(), 'Indakaterol'),
(NEWID(), 'Kabazytaksel'),
(NEWID(), 'Methylthioninii chloridum'),
(NEWID(), 'Chlorhexidini digluconatis solutio'),
(NEWID(), 'Halofuginoni lactas'),
(NEWID(), 'Cabotegravirum'),
(NEWID(), 'Filgotinibum'),
(NEWID(), 'Imlifidasum'),
(NEWID(), 'Bupivacainum'),
(NEWID(), 'Cefiderocolum'),
(NEWID(), 'Midazolamu maleinian'),
(NEWID(), 'Sugammadexum natricum'),
(NEWID(), 'Fostemsavirum'),
(NEWID(), 'Abirateronu octan'),
(NEWID(), 'Pazopanibi hydrochloridum'),
(NEWID(), 'Walsartan'),
(NEWID(), 'Acalabrutinibum'),
(NEWID(), 'Lumasiranum'),
(NEWID(), 'Dobutamine hydrochloride'),
(NEWID(), 'Bedinvetmab'),
(NEWID(), 'Ranolazinum'),
(NEWID(), 'Fenfluraminum'),
(NEWID(), 'Bendamustini hydrochloridum monohydricum'),
(NEWID(), 'Fingolimodi hydrochloridum'),
(NEWID(), 'Sugammadeks sodowy'),
(NEWID(), 'Baloxaviri marboxilum'),
(NEWID(), 'Albumini humani solutio'),
(NEWID(), 'Netarsudilum'),
(NEWID(), 'Tagraxofuspum'),
(NEWID(), 'Trastuzumabum deruxtecanum'),
(NEWID(), 'Etamsylatum'),
(NEWID(), 'Selpercatinibum'),
(NEWID(), 'Tucatinibum'),
(NEWID(), 'Glucagon hydrochloride'),
(NEWID(), 'Moxetumomabum pasudotoxum'),
(NEWID(), 'Calcii lactogluconas'),
(NEWID(), 'Tirbanibulinum'),
(NEWID(), 'Fluoroethyl-L-tyrosinum '),
(NEWID(), 'Levomethadoni hydrochloridum'),
(NEWID(), 'Suxibuzonum'),
(NEWID(), 'Arnica montana '),
(NEWID(), 'Risdiplamum'),
(NEWID(), 'Selinexorum'),
(NEWID(), 'Tapentadolu winian'),
(NEWID(), 'Rosuvastatin calcium'),
(NEWID(), 'Trilostanu'),
(NEWID(), 'Heksamidyna'),
(NEWID(), 'Cenobamate'),
(NEWID(), 'Ofatumumabum'),
(NEWID(), 'Fluticasone Propionate'),
(NEWID(), 'Sertaconazoli nitras'),
(NEWID(), 'Olej etiodowany'),
(NEWID(), 'Pantoprazol sodowy półtorawodny'),
(NEWID(), 'Frunevetmab'),
(NEWID(), 'Sunitinibi maleas'),
(NEWID(), 'Meldonium dihydratum'),
(NEWID(), 'Amlodypiny bezylan'),
(NEWID(), 'Ganirelix acetate'),
(NEWID(), 'Estetrolum'),
(NEWID(), 'Hydroksychlorochina'),
(NEWID(), 'Lapatynibu ditozylan jednowodny'),
(NEWID(), 'Amprolium hydrochloride'),
(NEWID(), 'Satralizumabum'),
(NEWID(), 'Roxadustatum'),
(NEWID(), 'kwas acetylosalicylowy'),
(NEWID(), 'Kalii clavulanas'),
(NEWID(), 'Evinacumabum'),
(NEWID(), 'Selumetinibum'),
(NEWID(), 'Abiraterone acetate'),
(NEWID(), 'Tralokinumabum'),
(NEWID(), 'Berotralstatum'),
(NEWID(), 'Duvelisibum'),
(NEWID(), 'Metoclopramide hydrochloride'),
(NEWID(), 'Dimethylis fumaras'),
(NEWID(), 'Omeprazol sodowy'),
(NEWID(), 'Karbidopa'),
(NEWID(), 'Oxaliplatinum'),
(NEWID(), 'Daryfenacyny bromowodorek'),
(NEWID(), 'Bosentanum monohydricum'),
(NEWID(), 'Enflicoxib'),
(NEWID(), 'Naltrexoni hydrochloridum'),
(NEWID(), 'vericiguatum'),
(NEWID(), 'Betametazonu dipropionian'),
(NEWID(), 'Odevixibatum'),
(NEWID(), 'Flubendazolum'),
(NEWID(), 'Bimekizumabum'),
(NEWID(), 'Vosoritidum'),
(NEWID(), 'Erythromycini cyclocarbonas'),
(NEWID(), 'Wenlafaksyny chlorowodorek'),
(NEWID(), 'Firocoxibum'),
(NEWID(), 'Sumatryptanu bursztynian'),
(NEWID(), 'Protamine sulfate'),
(NEWID(), 'Pentobarbitalum natricum'),
(NEWID(), 'Cloxacillinum benzathinum'),
(NEWID(), 'Casirivimabum'),
(NEWID(), 'Imdevimabum'),
(NEWID(), 'Escytalopramu szczawian'),
(NEWID(), 'Sacituzumabum govitecanum'),
(NEWID(), 'Paromomycinum'),
(NEWID(), 'Pralsetinibum'),
(NEWID(), 'Remimazolamum'),
(NEWID(), 'Zanubrutinibum'),
(NEWID(), 'NVX-Co'),
(NEWID(), 'Diroximelis fumaras'),
(NEWID(), 'Somapacitanum'),
(NEWID(), 'Anifrolumabum'),
(NEWID(), 'Sotorasibum'),
(NEWID(), 'Fexofenadini hydrochloridum'),
(NEWID(), 'Indocyanine green'),
(NEWID(), 'Metrocloprimidi hydrochloridum monohydricum'),
(NEWID(), 'Acidum formicum'),
(NEWID(), 'Artesunatum'),
(NEWID(), 'Abrocitinibum'),
(NEWID(), 'Phytomenadionum'),
(NEWID(), 'Dexamethasoni isonicotinas'),
(NEWID(), 'Sytagliptyny chlorwodorek jednowodny'),
(NEWID(), 'Nirmatrelvirum'),
(NEWID(), 'Insulin lispro'),
(NEWID(), 'Etynyloestradiolum'),
(NEWID(), 'Finerenonum'),
(NEWID(), 'Eptinezumabum'),
(NEWID(), 'Metformina'),
(NEWID(), 'Metforminy chlorowodorek'),
(NEWID(), 'Somatrogonum'),
(NEWID(), 'Teriparatide'),
(NEWID(), 'Tixagevimabum'),
(NEWID(), 'Cilgavimabum'),
(NEWID(), 'Tepotynib'),
(NEWID(), 'Semaglutide'),
(NEWID(), 'Glucarpidasum'),
(NEWID(), 'Ephedrini hydrochloridum'),
(NEWID(), 'Opicapone'),
(NEWID(), 'Baloxavir marboxil'),
(NEWID(), 'Cefalexinum benzathinum'),
(NEWID(), 'Tebentafuspum'),
(NEWID(), 'Bismuthi subnitras ponderosus'),
(NEWID(), 'Enfortumabum vedotini'),
(NEWID(), 'Cloprostenolum natricum'),
(NEWID(), 'Mosunetuzumabum'),
(NEWID(), 'betaine anhydrous'),
(NEWID(), 'Relugolixum'),
(NEWID(), 'Albumina osocza ludzkiego w postaci nanokoloidu'),
(NEWID(), 'Leuprorelini mesilas'),
(NEWID(), 'Capmatinibum'),
(NEWID(), 'Birch bark extract'),
(NEWID(), 'Pirfenidone'),
(NEWID(), 'Olipudase alfa'),
(NEWID(), 'linzagolix choline'),
(NEWID(), 'Midazolamu chlorowodorek'),
(NEWID(), 'Buserelinum'),
(NEWID(), 'Lonafarnibum'),
(NEWID(), 'Siponimod'),
(NEWID(), 'Ganirelixum'),
(NEWID(), 'Hydrocortisone aceponate'),
(NEWID(), 'Lecirelinum acetas'),
(NEWID(), 'Indigotinum'),
(NEWID(), 'Farycymab'),
(NEWID(), 'tezepelumab'),
(NEWID(), 'Asciminibum'),
(NEWID(), 'Awalglukozydaza alfa'),
(NEWID(), 'Valoctocogenum roxaparvovecum'),
(NEWID(), 'Melphalani flufenamidum'),
(NEWID(), 'Acepromazini maleas'),
(NEWID(), 'Lenacapavir'),
(NEWID(), 'Efgartigimod alfa'),
(NEWID(), 'Talidomid'),
(NEWID(), 'Vutrisiranum'),
(NEWID(), 'Tirzepatydum'),
(NEWID(), 'Sutimlimabum'),
(NEWID(), 'Nirsevimabum'),
(NEWID(), 'Teryflunomid'),
(NEWID(), 'Lutetii '),
(NEWID(), 'Gozetotyd'),
(NEWID(), 'Budezonid'),
(NEWID(), 'Lasmiditanum'),
(NEWID(), 'Oktreotydu octan'),
(NEWID(), 'Cephapirinum benzathinum'),
(NEWID(), 'Xylazini hydrochloridum '),
(NEWID(), 'Loncastuximabum tesirini'),
(NEWID(), 'Pleryksafor'),
(NEWID(), 'Abaloparatidum'),
(NEWID(), 'Mitapivati sulfas'),
(NEWID(), 'Delamanidum'),
(NEWID(), 'Almotriptanum'),
(NEWID(), 'Hydrocortisoni aceponas'),
(NEWID(), 'Tremelimumabum'),
(NEWID(), 'Etranacogenum dezaparvovecum'),
(NEWID(), 'Tolwaptan')